### PR TITLE
fix: ignore load jx-requirements.yml validation errors

### LINKED ISSUE #6936: jx boot swallows jx-requirements.yml validation errors
### Summary 

If you have syntax errors in `jx-requirements.yml`, they get swallowed and a generic error gets returned instead. This error obscures what is going wrong.

### Steps to reproduce the behavior

Make a syntax error in the `jx-requirements.yml` that is still valid YAML.
For example, add an additional field in the `environment.x.ingress.` such as below:

```yaml
- ingress:
    domain: staging.apps.ocp.kearos.net
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
  namespace: staging
  repository: env-staging
```

### Expected behavior

`jx boot` returning with an error, but logging the validation mistakes.

For example:

```bash
environments.1: Additional property namespace is not allowed
environments.2: Additional property namespace is not allowed)
```

### Actual behavior

```bash
error: unable to load jx-requirements.yml: jx-requirements.yml file not found
```

The culprit is the function `func LoadRequirementsConfig(dir string) (*RequirementsConfig, string, error) {}` in `config/install_requirements.go`.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1244
Kubernetes cluster v1.11.0+d4cacc0
kubectl            v1.16.7
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.3 build 19D76
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

OpenShift 3.11, how it was created -> https://joostvdg.github.io/openshift/rhos311-gcp-minimal/

### Operating system / Environment

Mac OS X 10.15.3 build 19D76

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

#### Which issue this PR fixes

fixes #6936

### CODE REVIEW

File: pkg/config/install_requirements.go [hunk 1]
```diff
@@ -520,10 +520,10 @@ func LoadRequirementsConfig(dir string) (*RequirementsConfig, string, error) {
 	for absolute != "" && absolute != "." && absolute != "/" {
 		fileName := filepath.Join(absolute, RequirementsConfigFileName)
 		config, err := LoadRequirementsConfigFile(fileName)
-		if err == nil {
-			return config, fileName, nil
+		if err != nil {
+			return nil, "", err
```
Comment (hferentschik) [inline pkg/config/install_requirements.go]: I don't think this is quite correct. If you look at the docs for this function, then you see that the intend is to walk up the filesystem to find the requirements file there. I am not saying this is good behaviour, just how it is. The reason for this is to be able to execute individual jx boot step in sub-directories of the requirements/dev repository. 

I am pretty sure that this change will brake this behaviour. 

To do what you are after, I think we need to split or at least pull out the file existence check from `LoadRequirementsConfigFile`. You need to be able to distinguish between the file not existing at all and the file not loadable due to a syntax error.

I think it would be great to add some tests around this as well. Should be quite straight forward, since _install_requirements_test.go_ already exists. One can just add a couple of more test scenarios to the _test_data_ directory. 

WDYT?

Comment (nodece) [reply pkg/config/install_requirements.go]: Thank you for your review! I know how to fix it.

Comment (nodece) [reply pkg/config/install_requirements.go]: Resolved it.

**Comment by hferentschik** [comment]
@nodece, fyi - the unit test failure:

```
--- FAIL: TestRequirementsConfigMarshalExistingFile (0.02s)
    install_requirements_test.go:62: 
        	Error Trace:	install_requirements_test.go:62
        	Error:      	Received unexpected error:
        	            	stat /tmp/test-requirements-config-142991987/subdir/**-requirements.yml: no such file or directory
        	            	checking if file /tmp/test-requirements-config-142991987/subdir/**-requirements.yml exists
        	            	github.com/jenkins-x/**/pkg/config.LoadRequirementsConfigFile
        	            		/workspace/source/pkg/config/install_requirements.go:542
        	            	github.com/jenkins-x/**/pkg/config.LoadRequirementsConfig
        	            		/workspace/source/pkg/config/install_requirements.go:524
        	            	github.com/jenkins-x/**/pkg/config_test.TestRequirementsConfigMarshalExistingFile
        	            		/workspace/source/pkg/config/install_requirements_test.go:61
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	Test:       	TestRequirementsConfigMarshalExistingFile
        	Messages:   	failed to load requirements file in subDir: /tmp/test-requirements-config-142991987/subdir
    install_requirements_test.go:63: 
        	Error Trace:	install_requirements_test.go:63
        	Error:      	unable to find file ""
        	Test:       	TestRequirementsConfigMarshalExistingFile
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x19a pc=0x10b0814]
goroutine 15 [running]:
testing.tRunner.func1(0xc000161300)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x11dcf60, 0x1f712b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/jenkins-x/**/pkg/config_test.TestRequirementsConfigMarshalExistingFile(0xc000161300)
	/workspace/source/pkg/config/install_requirements_test.go:65 +0x944
testing.tRunner(0xc000161300, 0x13c0f58)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
````

File: pkg/config/install_requirements.go [hunk 2]
```diff
@@ -525,6 +525,10 @@ func LoadRequirementsConfig(dir string) (*RequirementsConfig, string, error) {
 		if err == nil {
 			return config, fileName, nil
 		}
+		_, isPathErr := err.(*os.PathError)
```
Comment (hferentschik) [inline pkg/config/install_requirements.go]: Not sure whether an explicit `util.FileExists` would be better here. It might mean that we check for existence twice, but I don't think that matters. This is really now depending on an implementation detail and there is really no guarantee that `LoadRequirementsConfigFile` is going to pass up the `PathError`. It could for example wrap the error.

Comment (nodece) [reply pkg/config/install_requirements.go]: I think `errors.Wrap` is used. We need to `errors.Unwrap`.

Comment (nodece) [reply pkg/config/install_requirements.go]: Fixed

File: pkg/config/install_requirements.go (hunk 1 above)
Comment (hferentschik) [reply pkg/config/install_requirements.go]: I still would feel more comfortable if we prior to `config, err := LoadRequirementsConfigFile(fileName)` do an explicit file existence check:

```go
        absolute = filepath.Dir(absolute)
	exists, err := util.FileExists(fileName)
	if err != nil {
		return nil, "", err
	}

        if !exist {
            continue
       }

       config, err := LoadRequirementsConfigFile(fileName)
	if err == nil {
		return nil, "", err
	}
```

Something along these lines. I think that is easier to understand and it does also not rely on an implementation detail of `LoadRequirementsConfigFile`, namely that it does return the PathError directly. It might as well wrap it.

File: pkg/config/install_requirements_test.go [hunk 3]
```diff
@@ -407,4 +407,7 @@ func Test_LoadRequirementsConfig(t *testing.T) {
 			}
 		})
 	}
+
+	_, _, err := config.LoadRequirementsConfig(path.Join(testDataDir, "jx-requirements-syntax-error"))
```
Comment (hferentschik) [inline pkg/config/install_requirements_test.go]: Let's put this test into its own test function and give it a name which tells what we test, something like `Test_LoadRequirementsConfig_load_invalid_yaml`

I also think we should not only assert that an error is returned, but also that is the error we expect. For example by looking at the error message.

File: pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+    namespace: staging # syntax-error: property namespace is not allowed
+githubApp:
+  enabled: true
+gitops: true
+kaniko: true
+repository: nexus
+secretStorage: vault
+velero:
+  namespace: velero
+webhook: lighthouse
```
Comment (hferentschik) [inline pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml]: newlines missing

File: pkg/config/install_requirements.go (hunk 1 above)
Comment (nodece) [reply pkg/config/install_requirements.go]: I feel great!

File: pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml (hunk 4 above)
Comment (nodece) [reply pkg/config/test_data/jx-requirements-syntax-error/jx-requirements.yml]: Github ignored line 36. actually, I've added newlines.

File: pkg/config/install_requirements_test.go [hunk 5]
```diff
@@ -408,3 +408,14 @@ func Test_LoadRequirementsConfig(t *testing.T) {
...
 }
+
+func TestLoadRequirementsConfig_load_invalid_yaml(t *testing.T) {
+	testDir := path.Join(testDataDir, "jx-requirements-syntax-error")
+
+	absolute, err := filepath.Abs(testDir)
+	assert.NoError(t, err, "could not find absolute path of dir %s", testDataDir)
+
+	_, _, err = config.LoadRequirementsConfig(testDir)
+	requirementsConfigPath := path.Join(absolute, config.RequirementsConfigFileName)
```
Comment (hferentschik) [inline pkg/config/install_requirements_test.go]: 👍

File: pkg/config/install_requirements.go [hunk 6]
```diff
@@ -521,11 +521,19 @@ func LoadRequirementsConfig(dir string) (*RequirementsConfig, string, error) {
...
+		exists, err := util.FileExists(fileName)
+		if err != nil {
+			return nil, "", err
+		}
+
+		if !exists {
+			continue
+		}
+
+		config, err := LoadRequirementsConfigFile(fileName)
```
Comment (hferentschik) [inline pkg/config/install_requirements.go]: :+1

**Comment by hferentschik** [comment]
@nodece, thanks for your pull request and patience ;-) Much appreciated.

**Comment by nodece** [comment]
@hferentschik Thanks for your guidance! I am willing to participate with jx in GSoC 2020.  I looking forward to make more contributions.
