### PR TITLE
fix: Correct use of AWS credentials for vault

### LINKED ISSUE #6218: Problems with configuring vault for jx boot with externally created resources in AWS
### Summary 

When installing Jenkins-X with vault using `jx boot` in an EKS cluster there are some obstacles when the cloud resources needed by vault are created outside jx (in my case with terraform).

### Steps to reproduce the behavior

Added the following vault config in `jx-requirements.yml`:

```
vault:
  aws:
    dynamoDBRegion: eu-north-1
    dynamoDBTable: vault-data-dev
    iamUserName: vault_dev_eu-north-1
    kmsKeyId: redacted
    kmsRegion: eu-north-1
    s3Bucket: vault-unseal-dev.redacted
    s3Region: eu-north-1
```

Executed `jx boot` with the environment variables `VAULT_AWS_SECRET_ACCESS_KEY` and `VAULT_AWS_ACCESS_KEY_ID` set.

### Expected behavior

A vault would be created correctly.

### Actual behavior

`jx boot` failed:
```
Creating vault resources with following values, eu-north-1, vault_dev_eu-north-1, vault-data, vault-unseal-dev.redacted
error: creating vault: an error occurred while creating the vault resources: vault cloud formation template eks/templates/vault_cf_tmpl.yml doesn't exist
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step boot vault' command in directory 'systems/vault', output: ''
```

Turns out `jx step boot vault` expects the field `iamUserName` to be set, even though it's not needed. Also the values of the environment variables `VAULT_AWS_SECRET_ACCESS_KEY` and `VAULT_AWS_ACCESS_KEY_ID` are mixed together! That is I need to put the key id in `VAULT_AWS_SECRET_ACCESS_KEY` and the secret in `VAULT_AWS_SECRET_ACCESS_KEY`.

When running `jx boot` with the environment variables set in this mixed up fashion (after having to delete the vault CRD manually to get through) the vault got created correctly. But the pipeline steps doing `jx step helm apply` without --no-vault failed for me. The error indicated that the attempts to access vault was done in namespace jx and not the alternative I have configured.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1014
Kubernetes cluster v1.14.8-eks-b7174d
kubectl            v1.16.2
helm client        Client: v2.14.1+g5270352
git                2.16.2
Operating System   Mac OS X 10.15.1 build 19B88
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Kubernetes cluster

EKs cluster created with terraform.

### PR DESCRIPTION
**Pull request by msvticket**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Correct use of AWS credentials for vault when creating cloud resources outside of jx

Allow use of system vault in other namespace than jx

#### Which issue this PR fixes

fixes #6218

### CODE REVIEW

File: pkg/cmd/step/helm/step_helm_apply.go [hunk 1]
```diff
@@ -503,7 +503,7 @@ func defineAppsChartOverridingError(chartName string, err error) error {
 func (o *StepHelmApplyOptions) fetchSecretFilesFromVault(dir string, store configio.ConfigStore) ([]string, error) {
 	log.Logger().Debugf("Fetching secrets from vault into directory %q", dir)
 	files := []string{}
-	client, err := o.SystemVaultClient(kube.DefaultNamespace)
+	client, err := o.SystemVaultClient("")
```
Comment (ccojocar) [inline pkg/cmd/step/helm/step_helm_apply.go]: This will look up dynamically the dev namespace, which will allow a bit more flexibility. It seems like a good change.
