### PR TITLE
fix(cli): handle errors when doing a jx upgrade boot in non dev namespace

### LINKED ISSUE #6529: Boot upgrade without jx namespace in kube config
### Summary 

When executing `jx upgrade boot` with kube config NOT pointing to the `dev` (e.g., `jx`) Namespace, the output is as follows.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x22766da]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/gits.(*GitCLI).CreateAuthenticatedURL(0xc0009aea98, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workspace/source/pkg/gits/git_cli.go:581 +0x6a
github.com/jenkins-x/jx/pkg/cmd/upgrade.(*UpgradeBootOptions).cloneDevEnv(0xc00054ae40, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:488 +0x1b5
github.com/jenkins-x/jx/pkg/cmd/upgrade.(*UpgradeBootOptions).Run(0xc00054ae40, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:83 +0xad3
github.com/jenkins-x/jx/pkg/cmd/upgrade.NewCmdUpgradeBoot.func1(0xc000806280, 0xb162868, 0x0, 0x0)
        /workspace/source/pkg/cmd/upgrade/upgrade_boot.go:64 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000806280, 0xb162868, 0x0, 0x0, 0xc000806280, 0xb162868)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a8000, 0xc000309c00, 0x6608560, 0xc00000e010)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0006f9f88, 0xc0000a0058)
        /workspace/source/cmd/jx/app/jx.go:19 +0x185
main.main()
        /workspace/source/cmd/jx/jx.go:11 +0x32
```

### Steps to reproduce the behavior

Change the namespace in kube config to something other than Jenkins X `dev` namespace. Execute `jx upgrade boot`

### Expected behavior

An user-friendly message that tells that the problem is that kube config does not point to the `dev` Namespace.

### Actual behavior

`panic`

### Jx version

```
NAME               VERSION
jx                 2.0.1126
Kubernetes cluster v1.14.8-gke.17
kubectl            v1.17.1
git                2.23.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Any

### Operating system / Environment

Mac OS

### PR DESCRIPTION
**Pull request by ankitm123**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
`jx upgrade boot` in non-dev namespace results in a panic, this is due to the lack of error handling in the upgrade boot functionality. This PR adds the necessary checks, and some tests to validate it.

#### Which issue this PR fixes

fixes #6529

### CODE REVIEW

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 1]
```diff
@@ -521,10 +523,16 @@ func (o *UpgradeBootOptions) deleteLocalBranch(branch string) error {
...
 	jxClient, devNs, err := o.JXClientAndDevNamespace()
+	if err != nil {
+		return errors.Wrap(err, "failed to create/get jx client and dev namespace")
+	}
 	devEnv, err := kube.GetDevEnvironment(jxClient, devNs)
 	if err != nil {
 		return errors.Wrapf(err, "failed to get dev environment in namespace %s", devNs)
 	}
+	if devEnv == nil {
+		return errors.Wrapf(errors.New("Cannot find environment with dev selector"),"No development environment found for namespace %s", devNs)
```
Comment (abayer) [inline pkg/cmd/upgrade/upgrade_boot.go]: FYI, this is likely to have a lint failure due to the lack of a space after the comma.

Comment (ankitm123) [reply pkg/cmd/upgrade/upgrade_boot.go]: Fixed.

Comment (ankitm123) [reply pkg/cmd/upgrade/upgrade_boot.go]: all tests  passed. boot-vault seems to fail in the first attempt, and succeeds in the second, will take a look.

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 2]
```diff
@@ -449,13 +449,15 @@ func (o *UpgradeBootOptions) cherryPickCommits(cloneDir, fromSha, toSha string)
 
 func (o *UpgradeBootOptions) setupGitConfig(dir string) error {
 	jxClient, devNs, err := o.JXClientAndDevNamespace()
+	if err != nil {
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: +1 good catch
