### PR TITLE
fix: Ensure we are tracking a remote branch before attempting a pull …

### LINKED ISSUE #3897: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
```bash
[root@host-10-0-228-47 ~]# jx install --provider=kubernetes --on-premise
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Setting the dev namespace to: jx
Using helmBinary helm with feature flag: template-mode
Context "kubernetes-admin@kubernetes" modified.
Enabling helm template mode in the TeamSettings
Git configured for user:******* and email *******@***.com
Using helm2
Skipping tiller
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'
helm installed and configured
FATAL: initialise build packs failed: failed to reset hard to master in directory /root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes: git output: fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]': failed to run 'git reset --hard origin/master' command in directory '/root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes', output: 'fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''
```

```
[root@host-10-0-228-47 ~]# jx version
NAME               VERSION
jx                 2.0.108
Kubernetes cluster v1.13.3
kubectl            v1.13.3
helm client        Client: v2.13.1+g618447c
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.5.1804 (Core)
```

### LINKED ISSUE #4001: FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.
### Summary 
jx install error
### Steps to reproduce the behavior
run jx install error
### Expected behavior
install jx
### Actual behavior
FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.
### Jx version

```
jx version
NAME               VERSION
jx                 2.0.128
Kubernetes cluster v1.10.5-tke.4
kubectl            v1.10.5-tke.4
helm client        Client: v2.10.0+g9ad53aa
git                git version 1.8.3.1
Operating System   CentOS Linux release 7.5.1804 (Core)
The output of `jx version` is:
```

### Operating system / Environment

```
# jx install
? Select Jenkins installation type: Serverless Jenkins X Pipelines with Tekton
Setting the dev namespace to: jx
Using helmBinary helm with feature flag: template-mode
Context "master" modified.
? Cloud Provider kubernetes
Enabling helm template mode in the TeamSettings
Git configured for user: malingxin and email ***
Using helm2
Skipping tiller
Using helmBinary helm with feature flag: template-mode
Initialising Helm 'init --client-only'
helm installed and configured
FATAL: initialise build packs failed: git output: There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master: failed to run 'git pull' command in directory '/root/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes', output: 'There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master'
```

### PR DESCRIPTION
**Pull request by dgozalo**
fix: Ensure we are tracking a remote branch before attempting a pull build packs

Signed-off-by: Daniel Gozalo <dgozalo@cloudbees.com>

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
In both #3897  and #4001 users reported an error when pulling the buildpacks repository.

Upon investigation and after trying to reproduce the error, the conclusion reached is that the old clone function was sometimes cloning some repositories without setting a remote branch to track so it failed when a `git pull` was attempted.

The fix should attempt to fetch `origin`, checkout to the correct local branch and perform a `git branch --set-upstream-to=origin/<branch>` in order to set tracking information so the `git pull` doesn't 

#### Which issue this PR fixes

fixes #3897
fixes #4001

### CODE REVIEW

File: pkg/jenkinsfile/gitresolver/buildpack.go [hunk 1]
```diff
@@ -35,3 +41,29 @@ func InitBuildPack(gitter gits.Gitter, packURL string, packRef string) (string,
...
+		err = gitter.Checkout(dir, packRef)
+		if err != nil {
+			return err
+		}
+		err = gitter.SetUpstreamTo(dir, packRef)
+		if err != nil {
+			return errors.Wrapf(err, "there was a problem setting upstream to remote branch origin/%s", packRef)
+		}
+	}
+
```
Comment (warrenbailey) [inline pkg/jenkinsfile/gitresolver/buildpack.go]: Nice I like this.

File: pkg/jenkinsfile/gitresolver/buildpack.go [hunk 2]
```diff
@@ -35,3 +41,29 @@ func InitBuildPack(gitter gits.Gitter, packURL string, packRef string) (string,
 	}
 	return filepath.Join(dir, "packs"), err
 }
+
+func ensureBranchTracksOrigin(dir string, packRef string, gitter gits.Gitter) error {
```
Comment (warrenbailey) [inline pkg/jenkinsfile/gitresolver/buildpack.go]: just wondering if this should be part of the CloneOrPull function?

Comment (dgozalo) [reply pkg/jenkinsfile/gitresolver/buildpack.go]: I was thinking about that, too. I decided to do it ad hoc for these two issues because I don't know what impact it could have in the whole system right now and those issues were critical, but I think we should consider moving it.

Comment (warrenbailey) [reply pkg/jenkinsfile/gitresolver/buildpack.go]: I've just seen a similar problem when doing `jx upgrade platform` hence why I think this would be good in the CloneOrPull function. I can't see it doing causing any major problems and we could fix forward if we see them.

However we could do it in a two stage approach, merge this and then raise another change to refactor it. That way we'll close off the two critical issues whilst giving us a bit more time to test the wider impact?

Comment (dgozalo) [reply pkg/jenkinsfile/gitresolver/buildpack.go]: I think this would be a good approach, I just want to play it safe with this, then we can create an issue to make the general solution.
