### PR TITLE
fix: add confirmation to uninstall command

### LINKED ISSUE #4969: Improve jx uninstall
### Steps to reproduce the behavior

 jx uninstall 

### Expected behavior

clean the resource 

### Actual behavior

kubectl delete namespace xx

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.517
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [x] Classic Jenkins

### Operating system / Environment

I still remember, I ran the command ` jx uninstall `  on 2019-07-19 16:54 on a namespace which we used for produce.

It made a disaster and took our team for over 6 hours to repair .

the ` jx uninstall ` is terrible ,it delte the namespace  directly .

I wish the ` jx uninstall `  command will be improved,add the alert message ,tell the user that it will rm the  namespace or something.

### PR DESCRIPTION
**Pull request by warrenbailey**
Add confirmation message to uninstall and be explicit about what the command will do.

Signed-off-by: warrenbailey <warren@warrenbailey.net>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #4969

### CODE REVIEW

File: pkg/cmd/uninstall/uninstall.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ type UninstallOptions struct {
 
 var (
 	uninstall_long = templates.LongDesc(`
-		Uninstalls the Jenkins X platform from a Kubernetes cluster`)
+		Uninstalls the Jenkins X platform from a Kubernetes cluster. This will remove all Jenkins X components, secrets, config and namespaces including any environment related namespaces`)
```
Comment (pmuir) [inline pkg/cmd/uninstall/uninstall.go]: @warrenbailey I removed the period before including as it's not gramatically correct :-p

File: pkg/cmd/uninstall/uninstall.go [hunk 2]
```diff
@@ -60,6 +60,13 @@ func NewCmdUninstall(commonOpts *opts.CommonOptions) *cobra.Command {
 }
 
 func (o *UninstallOptions) Run() error {
+	fmt.Println("")
+	uninstall := util.Confirm("Uninstall JX - this command will remove all JX components and delete all namespaces created by Jenkins X. Do you wish to continue?", false,
```
Comment (pmuir) [inline pkg/cmd/uninstall/uninstall.go]: It might be nice to present the user with a list of what will be deleted here...

File: pkg/cmd/uninstall/uninstall.go (hunk 1 above)
Comment (warrenbailey) [reply pkg/cmd/uninstall/uninstall.go]: Definitely, good spot. That was terrible grammar :)

File: pkg/cmd/uninstall/uninstall.go (hunk 2 above)
Comment (warrenbailey) [reply pkg/cmd/uninstall/uninstall.go]: Yeah I can do that

Comment (pmuir) [reply pkg/cmd/uninstall/uninstall.go]: Sorry, I actually meant the names of the namespaces that will be deleted...

Comment (warrenbailey) [reply pkg/cmd/uninstall/uninstall.go]: ah ok, misunderstood. I could do that instead.
