### PR TITLE
fix: print a message instead of an error when vault cannot be listed

### LINKED ISSUE #3628: Banzaicloud vaults
### Summary 

I get this error:
```
 % jx get vaults
error: listing vaults in namespace 'jx': the server could not find the requested resource (get vaults.vault.banzaicloud.com)
```

### Steps to reproduce the behavior

Run `jx get vaults`

### Expected behavior

Should list my vaults

### Actual behavior

Returns error message

### Jx version

The output of `jx version` is:

```
 % jx version
NAME               VERSION
jx                 1.3.1098
jenkins x platform 0.0.3737
Kubernetes cluster v1.12.6-eks-d69f1b
kubectl            v1.13.4
helm client        &version.Version{SemVer:"v2.11.0+unreleased",
helm server        v2.13.1+g618447c
git                git version 2.19.2
Operating System   Unkown Linux distribution Linux version 4.19.30 (nixbld@localhost) (gcc version 7.4.0 (GCC)) #1-NixOS SMP Tue Mar 19 12:12:42 UTC 2019
```

### Jenkins type

- [x] Classic Jenkins
- [ ] Serverless Jenkins

### Kubernetes cluster

EKS

### Operating system / Environment

Nixos unstable

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #3628

### CODE REVIEW

File: pkg/jx/cmd/get_vault.go [hunk 1]
```diff
@@ -71,7 +72,8 @@ func (o *GetVaultOptions) Run() error {
 
 	vaults, err := vault.GetVaults(client, vaultOperatorClient, o.Namespace)
 	if err != nil {
-		return err
+		log.Infof("No vault found.")
```
Comment (hferentschik) [inline pkg/jx/cmd/get_vault.go]: 👍
