### PR TITLE
fix(prow): postsubmit jobs branches should be regexp

### LINKED ISSUE #6710: The release pipeline is triggered for a branch named `all-in-master`
### Summary 

I pushed changes on a new branch named `all-in-master`, and go 2 pipelines executed:
- the pull request one
- the release one

### Steps to reproduce the behavior

- create a branch named `all-in-master`, push it and create a PR

### Expected behavior

- only the pull request pipeline should be run

### Actual behavior

- both the PR pipeline and release pipeline are executed

Prow/Hook logs:

```
{"component":"hook","event-GUID":"07584628-4998-11ea-9ea9-0b5df18a57d9","event-type":"push","head":"61b8cfb5fc39771f9c31ce5369069fed9376a11d","level":"info","msg":"Push event.","org":"dailymotion","ref":"refs/heads/all-in-master","repo":"leo-dockerfiles4ci","time":"2020-02-07T10:53:10Z"}
{"component":"hook","event-GUID":"07584628-4998-11ea-9ea9-0b5df18a57d9","event-type":"push","head":"61b8cfb5fc39771f9c31ce5369069fed9376a11d","job":"release","level":"info","msg":"Creating a new prowjob.","name":"08073340-4998-11ea-861a-1ab038583b51","org":"dailymotion","plugin":"trigger","ref":"refs/heads/all-in-master","repo":"leo-dockerfiles4ci","time":"2020-02-07T10:53:10Z","type":"postsubmit"}
{"author":"vbehar","component":"hook","event-GUID":"0e2e6680-4998-11ea-86c1-9986ab044c0d","event-type":"pull_request","job":"pr-build","level":"info","msg":"Creating a new prowjob.","name":"0f7ca581-4998-11ea-861a-1ab038583b51","org":"dailymotion","plugin":"trigger","pr":9,"repo":"leo-dockerfiles4ci","time":"2020-02-07T10:53:23Z","type":"presubmit","url":"https://github.com/dailymotion/leo-dockerfiles4ci/pull/9"}
```

and the `config` configmap contains:

```
    postsubmits:
      dailymotion/leo-dockerfiles4ci:
      - agent: tekton
        branches:
        - master
        context: ""
        name: release
```

From https://github.com/jenkins-x/test-infra/blob/master/prow/jobs.md#how-to-configure-new-jobs it seems like the branch name is expected to be a regex, and this explains why the `all-in-master` name would match.

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1139
Kubernetes cluster v1.15.7-gke.23
kubectl            v1.15.7
helm client        Client: v2.14.3+g0e7f3b6
git                2.24.0
Operating System   Mac OS X 10.12.6 build 16G2136
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)

### Kubernetes cluster

GKE

### Operating system / Environment

mac

### PR DESCRIPTION
**Pull request by vbehar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

the `master` branch should be set as `^master$` in prow's postsubmit job, to avoid matching every branch with "master" in it.
this avoids triggering the release branch on non-master branches.

#### Special notes for the reviewer(s)

I haven't check if there is the same issue with lighthouse

#### Which issue this PR fixes

fixes #6710

### CODE REVIEW

File: pkg/prow/prow.go [hunk 1]
```diff
@@ -628,11 +629,8 @@ func (o *Options) GetPostSubmitJob(org, repo, branch string) (config.Postsubmit,
 
 	key := fmt.Sprintf("%s/%s", org, repo)
 	for _, p := range prowConfig.Postsubmits[key] {
-
-		for _, a := range p.Branches {
-			if a == branch {
-				return p, nil
-			}
+		if p.Brancher.ShouldRun(branch) {
```
Comment (hferentschik) [inline pkg/prow/prow.go]: So this actually panics atm:

```
--- FAIL: TestGetPostSubmitJob (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x52293f]
goroutine 65 [running]:
testing.tRunner.func1(0xc0004db600)
	/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x1890040, 0x2d00ef0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1af91ea, 0x6, 0x0, 0x0, ...)
	/usr/local/go/src/regexp/exec.go:527 +0x6f
regexp.(*Regexp).doMatch(...)
	/usr/local/go/src/regexp/exec.go:514
regexp.(*Regexp).MatchString(...)
	/usr/local/go/src/regexp/regexp.go:468
k8s.io/test-infra/prow/config.Brancher.ShouldRun(0x0, 0x0, 0x0, 0xc0006e0400, 0x1, 0x4, 0x0, 0x0, 0x1af91ea, 0x6, ...)
	/go/pkg/mod/k8s.io/test-infra@v0.0.0-20190131093439-a22cef183a8f/prow/config/jobs.go:222 +0x146
github.com/jenkins-x/**/pkg/prow.(*Options).GetPostSubmitJob(0xc00055bd08, 0x1af71d8, 0x4, 0x1af7108, 0x4, 0x1af91ea, 0x6, 0x0, 0x0, 0x0, ...)
	/workspace/source/pkg/prow/prow.go:632 +0x400
github.com/jenkins-x/**/pkg/prow_test.TestGetPostSubmitJob(0xc0004db600)
	/workspace/source/pkg/prow/prow_test.go:491 +0x42a
testing.tRunner(0xc0004db600, 0x1ba46f0)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a
```

I think the problem is in this code of `Brancher`:
```
	if len(br.Branches) == 0 || br.re.MatchString(branch) {
		return true
	}
```
Looks like `br.re` is nil.

File: pkg/prow/prow_test.go [hunk 2]
```diff
@@ -492,6 +492,7 @@ func TestGetPostSubmitJob(t *testing.T) {
 
 	assert.NotEmpty(t, job.Name, "job name is empty")
 	assert.Equal(t, "release", job.Name)
+	assert.Contains(t, "^master$", job.Branches)
```
Comment (hferentschik) [inline pkg/prow/prow_test.go]: Does this test actually pass for you?

File: pkg/prow/prow.go [hunk 3]
```diff
@@ -601,8 +600,10 @@ func (o *Options) GetReleaseJobs() ([]string, error) {
 	for repo, p := range prowConfig.Postsubmits {
 		for _, q := range p {
 			for _, b := range q.Branches {
+				branch := strings.TrimLeft(b, "^")
```
Comment (hferentschik) [inline pkg/prow/prow.go]: might be worth adding a comment here or extracting these lines into something like `prowBranchConfigToGitBranchName` (or something like that).

**Comment by vbehar** [comment]
Thanks for the review! I'll be off next week with no computer, I'll fix that when I'll be back.

**Comment by hferentschik** [comment]
> Thanks for the review! I'll be off next week with no computer, I'll fix that when I'll be back.

No problem.

File: pkg/prow/prow.go (hunk 1 above)
Comment (vbehar) [reply pkg/prow/prow.go]: yes, I forgot to call the func that compiles the regexes.

File: pkg/prow/prow.go (hunk 3 above)
Comment (vbehar) [reply pkg/prow/prow.go]: done

File: pkg/prow/prow_test.go (hunk 2 above)
Comment (vbehar) [reply pkg/prow/prow_test.go]: well now it does ;-)

**Comment by vbehar** [comment]
@hferentschik ok I fixed the issues

**Comment by abayer** [comment]
/lgtm

yaaaaaay. =)
