### PR TITLE
fix: making sure envconfig is not initialising nil structs

### LINKED ISSUE #7331: RequirementsConfig#OverrideRequirementsFromEnvironment populates nil values
Despite defining some structs in `RequirementsConfig` as pointers and setting the _omitempty_ property, the final `jx-requirement.yml` after running `jx boot` contains empty values for all possible struct even if not specified.

The cause lies in `RequirementsConfig#OverrideRequirementsFromEnvironment` which in turn calls `err := envconfig.InitWithOptions(&c, envconfig.Options{AllOptional: true})` which is responsible for the population of the empty structs.

This behaviour makes it hard to evolve the requirements in a backwards-compatible manner by introducing new pointer-based configuration options.

### PR DESCRIPTION
**Pull request by hferentschik**
- setting envconfig LeaveNil option to ensure nil structs are not initialised
- switching more override parameters to envconfig

fixes #7331

### CODE REVIEW

File: pkg/config/install_requirements.go [hunk 1]
```diff
@@ -872,92 +876,14 @@ func (i *IngressConfig) IsAutoDNSDomain() bool {
 
 // OverrideRequirementsFromEnvironment allows properties to be overridden with environment variables
 func (c *RequirementsConfig) OverrideRequirementsFromEnvironment(gcloudFn func() gke.GClouder) {
-	//init envconfig struct tags
-	err := envconfig.InitWithOptions(&c, envconfig.Options{AllOptional: true})
+	// struct members need to use explicit 'envconfig:"<var-name>"' unless there is a match between struct member navigation
+	// path and env variable name
+	err := envconfig.InitWithOptions(&c, envconfig.Options{AllOptional: true, LeaveNil: true, Prefix: "JX_REQUIREMENT"})
```
Comment (hferentschik) [inline pkg/config/install_requirements.go:881]: @garethjevans, this is the key change for the bug, using the option `LeaveNil`
