### PR TITLE
fix: Report error for nil pipeline for expected kind

### LINKED ISSUE #5183: Overriding entire pipeline fails
### Summary 
I am trying to run a custom pipeline that worked previously with the `yaml` below.  Now I get an error as shown below.

**NOTE:**  I noticed if I remove the `buildPack: none` at the top of the yaml file, then it does not error out.

### Steps to reproduce the behavior
Simply add the `yaml` to your `jenkins-x.yml` file and do a pull request.

### Expected behavior
The pipeline runs and the logs shows the custom steps. Using the following definition

```yaml
buildPack: none
pipelineConfig:
  pipelines:
    release:
      pipeline:
        agent:
          image: sharepointoscar/node:8
        stages:
          - name: Oscar Build Stage
            steps:
              - name: Get Node Version
                command: node
                args:
                  - --version
              - name: NPM Installar Por Favor
                command: npm
                args: 
                  - install               
            options:
              containerOptions:
                resources:
                  limits:
                    cpu: 0.4
                    memory: 256Mi
                  requests:
                    cpu: 0.2
                    memory: 128Mi
          - name: Oscar Test Stage
            steps:
              - name: Run MochaJS Tests
                command: npm
                args:
                  - test
            options:
              containerOptions:
                resources:
                  limits:
                    cpu: 0.4
                    memory: 256Mi
                  requests:
                    cpu: 0.2
                    memory: 128Mi
```

### Actual behavior
I get the error listed below.

```
Showing logs for build jenkins-oscar/sp-webpart/pr-1 #14 serverless-jenkins stage app-extension and container step-create-effective-pipeline
{"level":"info","msg":"Deleting and cloning the Jenkins X versions repo","time":"2019-08-22T23:26:27Z"}
{"level":"info","msg":"Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /builder/home/.jx/jenkins-x-versions","time":"2019-08-22T23:26:27Z"}
{"level":"info","msg":"Effective pipeline written to jenkins-x-serverless-jenkins-effective.yml","time":"2019-08-22T23:26:29Z"}

Showing logs for build jenkins-oscar/sp-webpart/pr-1 #14 serverless-jenkins stage app-extension and container step-create-tekton-crds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x11dcb4a]

goroutine 1 [running]:
github.com/jenkins-x/jx/pkg/tekton/syntax.(*ParsedPipeline).GenerateCRDs(0x0, 0xc00050b1a0, 0x25, 0x7ffde6032651, 0x2, 0xc000dc2440, 0x1f, 0xc000645ddc, 0x2, 0xc0005461e0, ...)
	/workspace/source/pkg/tekton/syntax/pipeline.go:1523 +0x3a
github.com/jenkins-x/jx/pkg/cmd/step/create.(*StepCreateTaskOptions).generateTektonCRDs(0xc0003222c0, 0xc0006c0630, 0xc000645ddc, 0x2, 0xc00050b1a0, 0x25, 0xc000dc2440, 0x1f, 0x0, 0x53267c0, ...)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:543 +0x18f
github.com/jenkins-x/jx/pkg/cmd/step/create.(*StepCreateTaskOptions).Run(0xc0003222c0, 0x0, 0x0)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:323 +0x66a
github.com/jenkins-x/jx/pkg/cmd/step/create.NewCmdStepCreateTaskAndOption.func1(0xc000624500, 0xc0000bc380, 0x8, 0x34)
	/workspace/source/pkg/cmd/step/create/step_create_task.go:146 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc000624500, 0xc0000bc000, 0x34, 0x38, 0xc000624500, 0xc0000bc000)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ae280, 0xc00034c550, 0x530c2c0, 0xc00000e010)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/jenkins-x/jx/cmd/jx/app.Run(0x0, 0x0, 0x0, 0xc0009eff88, 0xc0000a0058)
	/workspace/source/cmd/jx/app/jx.go:19 +0x147
main.main()
	/workspace/source/cmd/jx/jx.go:11 +0x32

Pipeline failed on stage 'app-extension' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.598
jenkins x platform 2.0.951
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.3
helm client        Client: v2.13.1+g618447c
git                2.21.0
Operating System   Mac OS X 10.14.3 build 18D42
```

### Jenkins type

- [ x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
What kind of Kubernetes cluster are you using & how did you create it?
Using GKE, used the following command to create cluster:

```bash
jx create cluster -n mycluster --tekton --no-tiller --default-admin-password=mypassword
```

### Operating system / Environment

In which environment are you running the jx CLI?
OS X Mojave 10.14.3

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Previously, we'd just end up with a nil pointer, and that's...never helpful. This will instead report an error for when there is no pipeline of a given kind in the effective config.

Also, I reworked how we check for expected errors in the test, and made `override.MatchesPipeline` case-insensitive, since we've got `pullrequest` in some places and `pullRequest` in others. Sigh.

#### Special notes for the reviewer(s)

/assign @hferentschik 

#### Which issue this PR fixes

fixes #5183

### CODE REVIEW

File: pkg/config/project_config.go [hunk 1]
```diff
@@ -161,5 +161,9 @@ func (c *ProjectConfig) GetPipeline(kind string) (*syntax.ParsedPipeline, error)
 	default:
 		return nil, fmt.Errorf("unknown pipeline kind %s", kind)
 	}
+
+	if parsed == nil {
+		return nil, fmt.Errorf("no pipeline defined for kind %s", kind)
```
Comment (hferentschik) [inline pkg/config/project_config.go]: I'd use errors.Errorf for this in order to consistently use a single package for dealing with errors - `errors.New`, `errors.Errorf`, `errors.Wrap` and `errors.Wrapf`.

File: pkg/config/project_config_test.go [hunk 2]
```diff
@@ -93,10 +93,12 @@ func TestGetPipeline(t *testing.T) {
 	assert.NotNil(t, releasePipeline)
 
 	pullRequestPipeline, err := testProjectConfigMaven.GetPipeline(jenkinsfile.PipelineKindPullRequest)
-	assert.NoError(t, err)
+	assert.NotNil(t, err)
```
Comment (hferentschik) [inline pkg/config/project_config_test.go]: `assert.Error`?

File: pkg/config/project_config_test.go [hunk 3]
```diff
@@ -93,10 +93,12 @@ func TestGetPipeline(t *testing.T) {
...
+	assert.Equal(t, err.Error(), "no pipeline defined for kind pullrequest")
 	assert.Nil(t, pullRequestPipeline)
 
 	featurePipeline, err := testProjectConfigMaven.GetPipeline(jenkinsfile.PipelineKindFeature)
-	assert.NoError(t, err)
+	assert.NotNil(t, err)
```
Comment (hferentschik) [inline pkg/config/project_config_test.go]: `assert.Error`?

File: pkg/tekton/syntax/pipeline.go [hunk 4]
```diff
@@ -1884,7 +1884,7 @@ func (p *PipelineOverride) AsStepsSlice() []*Step {
 
 // MatchesPipeline returns true if the pipeline name is specified in the override or no pipeline is specified at all in the override
 func (p *PipelineOverride) MatchesPipeline(name string) bool {
-	if p.Pipeline == "" || p.Pipeline == name {
+	if p.Pipeline == "" || strings.EqualFold(p.Pipeline, name) {
```
Comment (hferentschik) [inline pkg/tekton/syntax/pipeline.go]: Never seen this one before ;-) Had to look up what this method does. 

So we generally don't want to care about capitalisation? So 'RELEASE', 'Release' or 'release' is all the same for us?

File: pkg/cmd/step/create/step_create_task_test.go [hunk 5]
```diff
@@ -335,6 +337,15 @@ func TestGenerateTektonCRDs(t *testing.T) {
...
 			kind:         "release",
 		},
+		{
+			name:                  "no_pipeline_for_kind",
+			language:              "none",
+			repoName:              "js-test-repo",
+			organization:          "abayer",
+			branch:                "really-long",
+			kind:                  "release",
+			effectiveProjectError: fmt.Errorf("%s", "no pipeline defined for kind release"),
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/cmd/step/create/step_create_task_test.go]: Ok, works for me.

File: pkg/config/project_config.go (hunk 1 above)
Comment (abayer) [reply pkg/config/project_config.go]: Ok.

File: pkg/config/project_config_test.go (hunk 2 above)
Comment (abayer) [reply pkg/config/project_config_test.go]: Whoops. =)

File: pkg/tekton/syntax/pipeline.go (hunk 4 above)
Comment (abayer) [reply pkg/tekton/syntax/pipeline.go]: I'd prefer to care about case, but given that we have `pullRequest` in the syntax but `pullrequest` as the actual kind...we're kind of stuck with case insensitivity.

Comment (hferentschik) [reply pkg/tekton/syntax/pipeline.go]: > I'd prefer to care about case,

+1

> but given that we have pullRequest in the syntax but pullrequest as the actual kind...we're kind of stuck with case insensitivity.

Wonder whether there would be a way to sort this out. I can already seeing this biting us back one day.
