### PR TITLE
fix(pipeline): Don't use `dir` as container `workingDir`

### LINKED ISSUE #5584: dir pipeline option fails if directory does not exist in master
### Summary 
I was creating a Ruby application in a new repository. I had a basic skeleton of code in master but nothing else. I created a PR to add a charts directory with both the main chart and the preview chart, a Dockerfile to build it and a jenkins-x.yml with a single line ```buildPack: ruby```.

This failed with the following error:
```
sh: 0: getcwd() failed: No such file or directory
make: getcwd: No such file or directory
make: *** No rule to make target 'preview'.  Stop.
```

I played around with the pipeline and discovered the `dir` directive would not work for directories created in that PR. For example, in the following the first command would work but the second would fail
``` 
- command: cd /workspace/source/charts/preview && ls -a
 - command: ls -a
   dir: /workspace/source/charts/preview
```

### Steps to reproduce the behavior
1. Create new github repo
1. Add a basic ruby file
1. Merge to master
1. Create a PR with a jenkins-x.yml and a chart directory

### Expected behavior

The build should run successfully and create a preview environment

### Actual behavior
The build errors with:
sh: 0: getcwd() failed: No such file or directory
make: getcwd: No such file or directory
make: *** No rule to make target 'preview'.  Stop.

### Jx version

The output of `jx version` is:

```
jx                 2.0.758
Kubernetes cluster v1.13.7-gke.19
kubectl            v1.15.0
helm client        Client: v2.14.2+ga8b13cc
git                2.22.0
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

`dir` can cause problems if you try to use it with a directory created in a previous step, or directories added in the PR being built. So let's change this to insert `cd $DIR && ...` in front of the actual commands instead.

#### Special notes for the reviewer(s)

/assign @hferentschik 
/assign @warrenbailey 

#### Which issue this PR fixes

fixes #5584

### CODE REVIEW

File: pkg/tekton/syntax/pipeline.go [hunk 1]
```diff
@@ -1416,17 +1416,24 @@ func generateSteps(step Step, inheritedAgent, sourceDir string, baseWorkingDir *
...
-	if !filepath.IsAbs(workingDir) {
-		workingDir = filepath.Join(WorkingDirRoot, sourceDir, workingDir)
+	if !filepath.IsAbs(targetDir) {
+		targetDir = filepath.Join(WorkingDirRoot, sourceDir, targetDir)
 	}
 
 	if step.GetCommand() != "" {
+		var targetDirPrefix []string
+		if targetDir != workingDir {
+			targetDirPrefix = append(targetDirPrefix, "cd", targetDir, "&&")
```
Comment (hferentschik) [inline pkg/tekton/syntax/pipeline.go]: Interesting, so it really never when into the specified directory.
