### PR TITLE
fix: hide warning when override is not relevant

### LINKED ISSUE #5104: jx boot outputs numerous WARNING messages when templating
### Summary 
During installation of Jenkins X numerous WARNING messages are displayed when templating, however the installation appears to complete successfully

### Steps to reproduce the behaviour
- Create a cluster
- Install Jenkins X using `jx boot`

### Expected behaviour
The frequency of the WARNING messages are reduced or removed unless it will impact the installation of Jenkins X

### Jx version

The output of `jx version` is:

```
🙅 developer ~/go-workspace()$ jx version
NAME               VERSION
jx                 2.0.597
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.2
helm client        Client: v2.14.3+g0e7f3b6
git                2.22.0
Operating System   Alpine Linux 3.10.1
WARNING: 
A new jx version is available: 2.0.598
? Would you like to upgrade to the new jx version? [? for help] (Y/n) 
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #5104

### CODE REVIEW

File: pkg/cmd/step/helm/step_helm_apply.go [hunk 1]
```diff
@@ -385,6 +385,10 @@ func (o *StepHelmApplyOptions) applyTemplateOverrides(chartName string) error {
 				depChartName := writeTemplateParts[len(writeTemplateParts)-3]
 				templateName := writeTemplateParts[len(writeTemplateParts)-1]
 				depChartDir := filepath.Join(depChartsDir, depChartName)
+				if _, err := os.Stat(depChartDir); os.IsNotExist(err) {
```
Comment (ccojocar) [inline pkg/cmd/step/helm/step_helm_apply.go]: nit: there is a `util.FileExits` for this check
