### PR TITLE
fix: jx upgrade boot failure when duplicate commits

### LINKED ISSUE #6970: jx upgrade boot can fail when duplicate commits in the upgrade
### Summary 

`jx upgrade boot` can fail with the following error if there are duplicate commit's contained within the upgrade of the boot config

```
error: failed to update boot configuration: failed to cherry pick upgrade commits: cherry-picking <commit_id>: git output: The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
On branch <branch_name>
You are currently cherry-picking commit <commit_id>.
```

### PR DESCRIPTION
**Pull request by macox**
Signed-off-by: Mark Cox <markcox20@hotmail.com>
#### Description

`jx upgrade boot` fails with the following error if there are duplicate commit's 

```
error: failed to update boot configuration: failed to cherry pick upgrade commits: cherry-picking <commit_id>: git output: The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git reset'
On branch <branch_name>
You are currently cherry-picking commit <commit_id>.
```

fixes #6970

### CODE REVIEW

**Comment by abayer** [comment]
@macox - could you create an issue and do the `fixes #...` dance so we get this in the release notes properly? Thanks!

File: pkg/gits/git_cli.go [hunk 1]
```diff
@@ -1223,6 +1223,11 @@ func (g *GitCLI) CherryPickTheirs(dir string, commitish string) error {
 	return g.gitCmd(dir, "cherry-pick", commitish, "--strategy=recursive", "-X", "theirs")
 }
 
+// CherryPickTheirsKeepRedundantCommits does a git cherry-pick of commit
+func (g *GitCLI) CherryPickTheirsKeepRedundantCommits(dir string, commitish string) error {
```
Comment (hferentschik) [inline pkg/gits/git_cli.go]: Would it make sense to have a test case? It might also help to understand what we try to fix here.

Comment (hferentschik) [reply pkg/gits/git_cli.go]: or maybe it would be enough to understand:

> jx upgrade boot fails with the following error if there are duplicate commit's

how come there are duplicate commits? How does one get into this state?

**Comment by hferentschik** [comment]
The MockGitter would need updating as well.

File: pkg/gits/git_cli.go (hunk 1 above)
Comment (macox) [reply pkg/gits/git_cli.go]: That is a good question. From what I can see....
A PR is created containing a commit. Another PR is then created containing a commit with the same change as the first. Both PR's are merged.
When cherry-picking the commits the second one throws an error as in the description. (btw. adding --allow-empty to the cherry-pick command didn't work.)

Comment (hferentschik) [reply pkg/gits/git_cli.go]: Thanks for the clarification.

**Comment by macox** [comment]
> As mentioned before, I don't think cherry-picking is the right thing to do here in general and I also think that the way we evolve the GitCli interface is not really helpful. 
> 
> However, this is the way things are atm and the change is not making things worth by any means.

Totally agree
