### PR TITLE
fix: Don't include pipeline runs that failed/were retried by Prow in logs

### LINKED ISSUE #6061: "jx get build logs" can include failed-but-auto-retried-by-Prow pipelines
There are a couple race conditions in Tekton that can result in a `PipelineRun` failing for no good reason. We've tweaked Prow to automatically retry in those scenarios, but you can still get errors running `jx get build logs` in batch mode with a report that there are multiple builds matching the filter. We should just exclude the fail-right-away-and-retry cases from `jx get build logs`.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

The immediate impetus here is that BDD tests can fail in this scenario, because more than one pipeline is found for the filter - the one that failed, and the one that was retried. But this should just clean things up a bit anyway.

#### Special notes for the reviewer(s)

~~I'll come back and add tests for this later today.~~
EDIT: Test added.

/assign @dgozalo 

#### Which issue this PR fixes

fixes #6061

### CODE REVIEW

File: pkg/logs/tekton_logging_test.go [hunk 1]
```diff
@@ -803,6 +805,133 @@ func TestGetRunningBuildLogsMetapipelineAndPendingGenerated(t *testing.T) {
...
+		Namespace:    ns,
+		LogWriter: &TestWriter{
+			StreamLinesLogged: make([]string, 0),
+			SingleLinesLogged: make([]string, 0),
+		},
+		LogsRetrieverFunc: LogsProvider,
+	}
+
+	_, err := jxClient.JenkinsV1().PipelineActivities(ns).Create(&v1.PipelineActivity{
+		ObjectMeta: v12.ObjectMeta{
```
Comment (hferentschik) [inline pkg/logs/tekton_logging_test.go]: I'd try to separate the test setup out a bit. It is hard to narrow down on the actual test(assertion).
The whole set up of the fake client could, for example, happen in a _setUp_ function and the resources itself could be extracted and appropriately named, e.g. `succeededPipelineRun`, `activePipelineRun`.

File: pkg/logs/tekton_logging.go [hunk 2]
```diff
@@ -103,6 +103,13 @@ func (t TektonLogger) GetTektonPipelinesWithActivePipelineActivity(filters []str
 	prMap := make(map[string][]*tektonapis.PipelineRun)
 	for _, pr := range tektonPRs.Items {
 		p := pr
+		prStatus := p.Status.GetCondition(knativeapis.ConditionSucceeded)
+		// Don't include any pipeline runs that failed due to Tekton race conditions and were auto-restarted by Prow
+		if prStatus != nil && prStatus.IsFalse() &&
+			(strings.Contains(prStatus.Message, "can't be found:pipeline.tekton.dev") ||
```
Comment (hferentschik) [inline pkg/logs/tekton_logging.go]: That seems brittle. Depending on status message text/format.Is this the best we can do?

Comment (abayer) [reply pkg/logs/tekton_logging.go]: Sadly, yes.

File: pkg/logs/tekton_logging_test.go (hunk 1 above)
Comment (abayer) [reply pkg/logs/tekton_logging_test.go]: Ok, will do tomorrow.

File: pkg/logs/tekton_logging.go (hunk 2 above)
Comment (hferentschik) [reply pkg/logs/tekton_logging.go]: :-(

File: pkg/logs/tekton_logging_test.go (hunk 1 above)
Comment (abayer) [reply pkg/logs/tekton_logging_test.go]: So the `PipelineRun`s still differ too much to go that route. I did tease out the `PA1` `PipelineActivity` creation, but the cases where we create runs rather than just load from the disk are a hassle - if I have a chance today, I'm going to tweak those to load from disk instead.

Comment (abayer) [reply pkg/logs/tekton_logging_test.go]: Ok, moved the runs to be loaded from disk. I left the activities as is.
