### PR TITLE
fix: Optionally write OWNERS file for dev env repo during boot

### LINKED ISSUE #6457: GitOps approvals blocked under Boot install
### Summary 
I attempted to add the SSO app with `jx add app jx-app-sso` and this uses a PR on Dev to install a chart. The promotion build succeeds but the PR is never merged. If I try to `/lgtm` the PR, I see the `This PR is not approved' message and a request to add additional approvers.

The dev environment for a cluster created using boot is instantiated with an OWNERS file that is populated with the accounts of the Jenkins-X team, only.

Not sure if this is an extension of the Github Case Sensitivity Saga or a failure to authorise users on the Dev environment. I am seeing webhooks being logged.

If I force the merge, the deployment kicks off automatically and boot runs, although it fails subsequently due to what appears to be another bug.

There is no OWNERS file in the Dev environment of legacy clusters, so this looks like a config problem.

### Jx version

The output of `jx version` is:

```
AME               VERSION
jx                 2.0.1103
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.17.0
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.15.2 build 19C57
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow) - Boot
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Prompt for dev env repo approvers during `jx step verify preinstall`, if not specified in `jx-requirements.yml` and not run non-interactively, and write the list of provided users to the `OWNERS` file in the dev env repo.

#### Special notes for the reviewer(s)

I did a hacked BDD test here to specify approvers in the `jx-requirements.yml` and it worked, but I'm removing that for obvious reasons. =)

#### Which issue this PR fixes

fixes #6457

### CODE REVIEW

File: pkg/cmd/step/verify/step_verify_preinstall.go [hunk 1]
```diff
@@ -679,6 +708,22 @@ func (o *StepVerifyPreInstallOptions) gatherGitRequirements(requirements *config
...
+		approversString, err := util.PickValue(
+			"Comma-separated git provider usernames of approvers for development environment repository",
+			"",
+			true,
+			"Pull requests to the development environment repository require approval by one or more "+
+				"users, specified in the 'OWNERS' file in the repository. Please specify a comma-separated "+
+				"list of usernames for your Git provider to be used as approvers.",
+			o.GetIOFileHandles())
+		if err != nil {
+			return errors.Wrap(err, "error configuring approvers for development environment repository")
```
Comment (ccojocar) [inline pkg/cmd/step/verify/step_verify_preinstall.go]: nit: you don't need to prefix the error messages with `error`.  The message it will look like: `error: error configuring ...`.

File: pkg/cmd/step/verify/step_verify_preinstall.go [hunk 2]
```diff
@@ -643,9 +646,35 @@ func (o *StepVerifyPreInstallOptions) gatherRequirements(requirements *config.Re
...
+	err = o.writeOwnersFile(requirements)
+	if err != nil {
+		return nil, errors.Wrapf(err, "error writing approves to OWNERS file in %s", o.Dir)
+	}
+
 	return requirements, nil
 }
 
+func (o *StepVerifyPreInstallOptions) writeOwnersFile(requirements *config.RequirementsConfig) error {
+	if len(requirements.Cluster.DevEnvApprovers) > 0 {
```
Comment (ccojocar) [inline pkg/cmd/step/verify/step_verify_preinstall.go]: Shouldn't we generate an empty OWNERS file even though when the `DevEnvApprovers` is empty? I think not doing this, it will keep the original OWNERS with our handlers into it, which is not quite right.

**Comment by ccojocar** [comment]
This is also related to issue #6073.

File: pkg/cmd/step/verify/step_verify_preinstall.go (hunk 2 above)
Comment (abayer) [reply pkg/cmd/step/verify/step_verify_preinstall.go]: For right now, I’m opting to not change any behavior if no values are specified, but in the follow up #6465, we will require the field be not empty and will always overwrite.

File: pkg/cmd/step/verify/step_verify_preinstall.go (hunk 1 above)
Comment (abayer) [reply pkg/cmd/step/verify/step_verify_preinstall.go]: Doh, will fix.
