### PR TITLE
fix: Remove defunct CloudBees addon

### LINKED ISSUE #5923: Remove defunct CloudBees addon
This isn't a thing any more, so it should be removed.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #5923

### CODE REVIEW

**Comment by hferentschik** [comment]
/lgtm

These ones you can bringing on :-)

File: pkg/cmd/cloudbees/cloudbees.go [hunk 1]
```diff
@@ -1,224 +0,0 @@
...
-func NewCmdCloudBees(commonOpts *opts.CommonOptions) *cobra.Command {
-	options := &CloudBeesOptions{
-		CommonOptions: commonOpts,
-	}
-	cmd := &cobra.Command{
-		Use:     "cloudbees",
-		Short:   "Opens the CloudBees app for Kubernetes for visualising CI/CD and your environments",
-		Long:    core_long,
-		Example: core_example,
-		Aliases: []string{"cloudbee", "cb", "ui", "jxui"},
```
Comment (hferentschik) [inline pkg/cmd/cloudbees/cloudbees.go]: On closer inspection this should not be removed ;-)

This is the `jx ui` command which does the port forward to open the UI on localhost in case the UI is not installed with SSO. 

I think it is unfortunate that the commands main name is 'cloudbees'. I guess the description is also a bit off as well. 

Given that the way we document this in the distribution docs is `jx ui`, what we could do is:

* make the main name of this command "ui"
* rename file and package to get rid of 'cloudbees'
* add 'cloudbees' as alias for good measure in case someone is actually using it

BTW,  that seems wrong as well:

> 		# Print the Jenkins X console URL but do not open a browser
>		jx console -u`)

Should probably be `jx ui -u`

Comment (abayer) [reply pkg/cmd/cloudbees/cloudbees.go]: whoops! I'll clean this up on Monday.

**Comment by ccojocar** [comment]
@abayer I have already removed some parts (the addon command for this) but forgot the login. Thanks  for removing it.

**Comment by abayer** [comment]
/hold

As Hardy pointed out, I kinda overshot here. I’ll fix it up today, but holding it for the moment.

**Comment by abayer** [comment]
/hold cancel

Ok, updated, removing hold.
