### PR TITLE
fix: GC ProwJobs in gc_activities

### LINKED ISSUE #6094: gcactivities cronjob should also clean up prow jobs
Probably at least as aggressively as it cleans up `PipelineActivity`s, definitely not as aggressively as it cleans up `PipelineRun`s. Maybe we should be adding `prowJobName` to `PipelineActivity` labels, and whenever we're GCing a `PipelineActivity`, we GC its corresponding `ProwJob` as well? On prod, that'd still leave us with ~2500 or so `ProwJob`s floating around much of the time, but that's a lot better than "just grow forever" like we have now. There's probably a simpler way we could do it as well - just always deleting any `ProwJob` older than 3 days or something like that.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

We're already GCing `PipelineActivity` and `PipelineRun` directly,
which also results in the downstream CRDs
`Pipeline`/`Task`/`TaskRun`/`PipelineStructure` all getting GCed too,
but until now, we're not doing anything about `ProwJob`s, so they can
get out of control and cause performance and OOM issues on the various
Prow pods. So let's GC `ProwJob`s too.

The default is to keep a week of `ProwJob`s - even on prod, I haven't
seen issues caused by excesses of `ProwJob`s until it's been at least
two weeks of regular rates of creation, so a week seems fine.

#### Which issue this PR fixes

fixes #6094

### CODE REVIEW

File: pkg/cmd/gc/gc_activities.go [hunk 1]
```diff
@@ -267,6 +277,45 @@ func (o *GCActivitiesOptions) deletePipelineRun(pipelineRunInterface tektonclien
...
+	now := time.Now()
+
+	for _, pj := range pjList.Items {
+		completionTime := pj.Status.CompletionTime
+		if completionTime != nil && completionTime.Add(o.ProwJobAgeLimit).Before(now) {
+			err = o.deleteProwJob(pjInterface, &pj)
+			if err != nil {
+				return err
+			}
+			continue
```
Comment (ccojocar) [inline pkg/cmd/gc/gc_activities.go]: nit: this `continue` statement is not required

File: pkg/cmd/gc/gc_activities.go [hunk 2]
```diff
@@ -267,6 +277,45 @@ func (o *GCActivitiesOptions) deletePipelineRun(pipelineRunInterface tektonclien
...
+		return nil
+	}
+
+	now := time.Now()
+
+	for _, pj := range pjList.Items {
+		completionTime := pj.Status.CompletionTime
+		if completionTime != nil && completionTime.Add(o.ProwJobAgeLimit).Before(now) {
+			err = o.deleteProwJob(pjInterface, &pj)
+			if err != nil {
```
Comment (ccojocar) [inline pkg/cmd/gc/gc_activities.go]: It would be nice to wrap these errors with some context.

**Comment by abayer** [comment]
@ccojocar - updated!
