### PR TITLE
bug(delete team): Clear cached clients & namespaces when switching namespaces

### LINKED ISSUE #2451: `jx delete team cheese` trashes the admin namespace
### Summary 

when deleting a team via `jx delete team <teamname>` the command completes but it also trashes the team in the admin namespace.  (the admin namespace is still present but a lot of controllers are now gone),

### Steps to reproduce the behavior

```
jx install
jx create team foo
<wait>
jx delete team foo
```

### Jx version

The output of `jx version` is:

not sure as my cluster was trashed... it was create a day before this so probably platform was 3019

```
jx version
NAME               VERSION
jx                 [32m1.3.637[0m
jenkins x platform [32m0.0.3027[0m
Kubernetes cluster [32mv1.9.7-gke.11[0m
kubectl            [32mv1.10.3[0m
helm client        [32mv2.11.0+g2e55dbe[0m
helm server        [32mv2.11.0+g2e55dbe[0m
git                [32mgit version 2.16.2.windows.1[0m
Operating System   [32mWindows 10 Pro 1803 build 17134[0m
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

GKE  `jx create terraform`

### Operating system / Environment

OS X / Windows / N/A

### Expected behavior

unrelated teams from that being deleted are unaffected

### Actual behavior

the admin namespace is affected.

### PR DESCRIPTION
**Pull request by markawm**
JXClient, KubeClient, and namespaces are all cached for efficiency, but after switching namespaces these values might
be wrong. Clear them all out when changing namespaces, which will force the various setup methods in CommonOptions
(e.g. JXClient()) to create new ones, and recalculate dev namespaces etc.

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #2451

### CODE REVIEW

File: pkg/jx/cmd/delete_team.go [hunk 1]
```diff
@@ -195,4 +194,11 @@ func (o *DeleteTeamOptions) changeNamespace(ns string) {
 	if err != nil {
 		log.Warnf("Failed to set context to namespace %s: %s", ns, err)
 	}
+
+	//Reset all the cached clients & namespace values when switching so that they can be properly recalculated for
+	//the new namespace.
```
Comment (ccojocar) [inline pkg/jx/cmd/delete_team.go]: I would move this in a helper method in `common.go` such that it can be reused.

Comment (markawm) [reply pkg/jx/cmd/delete_team.go]: Yeah, I wondered the same after pushing it - moved into CommonOptions so that everyone can switch NS easily.
