### PR TITLE
fix(secreturl): Cluster names can have dots in them

### LINKED ISSUE #5848: `cannot parse k8s as path:key` when bootstrapping cluster using `jx boot`
### Summary 
- I am trying to get jenkins x et al installed on my already provisioned kops stage cluster.

- At the `STEP: install-jenkins-x` I get an error that boils down to: `cannot parse k8s as path:key`

- I see that this error message comes from the file: `./pkg/secreturl/helpers.go`

- It is trying to parse a URL from what I gather. The domain I provide to the ingress is: `stage.<NAME>.<TLD>` where <NAME> is my company name and <TLD> is our top-level domain.

- The cluster name I provide is `k8s.stage.<NAME>.<TLD>`

- I believe it is trying to grab the admin password secret at this step and it is getting confused at my cluster name format possibly.

Any help would be greatly appreciated, thanks! I have provided my redacted config and error message below.

### Steps to reproduce the behavior
Run `jx boot`
### Expected behavior
It works.

### Actual behavior
It doesn't work. 

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.881
Kubernetes cluster v1.13.10
kubectl            v1.14.6
helm client        v2.14.3+g0e7f3b6
helm server        v2.14.3+g0e7f3b6
git                2.19.0
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type
- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
Using a Kops created cluster in AWS.

### Operating system / Environment
MacOS Mojave 10.14.4 (18E226)

### jx-requirements.yml
```
autoUpdate:
  enabled: false
  schedule: ""
bootConfigURL: https://github.com/<NAME>/environment-k8s.stage.<NAME>.<TLD>-dev
cluster:
  azure: {}
  clusterName: k8s.stage.<NAME>.<TLD>
  environmentGitOwner: <NAME>
  gitKind: github
  gitName: github
  gitServer: https://github.com
  namespace: jx
  project: cluster-stage
  provider: kubernetes
environments:
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: dev
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: staging
- ingress:
    domain: ""
    externalDNS: false
    namespaceSubDomain: ""
    tls:
      email: ""
      enabled: false
      production: false
  key: production
gitops: true
ingress:
  domain: stage.<NAME>.<TLD>
  externalDNS: true
  namespaceSubDomain: -jx.
  tls:
    email: security@<NAME>.<TLD>
    enabled: true
    production: false
kaniko: true
secretStorage: local
storage:
  backup:
    enabled: false
    url: ""
  logs:
    enabled: false
    url: ""
  reports:
    enabled: false
    url: ""
  repository:
    enabled: false
    url: ""
vault: {}
velero: {}
versionStream:
  ref: master
  url: https://github.com/jenkins-x/jenkins-x-versions.git
webhook: prow

```

### `jx boot` output

```
STEP: install-jenkins-x command: /bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders in dir: env

Modified file /Users/ryan/dev/<NAME>/environment-k8s.stage.<NAME>.<TLD>-dev/env/Chart.yaml to set the chart to version 1
Copying the helm source directory /Users/ryan/dev/<NAME>/environment-k8s.stage.<NAME>.<TLD>-dev/env to a temporary location for building and applying /var/folders/4m/02dsqt8x6zjc_899syc0h2lc0000gn/T/jx-helm-apply-324529707/env
Applying helm chart at /var/folders/4m/02dsqt8x6zjc_899syc0h2lc0000gn/T/jx-helm-apply-324529707/env as release name jenkins-x to namespace jx
verifying the helm requirements versions in dir: . using version stream URL: https://github.com/jenkins-x/jenkins-x-versions.git and git ref: master
error: generating values.yaml for tree from /var/folders/4m/02dsqt8x6zjc_899syc0h2lc0000gn/T/jx-helm-apply-324529707/env: failed to convert secret URLs in parameters file /var/folders/4m/02dsqt8x6zjc_899syc0h2lc0000gn/T/jx-helm-apply-324529707/env/parameters.yaml: replacing vault paths in adminUser:
  password: local:k8s.stage.<NAME>.<TLD>/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: info@<NAME>.<TLD>
  token: local:k8s.stage.<NAME>.<TLD>/pipelineUser:token
  username: <NAME> Devs
prow:
  hmacToken: local:k8s.stage.<NAME>.<TLD>/prow:hmacToken
: cannot parse k8s as path:key
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step helm apply --boot --remote --name jenkins-x --provider-values-dir ../kubeProviders' command in directory 'env', output: ''
```

### PR DESCRIPTION
**Pull request by polothy**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

If a cluster name has dots in it (EG: `test.kops.k8s.local`) then `jx boot` fails to convert secrets:

```
failed to convert secret URLs in parameters file /path/jx-boot/environment-test.kops.k8s.local-dev/env/parameters.yaml: replacing vault paths in
adminUser:
  password: local:test.kops.k8s.local/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jx-bot-test@example.com
  token: local:test.kops.k8s.local/pipelineUser:token
  username: test-user
prow:
  hmacToken: local:test.kops.k8s.local/prow:hmacToken
: cannot parse "test" as path:key
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step create values --name parameters' command in directory 'env', output: ''
``` 

#### Special notes for the reviewer(s)

None

#### Which issue this PR fixes

fixes #5848

### CODE REVIEW

File: pkg/vault/fake/client.go [hunk 1]
```diff
@@ -16,7 +16,7 @@ const (
 	yamlDataKey = "yaml"
 )
 
-var vaultURIRegex = regexp.MustCompile(`vault:[-_\w\/:]*`)
+var vaultURIRegex = regexp.MustCompile(`vault:[-_.\w\/:]*`)
```
Comment (polothy) [inline pkg/vault/fake/client.go]: Just note to code reviewer: this regex is not like the others.

File: pkg/vault/vault_client.go [hunk 2]
```diff
@@ -16,7 +16,7 @@ const (
 	yamlDataKey = "yaml"
 )
 
-var vaultURIRegex = regexp.MustCompile(`:[\s"]*vault:[-_\w\/:]*`)
+var vaultURIRegex = regexp.MustCompile(`:[\s"]*vault:[-_.\w\/:]*`)
```
Comment (hferentschik) [inline pkg/vault/vault_client.go]: @ccojocar, are you aware of any reason not to allow '.' in the regexp?

Comment (ccojocar) [reply pkg/vault/vault_client.go]: You need to check if vault allows this in its secret path. I think it does according with this https://groups.google.com/forum/#!topic/vault-tool/_E2N0SLryv8

Comment (hferentschik) [reply pkg/vault/vault_client.go]: thanks @ccojocar. That seems ok then to me.
