### PR TITLE
fix(import): Fix application reimport

### LINKED ISSUE #7325: `jx import` fails to import project previously created by jx
### Summary 
Importing a project that was previously created (by another old inactive cluster) fails since jx tries to recreate the chart directories which already exist.
I'd expect jx to be able to reimport its own projects.
While it works when using the `--no-draft` option which disables draft (the technology used to prepare a project with a build pack) this is not very clear or rather the option's name is misleading.

### Steps to reproduce the behavior
1) Create a quickstart (e.g. golang-http) project with one cluster
2) Import the quickstart project into another cluster

### Expected behavior
The import should always succeed no matter if it's a project created by jx or not.

### Actual behavior
The import fails:
```
$ jx import --url https://github.com/max-test-org/jx-go-quickstart
? Do you wish to use mgoltzsche as the Git user name: Yes
Cloned Git repository from https://mgoltzsche:d1bac02785ef90b033c7273d599780a4571c49b3@github.com/max-test-org/jx-go-quickstart.git
trying to use draft pack: go
selected pack: /home/max/.jx/draft/packs/github.com/jenkins-x-buildpacks/jenkins-x-kubernetes/packs/go
WARNING: Failed to apply the build pack in /home/max/development/jx/jx-go-quickstart due to mkdir /home/max/development/jx/jx-go-quickstart/charts/preview: file exists
error: error renaming /home/max/development/jx/jx-go-quickstart/charts/golang to /home/max/development/jx/jx-go-quickstart/charts/jx-go-quickstart, failed to copy source dir /home/max/development/jx/jx-go-quickstart/charts/golang to /home/max/development/jx/jx-go-quickstart/charts/jx-go-quickstart: destination already exists
```

### Workaround
Use the `--no-draft` option with the `jx import` command.

### Jx version
The output of `jx version` is:
```
jx                 2.1.46
Kubernetes cluster v1.14.10-gke.36
kubectl            v1.16.8
helm client        2.16.5
git                2.17.1
Operating System   Ubuntu 18.04.4 LTS
```

### Kubernetes cluster
CJXD 9 on Kubernetes cluster v1.14.10-gke.36

### Operating system / Environment
Ubuntu 18.04

### PR DESCRIPTION
**Pull request by mgoltzsche**
Allows to reimport projects that have previously been
imported/created using Jenkins X by ignoring an already
existing chart directory.

Closes #7325

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
Skip copying chart dir from buildpack when the destination dir already exist and contains a `Chart.yaml`.

#### Which issue this PR fixes

fixes #7325

### CODE REVIEW

File: pkg/cmd/importcmd/import.go [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package importcmd
 
 import (
+	goerrors "errors"
```
Comment (mrageh) [inline pkg/cmd/importcmd/import.go:4]: Why do we call this `goerrors`, why not use the default name `errors`?

Comment (mgoltzsche) [reply pkg/cmd/importcmd/import.go:4]: because `github.com/pkg/errors` is also imported... hm, maybe I replace its occurrences with `errors` now that we updated to go 1.13...

Comment (mgoltzsche) [reply pkg/cmd/importcmd/import.go:4]: äh, no, can't do that quickly since callers might rely on them and `github.com/pkg/errors` v0.8.1 is not compatible with the new go `errors`...
Therefore I could try a) update the pkg/errors dependency to 0.9 which supports go 1.13 errors or b) continue to use pkg/errors only.
WDYT? @mrageh

Comment (mgoltzsche) [reply pkg/cmd/importcmd/import.go]: well i am not taking the risk for single line ;). I changed it to use `github.com/pkg/errors`.

**Comment by mgoltzsche** [comment]
Quickstart/import code still needs to be decomposed. However this is not part of this PR but postponed for now.
