### PR TITLE
fix: remove the "jx console" command from import message

### LINKED ISSUE #3831: serverless pipeline setups still show "jx console" as suggested action
### Summary 
After creating an application (quickstart) with a team in serverless, it still shows the option to open a console, but there won't be one, and it doesn't really make sense does it? 

`Open the Jenkins console via    jx console`

### Steps to reproduce the behavior
create a quickstart with a serverless team

### Expected behavior
should not show `jx console`
### Actual behavior
does show it. 

When you run it: 

```
 jx console
error: No Jenkins App services found in namespace jx with selector jenkins.io/kind=jenkins
Are you sure you installed a Jenkins App in this namespace?
Try jx add app jx-app-jenkins
```
### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.72
jenkins x platform 2.0.177
Kubernetes cluster v1.11.8-gke.6
kubectl            v1.12.2
helm client        Client: v2.12.1+g02a47c7
git                git version 2.20.1
Operating System   Mac OS X 10.14.4 build 18E226
```

### Jenkins type

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

I think is fine to remove the `jx console` command from import message. We can add maybe later a link to the UI.

#### Which issue this PR fixes

fixes #3831

### CODE REVIEW

File: pkg/jx/cmd/opts/import.go [hunk 1]
```diff
@@ -211,7 +211,6 @@ func (o *CommonOptions) LogImportedProject(isEnvironment bool, gitInfo *gits.Git
 	if !isEnvironment {
 		log.Infof("Watch pipeline activity via:    %s\n", util.ColorInfo(fmt.Sprintf("jx get activity -f %s -w", gitInfo.Name)))
 		log.Infof("Browse the pipeline log via:    %s\n", util.ColorInfo(fmt.Sprintf("jx get build logs %s", gitInfo.PipelinePath())))
-		log.Infof("Open the Jenkins console via    %s\n", util.ColorInfo("jx console"))
```
Comment (hferentschik) [inline pkg/jx/cmd/opts/import.go]: So we remove this message regardless of the install type? Works for me. 
 I wonder what should happen long term with `jx console` altogether. I think it should be removed.
