### PR TITLE
fix: Apply labels as part of pull req creation, not just after

### LINKED ISSUE #6210: Nil pointer error when creating a PR with no changes
See #6203 for an example - I'm creating a separate issue for just this part of it, since that issue's real problem is that `jx import` tries to add the imported repo to the dev env repo, but `jx delete application` doesn't remove it, so if you try to import something that's already been imported/deleted, things go weird. But the nil pointer error is a separate problem in `pull_request_op` that could get hit by any situation where a PR isn't actually created.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Analogous to #6244 - gets us away from the nil pointer issue and cuts down on API calls a bit.

#### Which issue this PR fixes

fixes #6210

### CODE REVIEW

File: pkg/gits/operations/pull_request_op.go [hunk 1]
```diff
@@ -92,9 +92,11 @@ func (o *PullRequestOperation) CreatePullRequest(kind string, update ChangeFiles
 		if err != nil {
 			return nil, errors.Wrapf(err, "failed to create PR for base %s and head branch %s from temp dir %s", o.Base, details.BranchName, dir)
 		}
-		err = gits.AddLabelsToPullRequest(result, labels)
-		if err != nil {
-			return nil, errors.Wrapf(err, "failed to add labels %+v to PR %s", labels, result.PullRequest.URL)
+		if result != nil {
```
Comment (hferentschik) [inline pkg/gits/operations/pull_request_op.go]: So what are we saying here? That `gits.PushRepoAndCreatePullRequest` might return nil and no error? Is there then not something semantically wrong in that function? In which cases do we get `nil` and no error?

Comment (ccojocar) [reply pkg/gits/operations/pull_request_op.go]: I think is this case inside of the function:
```
		changed, err := gitter.HasChanges(dir)
		if err != nil {
			return nil, errors.WithStack(err)
		}
		if !changed {
			log.Logger().Warnf("No changes made to the source code in %s. Code must be up to date!", dir)
			return nil, nil
		}
```

Maybe it  makes sense to explicitly check if there are any changes before calling the function and skip everything afterwords. The logic would look more clear to me. This doesn't look like an error case.

Comment (abayer) [reply pkg/gits/operations/pull_request_op.go]: @hferentschik We get `nil` and no error if there are no changes to create a PR with. And @ccojocar, which function do you mean?

Comment (ccojocar) [reply pkg/gits/operations/pull_request_op.go]: `changed, err := gitter.HasChanges(dir)`

Comment (abayer) [reply pkg/gits/operations/pull_request_op.go]: I'll tackle that in a followup - I'm gonna rework this like #6244 to apply the labels at creation time instead of immediately after to deal with the nil pointer specifically.

File: pkg/gits/operations/pull_request_op.go [hunk 2]
```diff
@@ -88,14 +88,11 @@ func (o *PullRequestOperation) CreatePullRequest(kind string, update ChangeFiles
 		filter := &gits.PullRequestFilter{
 			Labels: labels,
 		}
+		details.Labels = labels
```
Comment (hferentschik) [inline pkg/gits/operations/pull_request_op.go]: +1, that seems ways more sensible.

Any idea on why the labels were initially added in a separate call?  Seems to make no sense.

**Comment by hferentschik** [comment]
@abayer, there seems to be a legit issue with the integration tests:

```
=== Failed
=== FAIL: pkg/gits/operations TestCreatePullRequest (0.04s)
WARNING: Failed to retrieve team settings: failed to create the ** client: namespaces "**" not found - falling back to default settings...
    pull_request_op_test.go:93: 
        	Error Trace:	pull_request_op_test.go:93
        	Error:      	"Created Pull Request: https://fake.git/testowner/testrepo/pulls/1
        	            	" does not contain "Added label updatebot to Pull Request https://fake.git/testowner/testrepo/pulls/1"
        	Test:       	TestCreatePullRequest
        	Messages:   	Updatebot label should be added to the PR
=== FAIL: pkg/gits/operations TestCreatePullRequestWithMatrixUpdatePaths (0.03s)
WARNING: Failed to retrieve team settings: failed to create the ** client: namespaces "**" not found - falling back to default settings...
    pull_request_op_test.go:214: 
        	Error Trace:	pull_request_op_test.go:214
        	Error:      	"Created Pull Request: https://fake.git/testowner/testrepo/pulls/1
        	            	" does not contain "Added label updatebot to Pull Request https://fake.git/testowner/testrepo/pulls/1"
        	Test:       	TestCreatePullRequestWithMatrixUpdatePaths
        	Messages:   	Updatebot label should be added to the PR
```

**Comment by abayer** [comment]
@hferentschik Yup, definitely legit. I’ll try to look into it today.

**Comment by abayer** [comment]
So it wasn't an actual problem with the code, it's that the tests were looking for logging in something we're not using any more, so I changed them to instead verify that the labels were on the `PullRequestArguments`. Should be good now.
