### PR TITLE
fix: Verify pre install fails with incorrect kubectl or helm version on the path

### LINKED ISSUE #7169: jx step verify preinstall fails due to helm version
### Summary 

Running `jx step verify preinstall` fails with `FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2.` when helm 3 is on the path. JX now uses helm from ~/.jx/bin and should not fail in this case.

### PR DESCRIPTION
**Pull request by daveconde**
fixes #7169 

This PR installs helm and kubectl in to ~/.jx/bin as part of `jx step verify preinstall` it also forces ~/.jx/bin to the start of the path.

Signed-off-by: David Conde

### CODE REVIEW

File: pkg/cmd/step/verify/step_verify_preinstall.go [hunk 1]
```diff
@@ -172,6 +173,11 @@ func (o *StepVerifyPreInstallOptions) Run() error {
 	}
 	log.Logger().Info("\n")
 
+	err = o.installMissingDependencies()
```
Comment (hferentschik) [inline pkg/cmd/step/verify/step_verify_preinstall.go:176]: do we really want to install or just say they are not installed? I guess what bugs me is that this is supposed to be a _verify_, not an install step.

File: pkg/util/commands.go [hunk 2]
```diff
@@ -269,14 +269,17 @@ func (c *Command) run() (string, error) {
...
 	if mvnBinDir != "" {
 		answer += string(os.PathListSeparator) + mvnBinDir
 	}
 	for _, p := range paths {
-		answer += string(os.PathListSeparator) + p
+		if p != "" {
+			answer += string(os.PathListSeparator) + p
+		}
 	}
+	binDir, _ := JXBinLocation()
```
Comment (hferentschik) [inline pkg/util/commands.go:282]: maybe _jxBinDir_ to make it a bit cleaner in the final line where you put things together

Comment (hferentschik) [reply pkg/util/commands.go:282]: A test for this might not be bad either?

File: pkg/util/commands.go [hunk 3]
```diff
@@ -269,14 +269,17 @@ func (c *Command) run() (string, error) {
...
-	answer := path + string(os.PathListSeparator) + binDir
 	mvnBinDir, _ := MavenBinaryLocation()
+	answer := ""
 	if mvnBinDir != "" {
 		answer += string(os.PathListSeparator) + mvnBinDir
 	}
 	for _, p := range paths {
-		answer += string(os.PathListSeparator) + p
+		if p != "" {
+			answer += string(os.PathListSeparator) + p
```
Comment (hferentschik) [inline pkg/util/commands.go:279]: maybe assign this to something new like "customPaths" or "providedPath"? The last line of this function is quite confusing imo. It takes a while to understand what and how you put things together. WDYT?

File: pkg/util/commands.go [hunk 4]
```diff
@@ -269,14 +269,17 @@ func (c *Command) run() (string, error) {
...
+		}
 	}
+	binDir, _ := JXBinLocation()
+	answer = binDir + string(os.PathListSeparator) + path + answer
```
Comment (hferentschik) [inline pkg/util/commands.go:283]: I see, so the JX_HOME/bin was not added first, but after the main PATH. That is of course wrong.

File: pkg/util/commands.go [hunk 5]
```diff
@@ -269,14 +269,17 @@ func (c *Command) run() (string, error) {
 // PathWithBinary Sets the $PATH variable. Accepts an optional slice of strings containing paths to add to $PATH
```
Comment (hferentschik) [inline pkg/util/commands.go:269]: The godoc seems wrong. This function is not setting a PATH variable here.

File: pkg/cmd/step/verify/step_verify_preinstall.go (hunk 1 above)
Comment (daveconde) [reply pkg/cmd/step/verify/step_verify_preinstall.go:176]: I think the fact that they are an internal implementation detail for JX now that they are in ~/.jx/bin would make it ok to auto install. Is there a better location to do this you would suggest that would remove it out of the verify? Ideally longer terms we'd remove the need to call out to external binaries.

File: pkg/util/commands.go (hunk 3 above)
Comment (daveconde) [reply pkg/util/commands.go:279]: I'll make that a bit clearer to read and update the godoc

File: pkg/util/commands.go (hunk 2 above)
Comment (daveconde) [reply pkg/util/commands.go]: test is incoming, I've made the variables in here clearer

File: pkg/cmd/step/verify/step_verify_preinstall.go (hunk 1 above)
Comment (hferentschik) [reply pkg/cmd/step/verify/step_verify_preinstall.go:176]: The alternative is to fail with an error and let the user fix it. Given that we want to install into JX_HOME/bin it would not make much sense to just display `jx install dependencies`, so I guess it is the best we can do for now.
