### PR TITLE
fix: complete changelog on first release

### LINKED ISSUE #5646: first release does not generate a changelog or Release
as the `jx step changelog` bombs out early if it can't find a previous release tag

### PR DESCRIPTION
**Pull request by jstrachan**
fixes #5646

### CODE REVIEW

File: pkg/cmd/start/start_pipeline.go [hunk 1]
```diff
@@ -295,7 +295,9 @@ func (o *StartPipelineOptions) createProwJob(jobname string) error {
 	}
 	jobSpec.Type = prowjobv1.PostsubmitJob
 
-	//todo needs to change when we add support for multiple git providers with Prow
+	// TODO prow only supports github.com
+	// if you want to use anytthng but github.com you should use
```
Comment (romainverduci) [inline pkg/cmd/start/start_pipeline.go]:
```suggestion
	// if you want to use anything but github.com you should use
```
