### PR TITLE
fix: jx upgrade cli not working on windows

### LINKED ISSUE #969: Error at `jx upgrade cli` command on Windows
It looks like Windows [releases](https://github.com/jenkins-x/jx/releases) are packaged differently in .zip format instead of .tar. 

$ jx upgrade cli                                                                                                                                      
```
Downloading https://github.com/jenkins-x/jx/releases/download/v1.2.100/jx-windows-amd64.tar.gz to C:\Users\Igor\.jx\bin\jx.tgz...                     
Downloaded C:\Users\Igor\.jx\bin\jx.tgz                                                                                                               
panic: gzip: invalid header                                                                                                                           
        panic: runtime error: invalid memory address or nil pointer dereference                                                                       
[signal 0xc0000005 code=0x0 addr=0x70 pc=0x5ffe79]                                                                                                    
                                                                                                                                                      
goroutine 1 [running]:                                                                                                                                
compress/gzip.(*Reader).Close(0x0, 0x27e88e0, 0xc0420405c0)                                                                                           
        /usr/local/go/src/compress/gzip/gunzip.go:292 +0x29                                                                                           
panic(0x18ccc60, 0xc0420405c0)                                                                                                                        
        /usr/local/go/src/runtime/panic.go:491 +0x291                                                                                                 
github.com/jenkins-x/jx/pkg/util.UnTargz(0xc042414780, 0x1c, 0xc042414040, 0x15, 0xc0426e3830, 0x2, 0x2, 0x0, 0x0)                                    
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/util/downloads.go:94 +0x5dc                                                                  
github.com/jenkins-x/jx/pkg/jx/cmd.(*CommonOptions).installJx(0xc042103080, 0x1, 0xc04240c279, 0x7, 0x0, 0x0)                                         
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/common_install.go:500 +0x502                                                          
github.com/jenkins-x/jx/pkg/jx/cmd.(*UpgradeCLIOptions).Run(0xc042103080, 0xc0427d1c50, 0x0)                                                          
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/upgrade_cli.go:85 +0x7d0                                                              
github.com/jenkins-x/jx/pkg/jx/cmd.NewCmdUpgradeCLI.func1(0xc0420fea00, 0x294f110, 0x0, 0x0)                                                          
        /home/jenkins/go/src/github.com/jenkins-x/jx/pkg/jx/cmd/upgrade_cli.go:53 +0x7c                                                               
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).execute(0xc0420fea00, 0x294f110, 0x0, 0x0, 0xc0420fea00, 0x294f110)                  
        /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:766 +0x2c8                                              
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc042138c80, 0xc0422c3b80, 0xc042635680, 0xc04241e000)                     
        /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:852 +0x33b                                              
github.com/jenkins-x/jx/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042138c80, 0xc04274ad40, 0x27f2ae0)                                       
        /home/jenkins/go/src/github.com/jenkins-x/jx/vendor/github.com/spf13/cobra/command.go:800 +0x32                                               
github.com/jenkins-x/jx/cmd/jx/app.Run(0xc04202c000, 0x172a3d0)                                                                                       
        /home/jenkins/go/src/github.com/jenkins-x/jx/cmd/jx/app/jx.go:18 +0x97                                                                        
main.main()                                                                                                                                           
```

$ jx version                                                                                                                                     
```
NAME               VERSION                                                                                                                       
jx                 1.2.97                                                                                                                        
jenkins x platform 0.0.1175                                                                                                                      
kubernetes cluster v1.10.0                                                                                                                       
kubectl            v1.10.3                                                                                                                       
helm client        v2.9.1+g20adb27                                                                                                               
helm server        v2.9.1+g20adb27                                                                                                               
git                git version 2.9.0.windows.1                                                                                                   
```

### PR DESCRIPTION
**Pull request by jtnord**
fixes #969 the issue with attempting to upgrade jx on windows using `jx upgrade cli`.

This also has some improvements for non windows platforms as a bonus!

### CODE REVIEW

File: pkg/util/dirs.go [hunk 1]
```diff
@@ -125,17 +125,29 @@ func JXBinLocation() (string, error) {
 
 // JXBinaryLocation Returns the path to the currently installed JX binary.
 func JXBinaryLocation(commandInterface Commander) (string, error) {
```
Comment (jtnord) [inline pkg/util/dirs.go]: so this no longer uses the Commander, and the tests seem to serve no purpose so can be simplified and removed.
that does leave me wondering how best to test this however.  @i0n do you have any ideas?

File: pkg/util/dirs.go [hunk 2]
```diff
@@ -125,17 +125,29 @@ func JXBinLocation() (string, error) {
...
-	jxBinaryFromEnv, found := os.LookupEnv("JX_BINARY")
-	if found {
-		return strings.TrimSuffix(jxBinaryFromEnv, "/jx"), nil
+	jxProcessBinary, err := os.Executable()
```
Comment (ccojocar) [inline pkg/util/dirs.go]: It would be nice a test for this logic.

File: pkg/jx/cmd/common_install.go [hunk 3]
```diff
@@ -505,10 +505,15 @@ func (o *CommonOptions) installOc() error {
 // get the latest version from kubernetes, parse it and return it
 func (o *CommonOptions) getLatestVersionFromKubernetesReleaseUrl() (sem semver.Version, err error) {
 	response, err := http.Get(stableKubeCtlVersionURL)
```
[the remark this answers is not in the document]
Comment (ccojocar) [reply pkg/jx/cmd/common_install.go]: Potentially we can tests this with `httptest` and simulate when the download address is down. It will most likely block for a while, but the TCP timeout on OS level will kick in and it will cut the connection at some point.

[the remark this answers is not in the document]
Comment (jtnord) [reply pkg/jx/cmd/common_install.go]: I think that is worth a followup ticket and change, this is currently getting large-ish as is.

File: pkg/util/dirs.go (hunk 2 above)
Comment (jtnord) [reply pkg/util/dirs.go]: added a test

**Comment by jtnord** [comment]
@ccojocar I feel this is ready for a re-review.

File: pkg/jx/cmd/common_install.go [hunk 4]
```diff
@@ -1138,24 +1150,53 @@ func (o *CommonOptions) installJx(upgrade bool, version string) error {
...
-		log.Infof("Skipping removal of old jx binary: %s\n", err)
-	}
-	// Copy over the new binary
-	err = os.Rename(jxHome+"/jx", binDir+"/jx")
-	if err != nil {
-		return err
+
+
+	if runtime.GOOS != "windows" {
+		err = util.UnTargz(tmpArchiveFile, jxHome, []string{binary, fileName})
```
Comment (jtnord) [inline pkg/jx/cmd/common_install.go]: this was existing code - it looks wrong to me as it is asking to unpack "binary" and filename" only they will either be the same or only binary will be present as far as I understand this
