### PR TITLE
fix: add compatibility sh

### LINKED ISSUE #7035: jx boot fails on Windows
### Summary
When running jx boot on Windows it tries to execute /bin/sh in step validate-git. This obviously fails.

### Steps to reproduce the behavior
execute jx boot on Windows in powershell

### Expected behavior
set up jenkins x

### Actual behavior
```
Booting Jenkins X
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found
WARNING: failed to load ConfigMap jenkins-x-docker-registry in namespace jx: failed to get configmap jenkins-x-docker-registry in namespace jx, configmaps "jenkins-x-docker-registry" not found

STEP: validate-git command: /bin/sh -c jx step git validate in dir: E:\dev\environment-test-dev\workspace\source\workspace\source\env

error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c jx step git validate' command in directory 'workspace\source\workspace\source\env', output: ''
```
### Jx version

The output of `jx version` is:

```
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
NAME               VERSION
jx                 2.0.1274
Kubernetes cluster v1.14.10-gke.27
kubectl            v1.15.5
git                2.19.0.windows.1
Operating System   Windows 10 Pro 1809 build 17763
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster
GKE cluster tried with jx create gke --skip-install and manual creation

### Operating system / Environment
Windows 10/Powershell

### PR DESCRIPTION
**Pull request by nodece**
Signed-off-by: Zixuan Liu <nodeces@gmail.com>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

Due to Windows file struct, We cannot found `/bin/sh` in Windows.

Same way in #7096.  

#### Which issue this PR fixes

fixes #7035, #7156

### CODE REVIEW

File: pkg/util/shell.go [hunk 1]
```diff
@@ -0,0 +1,14 @@
+package util
+
+import "runtime"
+
+// GetSh returns the default sh path.
```
Comment (hferentschik) [inline pkg/util/shell.go:5]: +1 👍
