### PR TITLE
fix: Don't use pointers for getPipelineRunsForActivity return

### LINKED ISSUE #5652: Long-term storage of logs fails with multiple existing PipelineRuns of the same owner/repo/branch
This is due to me being dumb with go pointers.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

I'm not good with pointers, basically. If there are multiple runs for an owner/repo/branch, without this, the pointers returned by `getPipelineRunsForActivity` end up pointing to the last run we looked at, not the one that actually matched. Sigh. I modified an existing test to fail without this fix.

#### Special notes for the reviewer(s)

/assign @hferentschik 

#### Which issue this PR fixes

fixes #5652

### CODE REVIEW

File: pkg/logs/tekton_logging.go [hunk 1]
```diff
@@ -168,7 +168,7 @@ func findLegacyPipelineRunBuildNumber(pipelineRun *tektonapis.PipelineRun) strin
 	return buildNumber
 }
 
-func getPipelineRunsForActivity(pa *v1.PipelineActivity, tektonClient tektonclient.Interface) (map[string]*tektonapis.PipelineRun, error) {
+func getPipelineRunsForActivity(pa *v1.PipelineActivity, tektonClient tektonclient.Interface) (map[string]tektonapis.PipelineRun, error) {
```
Comment (hferentschik) [inline pkg/logs/tekton_logging.go]: by value is better anyways ;-)
