### PR TITLE
fix: Sleep five seconds after GitHub repo creation

### LINKED ISSUE #7129: Sporadic race condition on new GitHub repo creation and initial push to master
In our BDD tests, we've long seen errors pushing to a newly created GitHub repository very rarely, but in the last week, it's become much more frequent. The repo is created properly, but seems to not be ready to be pushed to quite as fast as we try to push to it.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This should prevent errors caused by GitHub not yet actually having the git repo proper ready and exposed.

#### Which issue this PR fixes

fixes #7129

### CODE REVIEW

File: pkg/gits/github.go [hunk 1]
```diff
@@ -343,6 +343,8 @@ func (p *GitHubProvider) CreateRepository(owner string, name string, private boo
 		}
 		return nil, errors.New(msg)
 	}
+	// Sleep 5 seconds to ensure repository exists enough to be pushed to.
+	time.Sleep(5 * time.Second)
```
Comment (hferentschik) [inline pkg/gits/github.go:347]: hmmm, for what it's worth, imo sleeping is just a crutch. I'd try to do an active poll loop in some form.
