### PR TITLE
fix: lock versions stream to tag

### LINKED ISSUE #5087: Use branch for version stream but resolve to tag if possible
### Summary 

Previously we used a branch to reference a version stream. We partially switched to GitHub releases but this is problematic (as releases aren't really a stream but a series of unrelated fixed points) and also prone to breakage (as it requires us to create a release).

Instead we will use the branch as a stream but try to resolve to a tag using `git describe` if possible and if not reference the SHA.

### PR DESCRIPTION
**Pull request by pmuir**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Special notes for the reviewer(s)
No tests atm, need to investigate if I can add some

#### Which issue this PR fixes

Fixes #5087

### CODE REVIEW

**Comment by pmuir** [comment]
It's probably better to merge this and then add tests for the whole of the version stream clone stuff as a separate issue I think - as they are missing totally.

**Comment by pmuir** [comment]
Actually on second thoughts I would really like us to have some tests for some of the versions stream, so I'm going to try to add those.

**Comment by ccojocar** [comment]
@pmuir This needs to be rebased. Thanks

**Comment by abayer** [comment]
Test failure looks legit:
```
=== FAIL: pkg/cmd/step/verify TestStepVerifyPreInstallNoKanikoLazyCreate (0.02s)
no need to reconnect to cluster
Deleting and cloning the Jenkins X versions repo
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with revision v1.0.0 to /tmp/**-test-TestStepVerifyPreInstallNoKanikoLazyCreate789345149/jenkins-x-versions
Using namespace '**' from context named '' on server ''.
    step_verify_preinstall_integration_test.go:87: 
        	Error Trace:	step_verify_preinstall_integration_test.go:87
        	Error:      	Received unexpected error:
        	            	failed to run 'git fetch origin v1.0.0' command in directory '/tmp/**-test-TestStepVerifyPreInstallNoKanikoLazyCreate789345149/jenkins-x-versions', output: 'fatal: not a git repository (or any of the parent directories): .git'
        	            	failed to git fetch origin v1.0.0 for repo: https://github.com/jenkins-x/jenkins-x-versions.git in dir /tmp/**-test-TestStepVerifyPreInstallNoKanikoLazyCreate789345149/jenkins-x-versions
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.clone
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:203
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.deleteAndReClone
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:173
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.cloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:156
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.CloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:29
        	            	github.com/jenkins-x/**/pkg/cmd/opts.(*CommonOptions).CloneJXVersionsRepo
        	            		/workspace/source/pkg/cmd/opts/version.go:150
        	            	github.com/jenkins-x/**/pkg/cmd/step/verify.(*StepVerifyPreInstallOptions).gatherRequirements
        	            		/workspace/source/pkg/cmd/step/verify/step_verify_preinstall.go:553
        	            	github.com/jenkins-x/**/pkg/cmd/step/verify.(*StepVerifyPreInstallOptions).Run
        	            		/workspace/source/pkg/cmd/step/verify/step_verify_preinstall.go:89
        	            	github.com/jenkins-x/**/pkg/cmd/step/verify_test.TestStepVerifyPreInstallNoKanikoLazyCreate
        	            		/workspace/source/pkg/cmd/step/verify/step_verify_preinstall_integration_test.go:86
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.cloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:158
        	            	github.com/jenkins-x/**/pkg/versionstream/versionstreamrepo.CloneJXVersionsRepo
        	            		/workspace/source/pkg/versionstream/versionstreamrepo/gitrepo.go:29
        	            	github.com/jenkins-x/**/pkg/cmd/opts.(*CommonOptions).CloneJXVersionsRepo
        	            		/workspace/source/pkg/cmd/opts/version.go:150
```
I'll work on it.

**Comment by abayer** [comment]
Ah-ha, it's the `git fetch` not working 'cos the tests are using `MockGitter`, so not actually doing anything.

**Comment by abayer** [comment]
Changing that to use `gitter.FetchBranch(wkrDir, "origin", versionReference)` gets us a new error:
```
--- FAIL: TestStepVerifyPreInstallNoKanikoLazyCreate (3.69s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5b4c7f6]

goroutine 11 [running]:
testing.tRunner.func1(0xc0001f3600)
	/usr/local/Cellar/go/1.12.4/libexec/src/testing/testing.go:830 +0x392
panic(0x67c6f40, 0x99cf750)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
gopkg.in/src-d/go-git%2ev4.(*Repository).Remote(0x0, 0x6d2a999, 0x6, 0x33, 0x0, 0x0)
	/Users/abayer/go/pkg/mod/gopkg.in/src-d/go-git.v4@v4.5.0/repository.go:371 +0x26
github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo.cloneJXVersionsRepo(0x6db6a19, 0x33, 0x0, 0x0, 0xc0006226a0, 0x78d8780, 0xc0000f2420, 0xc000270001, 0x0, 0x0, ...)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo/gitrepo.go:76 +0x6d9
github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo.CloneJXVersionsRepo(0x0, 0x0, 0x0, 0x0, 0xc0006226a0, 0x78d8780, 0xc0000f2420, 0x1, 0x0, 0x0, ...)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo/gitrepo.go:29 +0xf4
github.com/jenkins-x/jx/pkg/cmd/opts.(*CommonOptions).CloneJXVersionsRepo(0xc0002a8300, 0x0, 0x0, 0x0, 0x0, 0x4, 0xc00027f9a0, 0x1, 0x1, 0xc00043c460, ...)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/cmd/opts/version.go:150 +0x127
github.com/jenkins-x/jx/pkg/cmd/opts.(*CommonOptions).CreateVersionResolver(0xc0002a8300, 0x0, 0x0, 0x0, 0x0, 0x2, 0x2, 0xc00031c240)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/cmd/opts/version.go:18 +0x63
github.com/jenkins-x/jx/pkg/cmd/step/verify.(*StepVerifyPackagesOptions).Run(0xc001775e60, 0xc0006d8b70, 0x0)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/cmd/step/verify/step_verify_packages.go:99 +0x3f0
github.com/jenkins-x/jx/pkg/cmd/step/verify.(*StepVerifyPreInstallOptions).Run(0xc00068e900, 0x6e69390, 0xc0001f3600)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/cmd/step/verify/step_verify_preinstall.go:163 +0x78e
github.com/jenkins-x/jx/pkg/cmd/step/verify_test.TestStepVerifyPreInstallNoKanikoLazyCreate(0xc0001f3600)
	/Users/abayer/go/src/github.com/jenkins-x/jx/pkg/cmd/step/verify/step_verify_preinstall_integration_test.go:86 +0x330
testing.tRunner(0xc0001f3600, 0x6e69338)
	/usr/local/Cellar/go/1.12.4/libexec/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.12.4/libexec/src/testing/testing.go:916 +0x35a
FAIL	github.com/jenkins-x/jx/pkg/cmd/step/verify	3.809s
```

So something else that doesn't work with `MockGitter`...

**Comment by abayer** [comment]
@pmuir - I've changed `step_verify_preinstall_integration_test` to use `GitCLI` rather than `MockGitter` (with some requisite changes to the tests to always use a temporary `JX_HOME`).

**Comment by rawlingsj** [comment]
is this PR ready to go?

**Comment by wbrefvem** [comment]
@rawlingsj Should be ready to go, pending CI tasks. I'm off tomorrow but will check in first thing to see if anything came up.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+)
+
+const (
+	RepoURL    = "https://github.com/jenkins-x/jenkins-x-versions"
+	VersionRef = "v1.0.90"
+	BranchRef  = "master"
+	HEAD       = "HEAD"
+)
+
+func TestCloneJXVersionsRepoWithATag(t *testing.T) {
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: We should also test:

* Different URL than the default
* A URL and ref set in the team settings
* Not passing in a URL at all (to validate the default)

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+		true,
+		false,
+		nil,
+		nil,
+		nil,
+	)
+	assert.NoError(t, err)
+	assert.NotNil(t, dir)
+	assert.NotNil(t, versionRef)
+	assert.Equal(t, VersionRef, versionRef)
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: For these tests we need to validate that the correct files were checked out into the directory as well

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+	"github.com/jenkins-x/jx/pkg/gits"
+	"github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo"
+	"github.com/stretchr/testify/assert"
+)
+
+const (
+	RepoURL    = "https://github.com/jenkins-x/jenkins-x-versions"
+	VersionRef = "v1.0.90"
+	BranchRef  = "master"
+	HEAD       = "HEAD"
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: This is probably not the most realistic SHA to checkout, it's would be better to validate a specific SHA. Also I'm worried that the moment that we advance the HEAD then this test will break.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+import (
+	"testing"
+
+	"github.com/jenkins-x/jx/pkg/gits"
+	"github.com/jenkins-x/jx/pkg/versionstream/versionstreamrepo"
+	"github.com/stretchr/testify/assert"
+)
+
+const (
+	RepoURL    = "https://github.com/jenkins-x/jenkins-x-versions"
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: I would prefer to see these tests executed against something other than the real versions repo, as I worry that this approach makes them quite fragile. We normally use `test_data` to validate these sorts of methods, which I think will be a more robust approach and what we should do here. This will require you to make a git repo of that test data to start with.

**Comment by pmuir** [comment]
Left some feedback that needs adressing before merge @wbrefvem

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go (hunk 3 above)
Comment (wbrefvem) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: It won't break as long we're not asserting that it resolves to a specific tag. If we need to be able to do that, then I agree it makes more sense to use a specific commit.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go (hunk 2 above)
Comment (wbrefvem) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: I'm not sure I know what that means. You mean validate that we're checked out to the correct ref?

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go (hunk 1 above)
Comment (wbrefvem) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: Got it, will do.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go (hunk 4 above)
Comment (wbrefvem) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: Will do.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go (hunk 2 above)
Comment (pmuir) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: Exactly.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 5]
```diff
@@ -0,0 +1,157 @@
...
+	tag, _, err := gitter.Describe(dir, false, VersionRef, "")
+
+	assert.NoError(t, err)
+	assert.NotNil(t, dir)
+	assert.NotNil(t, versionRef)
+	assert.Equal(t, tag, versionRef)
+}
+
+func initializeTempGitRepo(gitter gits.Gitter) (string, error) {
+	dir, err := ioutil.TempDir("", "")
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: You need to manually clean up temp dirs you've created.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+		true,
+		false,
+		nil,
+		nil,
+		nil,
+	)
+	assert.NoError(t, err)
+	assert.NotNil(t, dir)
+	assert.NotNil(t, versionRef)
+	assert.Equal(t, VersionRef, versionRef)
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: As discussed we need to validate that the correct contents is checked out - is it definitely checking out whats in the tag, branch, sha.

File: pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+}
+
+func TestCloneJXVersionsRepoWithACommit(t *testing.T) {
+	gitter := gits.NewGitCLI()
+	gitDir, err := initializeTempGitRepo(gitter)
+	assert.NoError(t, err)
+	dir, versionRef, err := versionstreamrepo.CloneJXVersionsRepo(
+		gitDir,
+		HEAD, // We can't know a commit SHA in advance, so this instead of dereferencing it through rev-parse jiggery-pokery
```
Comment (pmuir) [inline pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: This is not really a useful test. It needs to test the real world scenario of a SHA.

Comment (wbrefvem) [reply pkg/versionstream/versionstreamrepo/gitrepo_integration_test.go]: Since we’re not initializing the repo ahead of time, the only way to get the expected SHA would be to do something like `git rev-parse HEAD` or equivalent. So using a SHA is logically equivalent to using HEAD, which just just a SHA with a few layers of indirection.

**Comment by wbrefvem** [comment]
@abayer I don't quite grok why the Tekton e2e tests failed. Any thoughts?

**Comment by abayer** [comment]
The [`boot-vault` failure](https://dashboard-jx.jenkins-x.live/teams/jx/projects/jenkins-x/jx/PR-5110/80) smells like what #5823 fixes, I thought? I'm gonna retry it.
