### PR TITLE
fix: override env vars from build pack if passed in

### LINKED ISSUE #6313: create effective pipeline fails if passing in DOCKER_REGISTRY
if we pass in the env var DOCKER_REGISTRY to creating the effective pipeline we've seen failures where the pod gets created with an env var of the form:

```yaml
    - name: DOCKER_REGISTRY
      value: gcr.io
      valueFrom:
        configMapKeyRef:
          key: docker.registry
          name: jenkins-x-docker-registry
```

which is invalid; either `value` or `valueFrom` should be used.

It looks like this is coming from logic of taking the `DOCKER_REGISTRY` from the pod templates and not detecting its being passed in to the meta pipeline client as a custom environment variable so should be discarded from the build pack. i.e. it should just generate this...

```yaml
    - name: DOCKER_REGISTRY
      value: gcr.io
```

### PR DESCRIPTION
**Pull request by jstrachan**
if we pass in custom env vars when creating an effective pipeline we should override any inherited env vars of the same name from the build pack to avoid creating invalid combined env var definitions in the pods which tekton + k8s cannot instantiate

fixes #6313

Signed-off-by: James Strachan <james.strachan@gmail.com>

### CODE REVIEW

File: pkg/cmd/step/syntax/step_syntax_effective.go [hunk 1]
```diff
@@ -448,6 +448,14 @@ func (o *StepSyntaxEffectiveOptions) createPipelineForKind(kind string, lifecycl
 		return nil, errors.Wrapf(validateErr, "validation failed for Pipeline")
 	}
 
+	// lets override any container options env vars from any custom injected env vars from the metapipeline client
```
Comment (abayer) [inline pkg/cmd/step/syntax/step_syntax_effective.go]: I'd rather either move `scopedEnv` out of `pkg/tekton/syntax/pipeline.go` or just make it publicly accessible, rather than having similarish behavior here.

Comment (jstrachan) [reply pkg/cmd/step/syntax/step_syntax_effective.go]: sorted - just need to make sure I can get all the tests passing with the reordered env vars
