### PR TITLE
fix(pipeline): Use standard version stream cloning logic in metapipeline

### LINKED ISSUE #5075: Installing CJXD with an existing jenkinx-x-versions repo in jenkins home doesn't override it with the correct one
### Summary 
When executing `jx boot` using the CJXD Release 1 binary while having an existing `jenkins-x-versions` repository in `.jx` results in boot using the existing repository without checking if it's a CJXD repository.

I had this happening when creating a brand new CJXD cluster without deleting `.jx`, resulting in CJXD using the versions stream master branch of `jenkins-x-versions` instead of `cloudbees-jenkins-x-versions`.

I found out because metapipelines were enabled by default. 

### Steps to reproduce the behavior

Create a cluster using `jx boot` with the `oss` profile enabled, it will download `jenkins-x-versions`. Then enable the `cloudbees` profile and attempt to do the same.

### Expected behavior
It should use the versions defined in `cloudbees-jenkins-x-versions`

### Actual behavior
Uses whatever versions are defined in the local `jenkins-x-versions` repository, without checking whether it's the correct one or not.

### Jx version
CJXD Release 1:

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.521
Kubernetes cluster v1.12.8-gke.10
kubectl            v1.15.1
helm client        Client: v2.13.1+g618447c
git                git version 2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.4 build 18E226
```
### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Now that the standard version stream cloning logic has merged, let's use that in metapipeline rather than its own logic.

#### Special notes for the reviewer(s)

/assign @pmuir 
/assign @hferentschik 

#### Which issue this PR fixes

fixes #5075

### CODE REVIEW

**Comment by hferentschik** [comment]
@abayer how does this fix #5075?

**Comment by abayer** [comment]
@hferentschik I'm kinda guessing. =) I'll add a test to verify, but I believe that the now-standard cloning approach handles that scenario.

**Comment by hferentschik** [comment]
>  I'll add a test to verify,

+1

File: pkg/cmd/controller/pipeline/pipelinerunner_cmd.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ func (o *PipelineRunnerOptions) Run() error {
 		return err
 	}
 
-	metapipelineClient, err := metapipeline.NewMetaPipelineClient()
+	metapipelineClient, err := metapipeline.NewMetaPipelineClient(o.Git(), o.In, o.Out, o.Err)
```
Comment (hferentschik) [inline pkg/cmd/controller/pipeline/pipelinerunner_cmd.go]: I've seen this now at several places that we pass all three standard file handles explicitly. I've been thinking it would make sense to wrap this into some utility struct like `IOFileHandles`. Definitely would help to reduce the number of function parameters and I think there is potential for some shared behaviour in this struct as well then (maybe not in this case).

File: pkg/tekton/metapipeline/clientfactory.go [hunk 2]
```diff
@@ -41,6 +42,12 @@ type clientFactory struct {
 	kubeClient   kubernetes.Interface
 	ns           string
 
+	git    gits.Gitter
+	stderr io.Writer
```
Comment (hferentschik) [inline pkg/tekton/metapipeline/clientfactory.go]: so `stderr` is not a terminal.FileWriter?

File: pkg/tekton/metapipeline/clientfactory.go [hunk 3]
```diff
@@ -41,6 +42,12 @@ type clientFactory struct {
...
+	stdin  terminal.FileReader
+	stdout terminal.FileWriter
+
+	teamSettings     *v1.TeamSettings
```
Comment (hferentschik) [inline pkg/tekton/metapipeline/clientfactory.go]: Do we really want to have a pointer? I'd prefer a value instance if possible.

File: pkg/tekton/metapipeline/clientfactory.go [hunk 4]
```diff
@@ -75,6 +82,11 @@ func NewMetaPipelineClientWithClientsAndNamespace(jxClient versioned.Interface,
 		tektonClient:     tektonClient,
 		kubeClient:       kubeClient,
 		ns:               ns,
+		git:              gitter,
+		stdin:            stdin,
+		stdout:           stdout,
+		stderr:           stderr,
+		teamSettings:     teamSettings,
```
Comment (hferentschik) [inline pkg/tekton/metapipeline/clientfactory.go]: I might be mistaken, but do we really need _teamSettings_ as an instance variable?

File: pkg/tekton/metapipeline/clientfactory.go [hunk 5]
```diff
@@ -216,18 +228,21 @@ func versionStreamURLAndRef(jxClient versioned.Interface, ns string) (string, st
...
+	teamSettings, url, ref, err := versionStreamURLAndRef(c.jxClient, c.ns)
 	if err != nil {
 		return err
 	}
 
 	if c.versionStreamURL != url || c.versionStreamRef != ref {
 		oldVersionStreamDir := c.versionDir
-		c.versionDir, err = cloneVersionStream(url, ref)
+		c.versionDir, _, err = versionstreamrepo.CloneJXVersionsRepo(url, ref, teamSettings, c.git, true, false, c.stdin, c.stdout, c.stderr)
+		c.teamSettings = teamSettings
```
Comment (hferentschik) [inline pkg/tekton/metapipeline/clientfactory.go]: You keep updating the instance `teamSetting`, but I cannot see where it is used.

File: pkg/tekton/metapipeline/clientfactory.go [hunk 6]
```diff
@@ -237,68 +252,6 @@ func (c *clientFactory) cloneVersionStreamIfNeeded() error {
 	return nil
 }
 
-func cloneVersionStream(url string, ref string) (string, error) {
```
Comment (hferentschik) [inline pkg/tekton/metapipeline/clientfactory.go]: 👍

File: pkg/tekton/metapipeline/clientfactory.go (hunk 5 above)
Comment (abayer) [reply pkg/tekton/metapipeline/clientfactory.go]: Ah, good point. I did need it at one point but then refactored.

File: pkg/tekton/metapipeline/clientfactory.go (hunk 2 above)
Comment (abayer) [reply pkg/tekton/metapipeline/clientfactory.go]: Nope.

**Comment by abayer** [comment]
@hferentschik Removed the team settings field since it was in fact unused, added a test for #5075 - verified that it does now remove the existing `jenkins-x-versions` clone and replace it.

File: pkg/tekton/metapipeline/clientfactory.go (hunk 2 above)
Comment (hferentschik) [reply pkg/tekton/metapipeline/clientfactory.go]: if it were me, I'd have a wrapper which wraps all three streams as their underlying io.[Reader|Writer] with a function to wrap then as a terminal xyz.

File: pkg/tekton/metapipeline/clientfactory.go (hunk 5 above)
Comment (hferentschik) [reply pkg/tekton/metapipeline/clientfactory.go]: let's get rid of it then :-)

**Comment by hferentschik** [comment]
/test boot-vault

@abayer, I've seen several failed boot-vault context over the last couple of days. Any idea why this context fails so often?

**Comment by abayer** [comment]
@hferentschik From what I can tell, it looks like Google Cloud load balancer provisioning has been taking abnormally long today, so...sometimes `boot-vault` times out trying to get the ingress domain. Is annoying.

File: pkg/tekton/metapipeline/clientfactory.go (hunk 2 above)
Comment (abayer) [reply pkg/tekton/metapipeline/clientfactory.go]: Yeah, I'm gonna open an issue for general refactoring around the streams - starting with the struct idea you had.
