### PR TITLE
fix:(preview) Try getting CHANGE_URL env variable for PRs, fixes #2174

### LINKED ISSUE #2174: jx preview uses incorrect repo name for PRs on Bitbucket Cloud
### Summary 

`jx preview` queries the wrong repo's PR endpoint on Bitbucket Cloud.

### Jx version

The output of `jx version` is:

```
jx                 1.3.516
Kubernetes cluster v1.9.7-gke.6
kubectl            v1.12.0
helm client        v2.11.0+g2e55dbe
helm server        v2.10.0+g9ad53aa
git                git version 2.17.2 (Apple Git-113)
```

### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?

### Operating system / Environment

macOS 10.14.1

### Expected behavior

`jx preview` should query the base/destination repo for a PR.

### Actual behavior

`jx preview` is querying the head/source repo.

I get the following error when creating a PR on Bitbucket Cloud:

```
issue getting pull request wbrefvem, promotion-debug-20181105-fork, 3: Status: 404 Not Found, Body: Not Found
```

The repo `promotion-debug-20181105-fork` is the head, not the base, so it makes sense that querying for a PR on it would return 404.

I think the following line from the `General SCM` step may be relevant:

```
 > git config remote.origin.url https://bitbucket.org/wbrefvem/promotion-debug-20181105-fork.git # timeout=10
```

When using GitHub, this line would set `remote.origin.url` to the base repo, not the head/fork. My hypothesis is that this difference is likely responsible for some of the gremlins around promotion as well.

### PR DESCRIPTION
**Pull request by wbrefvem**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description

For Jenkins pipeline builds triggered by PRs from Bitbucket Cloud, the `discoverGitUrl` logic currently pulls the incorrect repo from the pipeline workspace's git conf. `CHANGE_URL` should always contain the correct repo for git providers that have a Branch Source plugin, such as Bitbucket and GitHub, so pulling that env variable is now part of the git URL discovery logic. 

There's likely a similar gremlin lurking in promotion somewhere.

#### Which issue this PR fixes

fixes #2174

### CODE REVIEW

File: pkg/gits/git_cli.go [hunk 1]
```diff
@@ -313,7 +313,11 @@ func (g *GitCLI) Info(dir string) (*GitRepositoryInfo, error) {
 	if err != nil && strings.Contains(text, "Not a git repository") {
 		rUrl = os.Getenv("SOURCE_URL")
 		if rUrl == "" {
-			return nil, fmt.Errorf("you are not in a Git repository - promotion command should be executed from an application directory")
+			// Relevant in a Jenkins pipeline triggered by a PR
+			rUrl = os.Getenv("CHANGE_URL")
```
Comment (pmuir) [inline pkg/gits/git_cli.go]: `SOURCE_URL` is consistently set by Prow, but I guess this happens when you run in classic Jenkins.
