### PR TITLE
fix: prevent concurrent build to edit the same namespace

### LINKED ISSUE #6167: Environment wiped out during concurrent builds
### Summary 

This is a problem that kept me busy several days. When several environment build pipeline happen roughly at the same time (because several application master branches has been updated at the same time), the environment can be totally wiped out. It includes the deployments, the services, the ingresses, ... everything managed by the charts.

After adding outputs to jx (to see output of `kubect apply` and `kubectl delete`), the cause is clear:
- the first build runs `kubect apply` and sets everything to version to 61
- the second build runs `kubect apply` and sets everything to versions to 62
- the first build runs `kubectl delete` and deletes everything which has not the version 61, meaning at this point literally everything.
- the first build runs `kubectl delete` but there's nothing left anyway.

Both staging and production can be impacted. In production can be more careful to not promote applications too fast.

### Solutions

This is a synchronization problem.

The condition `jenkins.io/chart-release=jx,jenkins.io/version!=78` seems quite violent, `jenkins.io/chart-release=jx,jenkins.io/version<78` could already be much safer.

I think that if the `jx step helm apply` is cut in two step (`jx step helm apply` and `jx step helm clean`), and that before each of the step, a step checks that the pipeline is the latest version, most of the problems could be avoided.

But unlikely order of events could still be a problem.

### Steps to reproduce the behavior

Just run many pipelines
```
jx start pipeline my-repo/my-project-1/master
jx start pipeline my-repo/my-project-2/master
jx start pipeline my-repo/my-project-3/master
jx start pipeline my-repo/my-project-4/master
jx start pipeline my-repo/my-project-5/master
```
Wait and pray to see it
```
watch kubectl get all -n jx-staging
```

### Expected behavior

Pipelines should happen one by one, and everybody should be happy.

### Actual behavior

The environment gets totally wiped out, and everybody is sad.

### Jx version

The current head of `jx` (d2b7a7115fed1c537491ad556fd558a27b621163), customized to display `kubectl apply` and `kubectl output`

The output of `jx version` is:
```
NAME               VERSION
jx                 2.0.998-dev+46a9e4e6e
Kubernetes cluster v1.14.8-gke.12
kubectl            v1.14.7
helm client        Client: v2.14.3+g0e7f3b6
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

Standard `jx create cluster gke` `jx boot` process.

### Operating system / Environment

```
Ubuntu 18.04.3 LTS
```

### More

Here is what I could see while running 5 builds (form `#77` to `#81`). I've lost `#77` logs, but there was nothing specific to notice. `#78` clearly wiped out everything (apparently with the kind help of `#80`)

`xxx/environment-xxx-staging/master #78 promotion`
```
kubectl apply --recursive -f /tmp/helm-template-workdir-948611119/jx/output/namespaces/jx-staging -l jenkins.io/chart-release=jx --namespace jx-staging --wait --validate=false
==========
deployment.extensions/jx-api-poi-v2 configured
release.jenkins.io/api-poi-v2-0.0.20 created
service/api-poi-v2 configured
role.rbac.authorization.k8s.io/cleanup configured
rolebinding.rbac.authorization.k8s.io/cleanup configured
serviceaccount/cleanup configured
configmap/exposecontroller configured
role.rbac.authorization.k8s.io/expose configured
rolebinding.rbac.authorization.k8s.io/expose configured
serviceaccount/expose configured
deployment.extensions/jx-olli-log-management configured
ingress.extensions/jx-olli-log-management configured
issuer.certmanager.k8s.io/letsencrypt-prod configured
release.jenkins.io/olli-log-management-0.0.75 configured
service/olli-log-management configured
configmap/skills-server-redis configured
service/skills-server-redis-headless configured
configmap/skills-server-redis-health configured
statefulset.apps/skills-server-redis-master configured
service/skills-server-redis-master configured
deployment.extensions/jx-skills-server-x configured
release.jenkins.io/skills-server-x-0.0.37 created
service/skills-server-x configured
deployment.extensions/jx-skills-vue-x configured
ingress.extensions/jx-skills-vue-x configured
release.jenkins.io/skills-vue-x-0.0.59 created
service/skills-vue-x configured
deployment.extensions/jx-testx configured
release.jenkins.io/testx-0.0.7 created
service/testx configured
==========


kubectl delete all --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
service "skills-server-redis-headless" deleted
service "skills-server-redis-master" deleted
service "skills-vue-x" deleted
deployment.apps "jx-api-poi-v2" deleted
deployment.apps "jx-olli-log-management" deleted
deployment.apps "jx-skills-server-x" deleted
deployment.apps "jx-skills-vue-x" deleted
deployment.apps "jx-testx" deleted
release.jenkins.io "olli-log-management-0.0.75" deleted
==========
kubectldelete pvc --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete configmap --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
configmap "exposecontroller" deleted
configmap "skills-server-redis" deleted
configmap "skills-server-redis-health" deleted
==========
kubectl delete release --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete sa --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
serviceaccount "cleanup" deleted
serviceaccount "expose" deleted
==========
kubectl delete role --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
role.rbac.authorization.k8s.io "cleanup" deleted
role.rbac.authorization.k8s.io "expose" deleted
==========
kubectl delete rolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
rolebinding.rbac.authorization.k8s.io "cleanup" deleted
rolebinding.rbac.authorization.k8s.io "expose" deleted
==========
kubectl delete secret --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrole --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=78,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
error: upgrading helm chart '.': failed to run 'kubectl delete -f /tmp/helm-template-workdir-948611119/jx/helmHooks/env/charts/expose/templates/job.yaml --namespace jx-staging --wait' command in directory '/tmp/jx-helm-apply-142711026/env', output: 'Error from server (NotFound): error when deleting "/tmp/helm-template-workdir-948611119/jx/helmHooks/env/charts/expose/templates/job.yaml": jobs.batch "expose" not found'
```

`xxx/environment-xxx-staging/master #79 promotion`
```
Showing logs for build xxx/environment-xxx-staging/master #79 promotion stage meta-pipeline and container step-create-tekton-crds                                                                                                                              
? A local Jenkins X versions repository already exists, pulling the latest: Yes
running command: jx step next-version --use-git-tag-only --tag
created new version: 0.0.73 and written to file: ./VERSION
error: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: To https://github.com/xxx/environment-x-staging.git
 ! [rejected]        v0.0.73 -> v0.0.73 (already exists)
error: failed to push some refs to 'https://github.com/xxx/environment-xxx-staging.git'
hint: Updates were rejected because the tag already exists in the remote.: failed to run 'git push origin v0.0.73' command in directory '', output: 'To https://github.com/xxx/environment-xxx-staging.git
 ! [rejected]        v0.0.73 -> v0.0.73 (already exists)
error: failed to push some refs to 'https://github.com/xxx/environment-xxx-staging.git'
hint: Updates were rejected because the tag already exists in the remote.'
error: failed to set the version on release pipelines: failed to run '/bin/sh -c jx step next-version --use-git-tag-only --tag' command in directory '/workspace/source', output: ''

Pipeline failed on stage 'meta-pipeline' : container 'step-create-tekton-crds'. The execution of the pipeline has stopped.
```

`xxx/environment-xxx-staging/master #80 promotion`
```
kubectl apply --recursive -f /tmp/helm-template-workdir-154755877/jx/output/namespaces/jx-staging -l jenkins.io/chart-release=jx --namespace jx-staging --wait --validate=false
==========
deployment.extensions/jx-api-poi-v2 configured
release.jenkins.io/api-poi-v2-0.0.20 configured
service/api-poi-v2 configured
role.rbac.authorization.k8s.io/cleanup configured
rolebinding.rbac.authorization.k8s.io/cleanup configured
serviceaccount/cleanup configured
configmap/exposecontroller configured
role.rbac.authorization.k8s.io/expose configured
rolebinding.rbac.authorization.k8s.io/expose configured
serviceaccount/expose configured
deployment.extensions/jx-olli-log-management configured
ingress.extensions/jx-olli-log-management configured
issuer.certmanager.k8s.io/letsencrypt-prod configured
release.jenkins.io/olli-log-management-0.0.75 configured
service/olli-log-management configured
configmap/skills-server-redis configured
service/skills-server-redis-headless configured
configmap/skills-server-redis-health configured
statefulset.apps/skills-server-redis-master configured
service/skills-server-redis-master configured
deployment.extensions/jx-skills-server-x configured
release.jenkins.io/skills-server-x-0.0.37 configured
service/skills-server-x configured
deployment.extensions/jx-skills-vue-x configured
ingress.extensions/jx-skills-vue-x configured
release.jenkins.io/skills-vue-x-0.0.59 configured
service/skills-vue-x configured
deployment.extensions/jx-testx configured
release.jenkins.io/testx-0.0.7 configured
service/testx configured
==========


kubectl delete all --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
service "api-poi-v2" deleted
service "olli-log-management" deleted
service "skills-server-x" deleted
service "testx" deleted
statefulset.apps "skills-server-redis-master" deleted
release.jenkins.io "api-poi-v2-0.0.20" deleted
release.jenkins.io "skills-server-x-0.0.37" deleted
release.jenkins.io "skills-vue-x-0.0.59" deleted
release.jenkins.io "testx-0.0.7" deleted
==========
kubectldelete pvc --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete configmap --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete release --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete sa --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete role --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete rolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete secret --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrole --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=80,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
```

`xxx/environment-xxx-staging/master #81 promotion`
```
kubectl apply --recursive -f /tmp/helm-template-workdir-707178113/jx/output/namespaces/jx-staging -l jenkins.io/chart-release=jx --namespace jx-staging --wait --validate=false
==========
deployment.extensions/jx-api-poi-v2 configured
release.jenkins.io/api-poi-v2-0.0.20 configured
service/api-poi-v2 configured
role.rbac.authorization.k8s.io/cleanup configured
rolebinding.rbac.authorization.k8s.io/cleanup configured
serviceaccount/cleanup configured
configmap/exposecontroller configured
role.rbac.authorization.k8s.io/expose configured
rolebinding.rbac.authorization.k8s.io/expose configured
serviceaccount/expose configured
deployment.extensions/jx-olli-log-management configured
ingress.extensions/jx-olli-log-management configured
issuer.certmanager.k8s.io/letsencrypt-prod configured
release.jenkins.io/olli-log-management-0.0.75 configured
service/olli-log-management configured
configmap/skills-server-redis configured
service/skills-server-redis-headless configured
configmap/skills-server-redis-health configured
statefulset.apps/skills-server-redis-master configured
service/skills-server-redis-master configured
deployment.extensions/jx-skills-server-x configured
release.jenkins.io/skills-server-x-0.0.37 configured
service/skills-server-x configured
deployment.extensions/jx-skills-vue-x configured
ingress.extensions/jx-skills-vue-x configured
release.jenkins.io/skills-vue-x-0.0.59 configured
service/skills-vue-x configured
deployment.extensions/jx-testx configured
release.jenkins.io/testx-0.0.7 configured
service/testx configured
==========


kubectl delete all --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
release.jenkins.io "api-poi-v2-0.0.19" deleted
release.jenkins.io "skills-server-x-0.0.36" deleted
release.jenkins.io "skills-vue-x-0.0.57" deleted
release.jenkins.io "testx-0.0.6" deleted
==========
kubectl delete pvc --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete configmap --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete release --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete sa --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete role --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete rolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete secret --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81 --namespace jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrole --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
kubectl delete clusterrolebinding --ignore-not-found -l jenkins.io/chart-release=jx,jenkins.io/version!=81,jenkins.io/namespace=jx-staging --wait
==========
No resources found
==========
error: upgrading helm chart '.': failed to run 'kubectl delete -f /tmp/helm-template-workdir-707178113/jx/helmHooks/env/charts/expose/templates/job.yaml --namespace jx-staging --wait' command in directory '/tmp/jx-helm-apply-934058140/env', output: 'Error from server (NotFound): error when deleting "/tmp/helm-template-workdir-707178113/jx/helmHooks/env/charts/expose/templates/job.yaml": jobs.batch "expose" not found'
```

### PR DESCRIPTION
**Pull request by aure-olli**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This PR prevents builds to edit the same namespace at the same time. Such a behavior could lead to a namespace to be accidentally wiped out.

Only `jx step helm apply` is locked.

#### Special notes for the reviewer(s)

A ConfigMap `jx-lock-{namespace}` is used as a lock. No other build can run while this configmap exists. Waiting builds can edit the data of the ConfigMap in order to be the next one to run. If a build sees that the locking or waiting build is "higher", it will fail. When the build finished, the ConfigMap is removed. A waiting build can also remove the ConfigMap if the lokcing pod has finished.

The algorithm is approximately:
```
    Label: CREATE
    try to create the ConfigMap
    if it succeeds:
        return
    Label: READ
    get the ConfigMap and the locking Pod
    if the locking Pod has finished
        remove the ConfigMap
        goto CREATE
    if the ConfigMap references a "higher" build
        fail
    if the ConfigMap references a "lower" build
        update the ConfigMap
    wait for the ConfigMap or the Pod to be updated
        if the ConfigMap is delete
            goto CREATE
        if the ConfigMap references a different build
            goto READ
        if the Pod has finished
            goto CREATE
```

#### Which issue this PR fixes

fixes #6167

#### Issues

- there is currently no easy way to know which pod `jx` is running in. The pipeline could be changed to give such an info: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
- I currently use the filter `owner={REPO_OWNER},repository={REPO_NAME}s,branch={BRANCH_NAME},build={BUILD_NUMBER},jenkins.io/pipelineType=build`, using the headers. I'm afraid such a filter is specific to specific kind of pipelines.
- I also use those headers to compare builds. If a build has the same owner, repo and branch, I compare the build number. If not, I compare a timestamp (I ensure that the timestamp is always increasing though).
- It could be easily added to other `jx` commands. But I'm not sure which ones need.
- `make lint` made a huge update of `go.mod`. No idea why.

### CODE REVIEW

**Comment by abayer** [comment]
Woo! Happy to see this being worked on. I’ll get you the failed build logs in a bit.

The labels you’re looking at are consistent for all pipelines. I’ll look into the env cars exposing pod info, but think that will probably need to be dealt with in Tekton.

**Comment by abayer** [comment]
So a quick bit on the failed tests - when booting for the bdd tests, `jx step helm apply` is called in each of the contexts and fails due to boot not running inside a pod. We’re setting an env var for that - `JX_INTERPRET_PIPELINE`. The locking should probably be aware of that, most likely bypassing the lock check if it’s set. The `Tekton` context, running via `jx install`, passed, which is a good sign, though bdd, with `jx install` and static masters, didn’t. I’m gonna rerun that one to see if it’s just transient noise.

**Comment by abayer** [comment]
`integration` is failing with `pkg/kube/build_lock.go:48: Warnf call needs 1 arg but has 2 args`, and `unit` is failing with that and:

```
--- FAIL: TestApplyAppsTemplateOverrides (0.16s)
    step_helm_apply_test.go:78: 
        	Error Trace:	step_helm_apply_test.go:78
        	Error:      	Received unexpected error:
        	            	0 pods found for this job (owner=jenkins-x,repository=**,branch=PR-6953,build=6,jenkins.io/pipelineType=build)
        	            	fail to acquire the lock
        	            	github.com/jenkins-x/**/pkg/cmd/step/helm.(*StepHelmApplyOptions).Run
        	            		/workspace/source/pkg/cmd/step/helm/step_helm_apply.go:193
        	            	github.com/jenkins-x/**/pkg/cmd/step/helm_test.TestApplyAppsTemplateOverrides
        	            		/workspace/source/pkg/cmd/step/helm/step_helm_apply_test.go:77
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:865
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1337
        	Test:       	TestApplyAppsTemplateOverrides
    step_helm_apply_test.go:94: 
        	Error Trace:	step_helm_apply_test.go:94
        	Error:      	Not equal: 
        	            	expected: "**-app-dummy"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-**-app-dummy
        	            	+
        	Test:       	TestApplyAppsTemplateOverrides
FAIL
```

**Comment by abayer** [comment]
Ok, `bdd` context failure is legit: 

```
[Pipeline] sh
+ jx step helm apply
Modified file /home/jenkins/agent/workspace/3-8-static-gkebdd-staging_master/env/Chart.yaml to set the chart to version 2
WARNING: no REPO_OWNER provided
error: fail to acquire the lock: no REPO_OWNER provided
```

The env vars are annoyingly different on static masters, and, frankly, we don't care a ton about static masters since we're removing them next month. I'm trying to think of an env var we could look for that would signify "this is running in a static master" that we could just use to ignore the locking behavior when running in a Jenkins pipeline via a static master. `EXECUTOR_NUMBER` maybe?

**Comment by abayer** [comment]
Ah-ha - better than an env var, we could just check https://github.com/jenkins-x/jx/blob/a306c29ac2a8f926c93d4aaacf540d7a361b4baa/pkg/kube/namespaces.go#L129 at the beginning of `AcquireLock` and return a no-op function if it's false.

**Comment by hferentschik** [comment]
I am wondering whether it would make sense to write some integration tests for `kube.AcquireBuildLock`? It would help to evaluate the algorithm.

**Comment by aure-olli** [comment]
I updated the PR (I forgot to fix the commit message, will fix next update). I hopefully fixed the integration test.

> I am wondering whether it would make sense to write some integration tests for `kube.AcquireBuildLock`? It would help to evaluate the algorithm.

I totally agree ! but writing tests take time, I wanted to check if people agree with my fix first.

**Comment by aure-olli** [comment]
I've created tests to try most situation, and consequently fixed a bug.
If I test on my cluster, the behavior is the expected one. For instance, here is the build 35 waiting for the build 34, until the build 38 shows up.
```
Showing logs for build olli-ai/environment-jenkins-x1-test/master #35 stage from-build-pack and container step-build-helm-apply
Modified file /workspace/source/env/Chart.yaml to set the chart to version 35
creating the lock configmap jx-lock-jx-test
lock configmap jx-lock-jx-test already exists
locking pod olli-ai-environment-jenkins-x1-6dggt-34-from-build-pack-4nk58-pod-74812a is in phase Running
waiting for updates on the lock configmap jx-lock-jx-test
WARNING: newer build 38 is waiting already
error: fail to acquire the lock: newer build 38 is waiting already
```
I have no idea why lint is failing, it seems to work fine in local (or at least as fine as it used to).

**Comment by abayer** [comment]
FYI, lint is failing due to:
```
The following 1 test files are not classified with a valid Go build tag [unit|integration]
./hack/../pkg/kube/build_lock_test.go
```

**Comment by abayer** [comment]
And `boot-vault` is still failing for the same reason as before. =)

**Comment by aure-olli** [comment]
Ok so this should fix `lint`.
I don't understand why `boot-vault` is failing though, I've checked `IsTektonEnabled` for that purpose, and `bdd` now works. Should I check `JX_INTERPRET_PIPELINE` too ?

File: pkg/kube/build_lock.go [hunk 1]
```diff
@@ -0,0 +1,415 @@
...
+		log.Logger().Warnf("no BRANCH_NAME provided")
+		return nil, fmt.Errorf("no BRANCH_NAME provided")
+	}
+	build := os.Getenv("BUILD_NUMBER")
+	if _, err := strconv.Atoi(build); err != nil {
+		log.Logger().Warnf("no BUILD_NUMBER provided: %s\n", err.Error())
+		return nil, err
+	}
+	// Find our pod
+	podList, err := kubeClient.CoreV1().Pods(devNamespace).List(metav1.ListOptions{
```
Comment (hferentschik) [inline pkg/kube/build_lock.go]: I am struggling a bit why we need to tie the locking via a `ConfigMap` to a running pod? Even though uncommon, I think about the case where the step is executed locally. `jx boot` comes to mind.

Could we just not work with the ConfigMap? I think that's also what @ccojocar suggested in a comment on the issue.

File: pkg/kube/build_lock.go [hunk 2]
```diff
@@ -0,0 +1,415 @@
...
+	"jenkins-x.io/kind": "build-lock",
+}
+
+// AcquireBuildLock acquires a build lock, to avoid other builds to edit the
+// same namespace while a deployment is already running, other deployments
+// can negotiate which one should run after, by editing its data.
+// Returns a function to release the lock (to be called in a defer)
+// Returns an error if a newer build is already running, or if an error happened
+func AcquireBuildLock(kubeClient kubernetes.Interface, devNamespace, namespace string) (func() error, error) {
+	// Only lock if running in Tekton
```
Comment (hferentschik) [inline pkg/kube/build_lock.go]: this is a heck of a function, I am wondering whether it could not be split up a bit?

File: pkg/kube/build_lock.go [hunk 3]
```diff
@@ -0,0 +1,415 @@
...
+			"build":      build,
+			"pod":        pod.Name,
+			"timestamp":  now,
+		},
+	}
+	for k, v := range buildLockLabels {
+		lock.Labels[k] = v
+	}
+	// this loop continuously tries to create the lock
+Create:
```
Comment (hferentschik) [inline pkg/kube/build_lock.go]: hmmm, do we really need to use labels?

File: go.mod [hunk 4]
```diff
@@ -49,9 +49,9 @@ require (
 	github.com/ghodss/yaml v1.0.0
 	github.com/gliderlabs/ssh v0.1.1 // indirect
 	github.com/go-ole/go-ole v1.2.1 // indirect
-	github.com/go-openapi/jsonreference v0.19.2
-	github.com/go-openapi/spec v0.19.3
-	github.com/go-stack/stack v1.8.0 // indirect
+	github.com/go-openapi/jsonreference v0.19.3
```
[the remark this answers is not in the document]
Comment (aure-olli) [reply go.mod]: Those dependencies were updated by `make lint` for a reason I ignore (or `gofmt`, not sure anymore). I'll try to clean most of them then.

File: pkg/kube/build_lock.go (hunk 1 above)
Comment (aure-olli) [reply pkg/kube/build_lock.go]: The idea to use a ConfigMap is because we need an atomic operation at the Kubernetes level. Only create-update-delete are atomic as far as I know. Looking at the present pods is not a strong guarantee. Plus the ConfigMap is a playground for other job to negotiate which one will be next.

The ConfigMap is linked to a pod such that we can know if the pipeline is still running, in case of the pipeline did not have the opportunity to clean the ConfigMap (for instance with `jx stop pipeline`). If not, the lock could lock every future build.

I agree that this mechanism is not adapted to local commands like `jx boot`. But first those are manual commands, there is no reason for it to be launched 2 times. Second, I think blocking `jx boot` because another one may be running (and we don't have any way to be sure) could be horribly wrong when somebody is trying to fix a failed `jx boot`.

File: pkg/kube/build_lock.go (hunk 2 above)
Comment (aure-olli) [reply pkg/kube/build_lock.go]: Sure it can be, I'll work on that.

File: pkg/kube/build_lock.go (hunk 3 above)
Comment (aure-olli) [reply pkg/kube/build_lock.go]: We never have to use labels (same as you never have to use GOTO). But in that case, we will instead have to signify which loop should break and which one should continue. I don't thin kit will make the algorithm more clear. The algorithm is basically a state machine, and those are well described with GOTO ...

Comment (aure-olli) [reply pkg/kube/build_lock.go]: Oh sorry did you mean labels on the lock ? Well most of them let you know who is locking currently. They are similar to the ones in the pod. I also added a label to be sure that build are not log by another configmap that shouldn't be here (or maybe later another version of the same lock), that would cause a bug due to a different format. Nothing mandatory, just felt like it was cleaner.

File: pkg/kube/build_lock.go (hunk 1 above)
Comment (hferentschik) [reply pkg/kube/build_lock.go]: > The idea to use a ConfigMap is because we need an atomic operation at the Kubernetes level. Only create-update-delete are atomic as far as I know. 

I am onboard with the ConfigMap. I think that's the right thing to do.

> The ConfigMap is linked to a pod such that we can know if the pipeline is still running,

That's the part I am not so sure about. The linking to a pod. 

> If not, the lock could lock every future build.

Well, right. There is a potential for a lock not getting cleaned up if something crashes, but I was more thinking about working with timeouts. If there is a lock which does not get cleaned up and another build exceeds its timeout it will fail with an appropriate error message. And yes, one needs to then either manually delete the lock (which might be the first approach) or then eventually build something into `jx`. I think that would make things also a bit simpler and solve also the running locally case.

> Second, I think blocking jx boot because another one may be running ...

I am not so sure. There is actually an open issue for this as well. Given that the outcome of two concurrent boot runs would be unclear at best, I'd argue a `jx boot` needs to be locked as well. If you try to "fix" a failed install and there are locking issues, I would expect that you sort them out first. 

@jenkins-x/core thoughts?

**Comment by aure-olli** [comment]
OK I've restored `go.mod`/`go.sum` (it was updated by `make lint`), and refactored the main function to make it less long.

I'm actually not clear how `jx boot` works. So it look like it creates a pipeline but runs it locally, and uses the `JX_INTERPRET_PIPELINE` header to say so. It also looks like it still have a `REPO_OWNER`, `REPO_NAME` and `BUILD_NUMBER`. So there is no way to know if the "pipeline" is still running, we can only rely on some timeout.

Then I'll implement 2 mechanisms: if there is a pod (ie no `JX_INTERPRET_PIPELINE`), we keep linking to the pod. And if there is no pod (ie `JX_INTERPRET_PIPELINE=true`), we rely on a timeout compared to the `creationTimestamp` with some timeout (let's say one hour ?). And a message telling that the configmap should be removed to avoid waiting.

**Comment by aure-olli** [comment]
So as said before, there are now 2 version of the lock:
- Attached to a pod, if `JX_INTERPRET_PIPELINE` is undefined. Can be safely deleted once the pod has succeeded or failed.
- Unattached, if `JX_INTERPRET_PIPELINE=true`. It has then an `expires` field, and when it reaches its expiration date it can be safely deleted.

This should make `jx boot` safer too, as long as any edition of the namespace is done within the lock (currently only `jx step helm install`, but it's easy to add any command).

File: pkg/kube/build_lock.go [hunk 5]
```diff
@@ -0,0 +1,499 @@
...
+	return false, pod, nil
+}
+
+// watchBuildLock watches a lock configmap and its locking pod to detect any change
+// Returns nil if the lock was deleted, or is expected to be deleted
+// Returns the new lock configmap if another build is waiting
+func watchBuildLock(kubeClient kubernetes.Interface, lock *v1.ConfigMap, pod *v1.Pod, build map[string]string) (*v1.ConfigMap, error) {
+	log.Logger().Infof("waiting for updates on the lock configmap %s", lock.Name)
+	// watch a timer for expiration
+	var expChan <-chan time.Time
```
Comment (hferentschik) [inline pkg/kube/build_lock.go:340]: 👍

File: pkg/kube/build_lock_test.go [hunk 6]
```diff
@@ -0,0 +1,889 @@
...
+		}
+	}()
+	go func() {
+		time.Sleep(time.Duration(5) * time.Second)
+		c <- nil
+	}()
+	return clean, c
+}
+
+func builLockNoLock(t *testing.T, client kubernetes.Interface, namespace string) {
```
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/kube/build_lock_test.go:451]: Actually, instead of _buildLockNoLock_, is this not more of an _assertNoLock_ or _expectNoLock_?

File: pkg/kube/build_lock_test.go [hunk 7]
```diff
@@ -0,0 +1,889 @@
...
+	assert.Nil(t, lock)
+	if assert.Error(t, err) {
+		require.IsType(t, &errors.StatusError{}, err)
+		status := err.(*errors.StatusError)
+		require.Equal(t, metav1.StatusReasonNotFound, status.Status().Reason)
+	}
+}
+
+// builLockCheckLock checks if the lock configmap is correct
+func builLockCheckLock(t *testing.T, client kubernetes.Interface, namespace, owner, repository, branch, build string) {
```
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/kube/build_lock_test.go:462]: Actually, instead of builLockCheckLock, is this not more of an `assertLock`, `expectLock` or `verifyLock`?

**Comment by aure-olli** [comment]
I had to write those "hard to read" name because hound seem to care quite much about function names in test. I reverted it to a more readable form. The prefix is to avoid collisions with other tests in the package

**Comment by hferentschik** [comment]
@aure-olli thanks a lot for your pull request and your patience. Much appreciated.
