### PR TITLE
fix: check name of devEnv since devEnv never nil

### LINKED ISSUE #7432: Using boot on new installation always errors out
### Summary

When using `jx boot -r jx-requirements.yml` on a new cluster and a requirements file with few changes, `boot` errors out due to a possible stale requirements file.

### Steps to reproduce the behavior

- Clone [the default boot config repo](https://github.com/jenkins-x/jenkins-x-boot-config)
- Run `jx boot -r jx-requirements.yml`

### Expected behavior

The install to continue past the requirements file check.

### Actual behavior

```
$ jx boot -r jx-requirements.yml
Attempting to resolve version for boot config https://github.com/jenkins-x/jenkins-x-boot-config from https://github.com/jenkins-x/jenkins-x-versions.git
WARNING: when attempting to load team settings. the server could not find the requested resource (get environments.jenkins.io)
WARNING: It seems you're passing a requirements file to cluster which has already been provisioned.
WARNING: We recommend you update the jx-requirements.yml file at {  }, using the updates provided within your local jx-requirements.yml file.
error: loading from provided requirements file: attempting to boot cluster using a requirements file which is possibly stale
```

### Jx version

The output of `jx version` is:

```
Version        2.1.97
Commit         239bec3
Build date     2020-07-03T08:23:56Z
Go version     1.13.8
Git tree state clean
```

### Diagnostic information

The output of `jx diagnose version` is:

```
Running in namespace: default
WARNING: Failed to retrieve team settings: failed to setup the dev environment for namespace 'default': the server could not find the requested resource (post environments.jenkins.io) - falling back to default settings...
FATAL: Your current helm version v3 is not supported. Please downgrade to helm v2.
```

### Kubernetes cluster

This is a cluster created using kops on AWS GovCloud running k8s @ v1.16.10.

### Kubectl version
The output of `kubectl version --client` is:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
```

### Operating system / Environment

```
$ uname -srvmpio
Darwin 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```

### PR DESCRIPTION
**Pull request by searsaw**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
During boot, new installs were returning that the config was stale. Looking into it, it appears the function checking for this "staleness" assumed the returned environment could be `nil`. However, looking at the function that was called, it would never be `nil`. This PR just changes that check to make sure the returned environment has a name.

Closes #7432

### CODE REVIEW

**Comment by ankitm123** [comment]
@searsaw can you create an issue for this PR?

File: pkg/cmd/boot/boot.go [hunk 1]
```diff
@@ -505,7 +505,7 @@ func existingBootClone(dir string) (bool, error) {
 
 func (o *BootOptions) checkIfProvidedRequirementsArePossiblyStale() error {
 	_, devEnv := o.GetDevEnv()
-	if devEnv != nil {
```
Comment (ankitm123) [inline pkg/cmd/boot/boot.go:508]: Took a look at the function, and you are right, it never returns nil. 
I think we should to return nil from GetDevEnv(), instead of &jenkinsv1.Environment{}. However this function is used in a lot of different places, so it might be a breaking change. wdyt @abayer?

**Comment by searsaw** [comment]
@ ankitm123 #7432 created.

File: pkg/cmd/boot/boot.go (hunk 1 above)
Comment (abayer) [reply pkg/cmd/boot/boot.go:508]: This is called in enough places that it won't be trivial to switch it to returning nil, but it's probably worth the attempt.

Comment (searsaw) [reply pkg/cmd/boot/boot.go:508]: I can give it a shot.

Comment (ankitm123) [reply pkg/cmd/boot/boot.go:508]: That would be awesome :100:

Comment (searsaw) [reply pkg/cmd/boot/boot.go]: I've updated my PR to reflect this `GetDevEnv` returning `nil` instead.

**Comment by nodece** [comment]
please close issues: #7448

**Comment by searsaw** [comment]
@ankitm123 I looked into the failing unit tests here, and it appears they are also broken on master as well.

**Comment by ankitm123** [comment]
I will try to get the unit test logs, and see what is going on.

**Comment by MarckK** [comment]
The meta pipeline has failed due to the conflicting files `.secrets.baseline` (see above). 
Logs:
```
Auto-merging .secrets.baseline
CONFLICT (content): Merge conflict in .secrets.baseline
Automatic merge failed; fix conflicts and then commit the result.'
Pipeline failed on stage 'meta-pipeline' : container 'step-git-merge'. The execution of the pipeline has stopped.
```

**Comment by ankitm123** [comment]
@searsaw why these changes in the .secrets.baseline? also need to rebase.

**Comment by searsaw** [comment]
@ankitm123 Rebase complete. I have no idea why that file was updated. It was done as part of the pre-commit hook.
