### PR TITLE
fix: check helm compatibility to avoid using helm v3

### LINKED ISSUE #6181: Improve the error message when using helm v3
### Summary 
Helm v3 came out recently and I updated my helm version to v3.
When using jx create cluster .... I received the following 
WARNING: retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
WARNING:
retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'

### Steps to reproduce the behavior
On macOS brew install helm

### Expected behavior
An error message that helm v3 is not supported yet and that one need to install helm v2.

### Actual behavior
WARNING: retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
WARNING:
retrying after error:failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'
FATAL: helm init failed: after 3 attempts, last error: failed to run 'helm init --client-only' command in directory '', output: 'Error: unknown flag: --client-only'

### Jx version

The output of `jx version` is:

~ $ jx version
NAME               VERSION
jx                 2.0.881
jenkins x platform 2.0.1642
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.24.0
Operating System   Mac OS X 10.15.1 build 19B88

verifying packages

WARNING: jx version 2.0.1011 is available in the version stream. We highly recommend you upgrade to it.

### Jenkins type

- [ X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GCP

### Operating system / Environment

macOS

### PR DESCRIPTION
**Pull request by ccojocar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #6181

### CODE REVIEW

File: pkg/cmd/clients/factory.go [hunk 1]
```diff
@@ -747,6 +750,23 @@ func (f *factory) CreateHelm(verbose bool,
...
+		log.Logger().Warnf("Unable to detect the current helm version due to: %s", err)
+		return
+	}
+	v, err := semver.ParseTolerant(version)
+	if err != nil {
+		log.Logger().Warnf("Unable to parse the current helm version: %s", version)
+		return
+	}
+	if v.Major > 2 {
+		log.Logger().Fatalf("Your current helm version v3 is not supported. Please downgrade to helm v2.")
```
Comment (abayer) [inline pkg/cmd/clients/factory.go]: Probably worth change to `Your current helm version v%d` with `v.Major`, just in case something goes truly insane and they release v4 while we're not looking. =)

Comment (ccojocar) [reply pkg/cmd/clients/factory.go]: Fixed.

File: pkg/helm/helm_cli.go [hunk 2]
```diff
@@ -66,6 +65,35 @@ func NewHelmCLI(binary string, version Version, cwd string, debug bool, args ...
...
+		log.Logger().Warnf("Unable to detect the current helm version due to: %s", err)
+		return
+	}
+	v, err := semver.ParseTolerant(version)
+	if err != nil {
+		log.Logger().Warnf("Unable to parse the current helm version: %s", version)
+		return
+	}
+	if v.Major > 2 {
+		log.Logger().Fatalf("Your current helm version v%d is not supported. Please downgrade to helm v2.", v.Major)
```
Comment (hferentschik) [inline pkg/helm/helm_cli.go]: I am not a big fan of using `Fatalf`, but I guess w/o further changes that's the best we can do.

One could, however, return an error from `checkCompatibility` or a `bool` and a message `string`.  One can then use `Fatalf` in `NewHelmCLIWithCompatibilityCheck` based on the returned value. The benefit is that ` checkCompatibility`. Up to you. We can also merge as is.

Comment (ccojocar) [reply pkg/helm/helm_cli.go]: I though about about returning an error and let the caller to handle it but if it doesn't treat that error as fatal the execution might continue with an invalid helm version.

Comment (ccojocar) [reply pkg/helm/helm_cli.go]: and the `CreateHelm` doesn't propagate further any error, so we could log it there but keeping  this check encapsulated in the helm client wrapper seems more appropriate to me because we can have in future a different wrapper implementation for helm 3

Comment (ccojocar) [reply pkg/helm/helm_cli.go]: We can merge as it is if you are fine with it.

Comment (hferentschik) [reply pkg/helm/helm_cli.go]: Fair enough. Just wanted to hear your reasoning :-)
