### PR TITLE
Disabled prow configuration for jx delete app

### LINKED ISSUE #2331: jx delete application can't find apps
### Summary 
Running `jx delete application` is no working, the command returns that `There are no Apps in Jenkins` 

### Steps to reproduce the behavior
1. Run `jx get applications` and be sure you have some apps
2. Run 'jx delete application'

### Jx version

The output of `jx version` is:

NAME               VERSION
jx                 1.3.593
jenkins x platform 0.0.2934
Kubernetes cluster v1.9.7-gke.11
kubectl            v1.10.4
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.17.2 (Apple Git-113)
Operating System   Mac OS X 10.14 build 18A391

### Kubernetes cluster

GKE

### Operating system / Environment

Mac OS Mojave

### Expected behavior
`jx delete application your-app` should delete the app

### Actual behavior

```
Romains-MacBook-Pro:rverduci-test-org romain$ jx get applications
APPLICATION           STAGING PODS URL                                                                     PRODUCTION PODS URL
jx-spring             0.0.4   1/1  http://jx-spring.jx-staging.xxxxxx             0.0.4      1/1  http://jx-spring.jx-production.xxxx
reproduce-issue       0.0.3   1/1  http://reproduce-issue.jx-staging.xxxxx                       
rom-spring            0.0.9   1/1  http://rom-spring.jx-staging.xxxxx            0.0.9      1/1  http://rom-spring.jx-production.xxxx
spring-petclinic      0.0.11  1/1  http://spring-petclinic.jx-staging.xxxxx      0.0.8      1/1  http://spring-petclinic.jx-production.xxxxx
springboot-quickstart 0.0.2   1/1  http://springboot-quickstart.jx-staging.xxxx 0.0.2      1/1  http://springboot-quickstart.jx-production.xxxxx
Romains-MacBook-Pro:rverduci-test-org romain$ jx delete application
error: There are no Apps in Jenkins
```

It looks like jx delete application is looking for apps in static jenkins, which makes no sense if we are using serverless jenkins.

### PR DESCRIPTION
**Pull request by agentgonzo**
#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Description
Disabled the prow config and removed an application from running envirnoments when using `jx delete app`

#### Special notes for the reviewer(s)
I needed to add a new `--org` parameter to specify the github org when deleting an app as it is lost during the `import` or `create quickstart` process. My intention is that this will be stored in a new CRD in a subsequent PR

#### Which issue this PR fixes

fixes #2331

### CODE REVIEW

File: pkg/jx/cmd/delete_app.go [hunk 1]
```diff
@@ -90,23 +93,82 @@ func NewCmdDeleteApp(f Factory, in terminal.FileReader, out terminal.FileWriter,
...
+	if err != nil {
+		return errors.Wrapf(err, "deleting application")
+	}
+	log.Infof("Deleted Application(s): %s\n", util.ColorInfo(strings.Join(deletedApplications, ",")))
+	return nil
+}
+
+func (o *DeleteAppOptions) deleteProwApp() (deletedApplications []string, err error) {
+	if o.Org == "" {
+		return deletedApplications, errors.New("--org must be supplied")
```
Comment (jtnord) [inline pkg/jx/cmd/delete_app.go]: should this not return an empty array?  (ie if you ask to delete 5 apps and one failed I would expect a return with the 4 successfully deleted ones and an error?

(at least it implies the return is the applications that have been deleted)

Comment (agentgonzo) [reply pkg/jx/cmd/delete_app.go]: it does return an empty array. Due to the magic of go, the `deletedApplications` that is defined as a named return value gets initialised to the `nil` value at the start of the function. The `nil` value of an array/slice in go is (very much to my liking) an empty array/slice

File: pkg/jx/cmd/delete_app.go [hunk 2]
```diff
@@ -90,23 +93,82 @@ func NewCmdDeleteApp(f Factory, in terminal.FileReader, out terminal.FileWriter,
...
+	return
+}
+
+func (o *DeleteAppOptions) deleteJenkinsApp() (deletedApplications []string, err error) {
 	args := o.Args
 
 	jenk, err := o.JenkinsClient()
 	if err != nil {
-		return err
+		return
```
Comment (jtnord) [inline pkg/jx/cmd/delete_app.go]: bare returns are generally not used elswhere in the code, should we be introducing them here (there is an issue to remove the functionality from golang)

File: pkg/jx/cmd/delete_app.go [hunk 3]
```diff
@@ -120,58 +182,43 @@ func (o *DeleteAppOptions) Run() error {
...
-		duration, err := time.ParseDuration(o.Timeout)
-		if err != nil {
-			return fmt.Errorf("Invalid duration format %s for option --%s: %s", o.Timeout, optionTimeout, err)
-		}
-		o.TimeoutDuration = &duration
-	}
-
 	if len(names) == 0 {
-		return fmt.Errorf("There are no Apps in Jenkins")
+		return deletedApplications, fmt.Errorf("There are no Apps in Jenkins")
```
Comment (jtnord) [inline pkg/jx/cmd/delete_app.go]: NIT: this should be applications as apps are a different thing.  (not your code)

File: pkg/prow/config/tide.go [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+		// No Tide config needed for Protection
+	default:
+		return fmt.Errorf("unknown Prow config kind %s", kind)
+	}
+	return nil
+}
+
+func createApplicationTideQuery() config.TideQuery {
+	return config.TideQuery{
+		Repos:         []string{"jenkins-x/dummy"},
```
Comment (jtnord) [inline pkg/prow/config/tide.go]: this value looks weird but I see it is just a move of code.

File: pkg/jx/cmd/delete_app.go (hunk 3 above)
Comment (agentgonzo) [reply pkg/jx/cmd/delete_app.go]: yeah, :-(  - it's littered with references to app rather than 'application'. This PR's not the space to address it :-/

File: pkg/prow/config/tide.go (hunk 4 above)
Comment (agentgonzo) [reply pkg/prow/config/tide.go]: correct. No idea what it does

File: pkg/jx/cmd/delete_app.go (hunk 2 above)
Comment (agentgonzo) [reply pkg/jx/cmd/delete_app.go]: I'll take a look

Comment (agentgonzo) [reply pkg/jx/cmd/delete_app.go]: It's not a bare return anymore, it's a named return (I think) - it returns `(deletedApplications []string, err error)`

Comment (jtnord) [reply pkg/jx/cmd/delete_app.go]: I think the naming has changed over the time (bare = naked = named).  I may be wrong on that though

File: pkg/jx/cmd/get_applications.go [hunk 5]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+
+func (o *GetApplicationsOptions) generateTable(apps []string, envApps []EnvApps, kubeClient kubernetes.Interface) table.Table {
+	table := o.generateTableHeaders(envApps)
+
+	appEnvMap := map[string]map[string]*ApplicationEnvironmentInfo{}
+	for _, appName := range apps {
+		row := []string{appName}
+		for _, ea := range envApps {
+			version := ""
+			d := ea.Apps[appName]
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: I would really check if the `appName` is present in the map. 

```Go
d, ok := ea.Apps[appName]
if !ok {
...
}
```

File: pkg/jx/cmd/get_applications.go [hunk 6]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+			appMap := appEnvMap[appName]
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: The same here

File: pkg/jx/cmd/get_applications.go [hunk 7]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+				replicas := ""
+				ready := d.Status.ReadyReplicas
+				if d.Spec.Replicas != nil && ready > 0 {
+					replicas = formatInt32(*d.Spec.Replicas)
+					pods = formatInt32(ready) + "/" + replicas
+				}
+				row = append(row, pods)
+			}
+			if !o.HideUrl {
+				url, _ := services.FindServiceURL(kubeClient, d.Namespace, appName)
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: Why the error return by `FindServiceURL` is not handled here?

File: pkg/jx/cmd/get_applications.go [hunk 8]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+				if url == "" {
+					url, _ = services.FindServiceURL(kubeClient, d.Namespace, d.Name)
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: also here

File: pkg/jx/cmd/get_applications.go [hunk 9]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+				}
+				if url == "" {
+					// handle helm3
+					chart := d.Labels["chart"]
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: check if the deployment really has a `chart` label: e.g. `chart, ok := d.Labels["chart"]`

File: pkg/jx/cmd/get_applications.go [hunk 10]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+					if chart != "" {
+						idx := strings.LastIndex(chart, "-")
+						if idx > 0 {
+							svcName := chart[0:idx]
+							if svcName != appName && svcName != d.Name {
+								url, _ = services.FindServiceURL(kubeClient, d.Namespace, svcName)
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: error handling?

File: pkg/jx/cmd/get_applications.go [hunk 11]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
+func (o *GetApplicationsOptions) getAppData(kubeClient kubernetes.Interface) (namespaces []string, envApps []EnvApps, envNames, apps []string, err error) {
+	f := o.Factory
+	client, currentNs, err := f.CreateJXClient()
+	if err != nil {
+		return nil, nil, nil, nil, err
+	}
 	u, err := user.Current()
 	if err != nil {
-		return err
+		return nil, nil, nil, nil, err
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: Wrap these errors.

File: pkg/jx/cmd/get_applications.go [hunk 12]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
 	}
 	ns, _, err := kube.GetDevNamespace(kubeClient, currentNs)
 	if err != nil {
-		return err
+		return nil, nil, nil, nil, err
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: wrap?

File: pkg/jx/cmd/get_applications.go [hunk 13]
```diff
@@ -114,33 +116,116 @@ func NewCmdGetApplications(f Factory, in terminal.FileReader, out terminal.FileW
...
 	}
 	envList, err := client.JenkinsV1().Environments(ns).List(metav1.ListOptions{})
 	if err != nil {
-		return err
+		return nil, nil, nil, nil, err
```
Comment (ccojocar) [inline pkg/jx/cmd/get_applications.go]: wrap?

File: pkg/prow/config/branch_protection.go [hunk 14]
```diff
@@ -0,0 +1,106 @@
...
+
+// AddRepoToBranchProtection adds a repository to the Branch Protection section of a prow config
+func AddRepoToBranchProtection(bp *config.BranchProtection, repoSpec string, context string, kind Kind) error {
+	bp.ProtectTested = true
+	if bp.Orgs == nil {
+		bp.Orgs = make(map[string]config.Org, 0)
+	}
+	requiredOrg, requiredRepo, err := util.GetRemoteAndRepo(repoSpec)
+	if err != nil {
+		return err
```
Comment (ccojocar) [inline pkg/prow/config/branch_protection.go]: Wrap?

File: pkg/prow/config/branch_protection.go [hunk 15]
```diff
@@ -0,0 +1,106 @@
...
+
+// RemoveRepoFromBranchProtection adds a repository to the Branch Protection section of a prow config
+func RemoveRepoFromBranchProtection(bp *config.BranchProtection, repoSpec string) error {
+	if bp.Orgs == nil {
+		return errors.New("no orgs in BranchProtection object")
+	}
+	requiredOrg, requiredRepo, err := util.GetRemoteAndRepo(repoSpec)
+
+	if err != nil {
+		return err
```
Comment (ccojocar) [inline pkg/prow/config/branch_protection.go]: Wrap?

File: pkg/prow/config/branch_protection.go [hunk 16]
```diff
@@ -0,0 +1,106 @@
...
+	}
+	repos := bp.Orgs[requiredOrg].Repos
```
Comment (ccojocar) [inline pkg/prow/config/branch_protection.go]: check if the `requriedOrg` is in the `b.Orgs` before calling the `Repos` filed, this can lead to a crash if the value is no present in the map

File: pkg/prow/config/branch_protection.go [hunk 17]
```diff
@@ -0,0 +1,106 @@
...
+		prowRepo.RequiredStatusChecks = &config.ContextPolicy{}
+	}
+	return prowRepo.RequiredStatusChecks.Contexts, nil
+}
+
+func GetBranchProtectionContexts(org string, repo string, prowConfig *config.Config) ([]string, error) {
+	result := make([]string, 0)
+	contexts, err := GetAllBranchProtectionContexts(org, repo, prowConfig)
+	if err != nil {
+		return result, err
```
Comment (ccojocar) [inline pkg/prow/config/branch_protection.go]: wrap?

File: pkg/prow/config/tide.go [hunk 18]
```diff
@@ -0,0 +1,133 @@
...
+	"github.com/jenkins-x/jx/pkg/util"
+	"k8s.io/test-infra/prow/config"
+	"time"
+)
+
+// CreateTide creates a default Tide Config object
+func CreateTide() config.Tide {
+	// todo get the real URL, though we need to handle the multi cluster use case where dev namespace may be another cluster, so pass it in as an arg?
+	t := config.Tide{
+		TargetURL: "https://tide.foo.bar",
```
Comment (ccojocar) [inline pkg/prow/config/tide.go]: I would inject the `TargetURL` as an argument in the `CreateTide` function instead of hardcoding a dummy value here

File: pkg/prow/config/tide.go [hunk 19]
```diff
@@ -0,0 +1,133 @@
...
+	myFalse := false
+
+	t.SyncPeriod = time.Duration(30)
+	t.StatusUpdatePeriod = time.Duration(30)
+	t.ContextOptions = config.TideContextPolicyOptions{
+		TideContextPolicy: config.TideContextPolicy{
+			FromBranchProtection: &myTrue,
+			SkipUnknownContexts:  &myFalse,
+		},
+		//Orgs: orgPolicies,
```
Comment (ccojocar) [inline pkg/prow/config/tide.go]: Can this be removed?

File: pkg/prow/prow.go [hunk 20]
```diff
@@ -394,6 +267,37 @@ func (o *Options) AddProwConfig() error {
...
+		return errors.New("no existing prow config. Nothing to remove")
+	}
+	if err != nil {
+		return errors.Wrap(err, "getting existing prow config")
+	}
+
+	for _, repo := range o.Repos {
+		err = prowconfig.RemoveRepoFromTideConfig(&prowConfig.Tide, repo, o.Kind)
+		if err != nil {
+			return err
```
Comment (ccojocar) [inline pkg/prow/prow.go]: Wrap?

File: pkg/prow/prow.go [hunk 21]
```diff
@@ -394,6 +267,37 @@ func (o *Options) AddProwConfig() error {
...
+		}
+		err = prowconfig.RemoveRepoFromBranchProtection(&prowConfig.BranchProtection, repo)
+		if err != nil {
+			return err
```
Comment (ccojocar) [inline pkg/prow/prow.go]: Wrap?

File: pkg/prow/prow_test.go [hunk 22]
```diff
@@ -304,3 +326,26 @@ func TestGetPostSubmitJob(t *testing.T) {
 	assert.NotEmpty(t, job.Name, "job name is empty")
 	assert.Equal(t, "release", job.Name)
 }
+
+func getProwConfig(t *testing.T, o TestOptions) (*config.Config, error) {
+	cm, err := o.KubeClient.CoreV1().ConfigMaps(o.NS).Get(prow.ProwConfigMapName, metav1.GetOptions{})
+	assert.NoError(t, err)
+	prowConfig := &config.Config{}
+	yaml.Unmarshal([]byte(cm.Data[prow.ProwConfigFilename]), &prowConfig)
```
Comment (ccojocar) [inline pkg/prow/prow_test.go]: Maybe also check the error return by `Unmarshal`?

File: pkg/prow/prow_test.go [hunk 23]
```diff
@@ -304,3 +326,26 @@ func TestGetPostSubmitJob(t *testing.T) {
...
+	return prowConfig, err
+}
+
+func assertInPluginConfig(t *testing.T, prowConfig *config.Config, repo string, shouldBeInConfig bool) {
+	org, r, _ := util.GetRemoteAndRepo(repo)
```
Comment (ccojocar) [inline pkg/prow/prow_test.go]: Check the error also?

File: pkg/jx/cmd/get_applications.go (hunk 10 above)
Comment (agentgonzo) [reply pkg/jx/cmd/get_applications.go]: ditto

File: pkg/prow/config/branch_protection.go (hunk 16 above)
Comment (agentgonzo) [reply pkg/prow/config/branch_protection.go]: I ran through tests for that and it didn't crash. I'll put explicit tests in.

File: pkg/prow/config/tide.go (hunk 18 above)
Comment (agentgonzo) [reply pkg/prow/config/tide.go]: not my code. No idea why this is even here.

Comment (agentgonzo) [reply pkg/prow/config/tide.go]: I just moved the methods to a new package

**Comment by amuniz** [comment]
FTR `jx delete app` generated [this PR](https://github.com/cb-kubecd/amuniz-golang/pull/5) in a non environment repository (it's actually an app).
