### PR TITLE
fix: use the stream specified

### LINKED ISSUE #5059: Can't use latest release for version stream
### Summary 

Currently `jx boot` is using the latest release for the version stream, which makes little sense as it's a stream and tags aren't. Switch boot to use the stream.

### PR DESCRIPTION
**Pull request by pmuir**
Fixes #5059
Signed-off-by: Pete Muir <pmuir@bleepbleep.org.uk>

#### Submitter checklist

- [ ] Change is code complete and matches issue description.
- [ ] Change is covered by existing or new tests.

#### Which issue this PR fixes

fixes #

### CODE REVIEW

File: pkg/cmd/boot/boot.go [hunk 1]
```diff
@@ -219,6 +220,11 @@ func (o *BootOptions) Run() error {
 	}
 
 	requirements, requirementsFile, err := config.LoadRequirementsConfig(o.Dir)
+	if requirements.VersionStream.URL == "" && requirements.VersionStream.Ref == "" {
+		requirements.VersionStream.URL = o.VersionStreamURL
+		requirements.VersionStream.Ref = o.VersionStreamRef
+	}
```
Comment (cagiti) [inline pkg/cmd/boot/boot.go]: Does this introduce a cyclic dependency problem?
