### PR TITLE
fix: Adding clarity to git access error message

### LINKED ISSUE #5718: Wrong GitAccess better message
### Summary 

When we have this kind of error 
```
WARNING: Querying webhooks on enterprise/app-server: GET https://api.github.com/repos/enterprise/app-server/hooks: 404 Not Found []
Creating GitHub webhook for enterprise/app-server for url https://hook-for enterprise.domain.io/hook
error: POST https://api.github.com/repos/enterprise/app-server/hooks: 404 Not Found [] 
```

### Expected behavior

Display a better message to user to say that the account don't have the correct access.

### Kubernetes cluster

EKS 

### Operating system / Environment

```
NAME               VERSION
jx                 2.0.827
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0 (Apple Git-122)
Operating System   Mac OS X 10.14.6 build 18G103
```

### PR DESCRIPTION
**Pull request by nehagup**
fixes #5718

### CODE REVIEW

File: pkg/gits/github.go [hunk 1]
```diff
@@ -445,7 +445,13 @@ func (p *GitHubProvider) CreateWebHook(data *GitWebHookArguments) error {
 	}
 
 	log.Logger().Infof("Creating GitHub webhook for %s/%s for url %s", util.ColorInfo(owner), util.ColorInfo(repo), util.ColorInfo(webhookUrl))
-	_, _, err = p.Client.Repositories.CreateHook(p.Context, owner, repo, hook)
+	_, resp, err := p.Client.Repositories.CreateHook(p.Context, owner, repo, hook)
+	if err != nil {
+		if resp.StatusCode == 404 || resp.StatusCode == 403 {
+			log.Logger().Error("Permission denied")
```
Comment (ccojocar) [inline pkg/gits/github.go]: Why don't you wrap the error with a message in this case? 

```Go
errors.Wrap(err, "Permission denied")
```

an the let the caller the log the error

Comment (hferentschik) [reply pkg/gits/github.go]: That's more consistent with the rest of the code base.

Comment (hferentschik) [reply pkg/gits/github.go]: Maybe we can find a way to add a test as well? ;-)

Comment (nehagup) [reply pkg/gits/github.go]: Yes, seems better.

Comment (nehagup) [reply pkg/gits/github.go]: I'm keeping the statusCode just to make sure it appears only in case of 404 and 403.

File: pkg/gits/github.go [hunk 2]
```diff
@@ -445,7 +445,13 @@ func (p *GitHubProvider) CreateWebHook(data *GitWebHookArguments) error {
 	}
 
 	log.Logger().Infof("Creating GitHub webhook for %s/%s for url %s", util.ColorInfo(owner), util.ColorInfo(repo), util.ColorInfo(webhookUrl))
-	_, _, err = p.Client.Repositories.CreateHook(p.Context, owner, repo, hook)
+	_, resp, err := p.Client.Repositories.CreateHook(p.Context, owner, repo, hook)
+	if err != nil {
+		if resp.StatusCode == 404 || resp.StatusCode == 403 {
+			return errors.Wrap(err, "Permission denied")
```
Comment (hferentschik) [inline pkg/gits/github.go]: +1, maybe we can provide a bit more context `errors.Wrapf(err, "unable to create webhook for %s/%s - permission denied", owner, repo)`.
This way when you get the error you have a bit more context and you don't need to figure out what caused a 404.

Do you mind adding some tests as well?

Comment (nehagup) [reply pkg/gits/github.go]: Hey, @hferentschik how can I mock a Github provider for the test case?

Comment (hferentschik) [reply pkg/gits/github.go]: On the second thought, a `MockGitProvider` won't cut it here. You would need to create the `GitHubProvider` test instance and set its `Client` instance to something you can control, aka some test server from which you can return what you need/want (opposed to talking to GitHub directly).

The way to do this is shown here - https://github.com/google/go-github/blob/master/github/github_test.go#L34
You need this _setup_ function as a helper for your tests. It allows you to spin off an HTTP server for which you can control what requests to handle and how to respond. 

You can see how this is used here - https://github.com/google/go-github/blob/master/github/repos_hooks_test.go

I think it would make for a nice test and open the doors for better testing of `GitHubProvider`. Once the helper method is there we can write more tests using it.

WDYT, do you want to give it a go? Happy to help in case you need some help.

Comment (nehagup) [reply pkg/gits/github.go]: Sure, Can I please have another PR for that? It seems it may take some time to learn it.

**Comment by nehagup** [comment]
I'm not sure why this is failing, the build says : 

`k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found`

seems to be related to #1207

**Comment by hferentschik** [comment]
> Sure, Can I please have another PR for that? It seems it may take some time to learn it.

Fair enough, we can merge this PR and you can have a go at learning the test framework and adding a unit test for it. This will be a good exercise as well.

To merge it though, you first have to fix the Go formatting. We use and enforce the default Go formatting style and it seems that there is an issue with the change you made. You can run `make  fmt` locally and it should fix all formatting violations for you. IMO it is then the best to amend the existing commit and do a forced push to this pull request. Something along these lines:

```bash
$ make fmt
$ git add .
$ git commit --amend --no-edit 
$ git push -f <remote> HEAD
```

Once the linting issue is fixed, I'll merge the PR.

**Comment by hferentschik** [comment]
> I'm not sure why this is failing, the build says :

> k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid 
> pseudo-version: preceding tag (v2.0.0-alpha.0) not found

Where and how do you see this problem?

**Comment by nehagup** [comment]
> > I'm not sure why this is failing, the build says :
> 
> > k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid
> > pseudo-version: preceding tag (v2.0.0-alpha.0) not found
> 
> Where and how do you see this problem?

I get this on `make build`
Even on `make fmt` I get `go: k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found`

**Comment by hferentschik** [comment]
> I get this on make build
Even on make fmt I get go: k8s.io/client-go@v2.0.0-alpha.0.0.20190115164855-701b91367003+incompatible: invalid pseudo-version: preceding tag (v2.0.0-alpha.0) not found

Which version of Go are you using?

**Comment by nehagup** [comment]
I was using 1.13.x . 
Thanks!
