### PR TITLE
fix: Resolve OWNERS merge conflicts in boot upgrade with existing version

### LINKED ISSUE #6543: jx boot upgrade replaces OWNERS with OWNERS from jenkins-x-boot-config
### Summary

Forked repo's `OWNERS` configuration is replaced with the `OWNERS` configuration from the `jenkins-x-boot-config` repository during an upgrade from `v1.0.69` to `v1.0.71` with the commit: "chore: exclude files from upgrade" (i.e. https://github.com/yields-io/environment-k8s-dev/pull/5).

### Steps to reproduce the behavior

Upgrade environment using `jx upgrade boot`.

### Expected behavior

`OWNERS` file created with the values from the `jx-requirements.yml` > `devEnvApprovers` during the initial `jx boot` shouldn't be touched during an upgrade.

### Actual behavior

`OWNERS` file is replaced with the `OWNERS` file from the `jenkins-x-boot-config` repository. I'm currently not an approver / reviewer in the `jenkins-x-boot-config` repository hence I can't approve the PR created for the upgrade nor would I want to given the `OWNERS` modifications. Similar to [this issue](https://github.com/jenkins-x/jx/issues/5035): "This results in these jx devs having a high prow privileges on other peoples dev environments."

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1123
Kubernetes cluster v1.15.4-gke.22
kubectl            v1.17.0
helm client        Client: v2.13.1+g618447c
git                2.17.1
Operating System   Ubuntu 18.04.3 LTS
```

### Jenkins type

- [X] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### Kubernetes cluster

GKE: `jx create cluster gke --skip-installation --cluster-name k8s`

### Operating system / Environment

Ubuntu 18.04

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Realized this was an issue while thinking about #6465 - we don't commit changes to `OWNERS` from upstream when running `jx upgrade boot`, but we still will hit merge conflicts when cherry-picking if `OWNERS` has changed in both the dev env repo and upstream, so let's use a custom merge driver to ensure that all conflicts for `OWNERS` are automatically resolved in favor of the existing version in the dev env repo, as described in https://stackoverflow.com/a/930495

#### Special notes for the reviewer(s)

I still need to write a unit test for this.

#### Which issue this PR fixes

fixes #6543

### CODE REVIEW

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 1]
```diff
@@ -399,14 +466,13 @@ func (o *UpgradeBootOptions) setupGitConfig(dir string) error {
...
 
 func (o *UpgradeBootOptions) excludeFiles(commit string) error {
-	excludedFiles := []string{"OWNERS"}
-	err := o.Git().CheckoutCommitFiles(o.Dir, commit, excludedFiles)
+	err := o.Git().CheckoutCommitFiles(o.Dir, commit, filesExcludedFromCherryPick)
 	if err != nil {
 		return errors.Wrap(err, "failed to checkout files")
 	}
-	err = o.Git().AddCommitFiles(o.Dir, "chore: exclude files from upgrade", excludedFiles)
+	err = o.Git().AddCommitFiles(o.Dir, "chore: exclude files from upgrade", filesExcludedFromCherryPick)
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: I really have a bad feeling about this. Can we not just get rid of cherry-picking altogether?

Comment (abayer) [reply pkg/cmd/upgrade/upgrade_boot.go]: I just want to fix this one thing with `OWNERS` here and defer the root-and-branch work til later. =)

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 2]
```diff
@@ -312,14 +320,69 @@ func (o *UpgradeBootOptions) updateBootConfig(versionStreamURL string, versionSt
...
 		return errors.Wrap(err, "failed to cherry pick upgrade commits")
 	}
-	err = o.excludeFiles(currentSha)
+	return nil
+}
+
+func (o *UpgradeBootOptions) configureGitMergeExcludes() error {
+	gitConfigFile := filepath.Join(o.Dir, ".git", "config")
+	var existingGitConfig string
+	gcExists, err := util.FileExists(gitConfigFile)
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: hmm, should that not go through the gitter really using the `git config` command? See also https://github.com/jenkins-x/jx/pull/6572/files#diff-ea63bc4be56a5cd0bf52d8031a36cefcR179

not sure whether it is a good idea to just append this line? Can that never conflict with existing sections?

Comment (abayer) [reply pkg/cmd/upgrade/upgrade_boot.go]: Yeah, I'd be happy to change that to use `git config`. Will do!

Comment (abayer) [reply pkg/cmd/upgrade/upgrade_boot.go]: I'm waiting on #6572 to get in first, since it seems silly to call `git config` directly when you're about to add a helper function for exactly that.

**Comment by abayer** [comment]
/hold cancel

@hferentschik - updated!

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 3]
```diff
@@ -312,14 +318,55 @@ func (o *UpgradeBootOptions) updateBootConfig(versionStreamURL string, versionSt
...
+		existingGitAttr = string(gaBytes)
+	}
+
+	// Write the existing .git/info/attributes content and marking the selected files as using our custom driver
+	gitAttrContent := existingGitAttr + "\n"
+	for _, excludedFile := range filesExcludedFromCherryPick {
+		gitAttrContent += fmt.Sprintf("%s merge=%s\n", excludedFile, keepDevEnvKey)
+	}
+
+	err = ioutil.WriteFile(gitAttrFile, []byte(gitAttrContent), util.DefaultFileWritePermissions)
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: Don't you have to unset this as well after the upgrade? You only want the custom merge driver during `upgrade boot` right? Afterwards, the normal git workflow should apply, right? Does your change now not mean that merging is off for regular evolution of the dev repo?

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 4]
```diff
@@ -312,14 +318,55 @@ func (o *UpgradeBootOptions) updateBootConfig(versionStreamURL string, versionSt
...
+	err := o.Git().Config(o.Dir, "--local", fmt.Sprintf("merge.%s.name", keepDevEnvKey), keepDevEnvDriverName)
+	if err != nil {
+		return errors.Wrapf(err, "configuring name for exclude merge driver in %s", o.Dir)
+	}
+	err = o.Git().Config(o.Dir, "--local", fmt.Sprintf("merge.%s.driver", keepDevEnvKey), "true")
+	if err != nil {
+		return errors.Wrapf(err, "configuring driver for exclude merge driver in %s", o.Dir)
+	}
+
+	// Read the existing .git/info/attributes if it exists
```
[the remark this answers is not in the document]
Comment (abayer) [reply pkg/cmd/upgrade/upgrade_boot.go]: I'd say no for two reasons: this is the only place we're doing it currently, and `gitter` feels to me like it should only be for `git` commands, and this isn't that.

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 5]
```diff
@@ -312,13 +318,101 @@ func (o *UpgradeBootOptions) updateBootConfig(versionStreamURL string, versionSt
...
+
+	err = o.removeMergeExcludesFromAttributes()
+	if err != nil {
+		return errors.Wrapf(err, "removing special handling of files to exclude from merging from upstream")
+	}
+	return nil
+}
+
+// Add a custom merge driver to .git/config that will always choose the current version when there's a change upstream
+// in selected files, and use that merge driver in .git/info/attributes for those selected files.
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: thanks :-)

File: pkg/cmd/upgrade/upgrade_boot.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/cmd/upgrade/upgrade_boot.go]: > I'd say no for two reasons: this is the only place we're doing it currently,

right, but say someone else needs to do the same, where would he naturally be looking for it?

> gitter feels to me like it should only be for git commands, and this isn't that.

It is already more than pure git command execution. There are functions in there already dealing with .git internas. 
But since you feel so strongly about it, I resy my case.

[the remark this answers is not in the document]
Comment (abayer) [reply pkg/cmd/upgrade/upgrade_boot.go]: I also can't think of a good abstraction, but lemme try to bang something out.

[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/cmd/upgrade/upgrade_boot.go]: btw, another argument for moving it would be to write some tests for it in the gitter area.

File: pkg/cmd/upgrade/upgrade_boot.go [hunk 6]
```diff
@@ -312,13 +318,101 @@ func (o *UpgradeBootOptions) updateBootConfig(versionStreamURL string, versionSt
...
+		return errors.Wrapf(err, "configuring files (%s) to always use existing version when conflicting with upstream", strings.Join(filesExcludedFromCherryPick, ", "))
+	}
+
 	err = o.cherryPickCommits(configCloneDir, currentSha, upgradeSha)
 	if err != nil {
 		return errors.Wrap(err, "failed to cherry pick upgrade commits")
 	}
-	err = o.excludeFiles(currentSha)
+
+	err = o.removeMergeExcludesFromAttributes()
```
Comment (hferentschik) [inline pkg/cmd/upgrade/upgrade_boot.go]: this needs to happen in a defer, otherwise the cleanup is not happening if a cherry-pick error occurs.

File: pkg/gits/git_local.go [hunk 7]
```diff
@@ -538,3 +538,13 @@ func (g *GitLocal) Describe(dir string, contains bool, commitish string, abbrev
 func (g *GitLocal) IsAncestor(dir string, possibleAncestor string, commitish string) (bool, error) {
 	return g.GitCLI.IsAncestor(dir, possibleAncestor, commitish)
 }
+
+// WriteRepoAttributes writes the given content to .git/info/attributes
+func (g *GitLocal) WriteRepoAttributes(dir string, content string) error {
+	return g.GitCLI.WriteRepoAttributes(dir, content)
```
Comment (hferentschik) [inline pkg/gits/git_local.go]: This git_local impl is really a special beast. IMO we shot ourselves into the foot with this one.

File: pkg/gits/git_cli.go [hunk 8]
```diff
@@ -1263,3 +1263,32 @@ func (g *GitCLI) IsAncestor(dir string, possibleAncestor string, commitish strin
...
+
+	err := ioutil.WriteFile(gitAttrFile, []byte(content), util.DefaultFileWritePermissions)
+	if err != nil {
+		return errors.Wrapf(err, "writing new repo-local git attributes to %s", gitAttrFile)
+	}
+	return nil
+}
+
+// ReadRepoAttributes reads the existing content, if any, in .git/info/attributes
+func (g *GitCLI) ReadRepoAttributes(dir string) (string, error) {
```
Comment (hferentschik) [inline pkg/gits/git_cli.go]: 👍

File: pkg/gits/git_cli.go [hunk 9]
```diff
@@ -1263,3 +1263,32 @@ func (g *GitCLI) IsAncestor(dir string, possibleAncestor string, commitish strin
 	// Default case is that this is an ancestor, since there's no error from the merge-base call.
 	return true, nil
 }
+
+// WriteRepoAttributes writes the given content to .git/info/attributes
+func (g *GitCLI) WriteRepoAttributes(dir string, content string) error {
```
Comment (hferentschik) [inline pkg/gits/git_cli.go]: 👍
