### PR TITLE
fix: broken tls in jx preview

### LINKED ISSUE #2196: TLS is broken in jx preview
### Summary 

deploying a preview environment with TLS through `jx preview` doesn't work: the ingress is setup with http and not https

### Steps to reproduce the behavior

- `jx preview --tls-acme="true"` -> `tls-acme` is still `false` in the `exposecontroller` configmap
- setting `expose.config.tlsacme: true` in preview's chart `values.yaml` -> `tls-acme` is still `false` in the `exposecontroller` configmap

### Jx version

The output of `jx version` is:

```
Using helmBinary helm with feature flag: none
NAME               VERSION
jx                 1.3.519
jenkins x platform 0.0.2267
Kubernetes cluster v1.10.7-gke.6
kubectl            v1.12.2
helm client        v2.11.0+g2e55dbe
helm server        v2.11.0+g2e55dbe
git                git version 2.8.4
```

### Kubernetes cluster

GKE, created with `jx create cluster`

### Operating system / Environment

`jx preview` cmd executed in the `jenkinsxio/builder-base:0.1.58` image, in a kubernetes pod, through a Jenkinsfile

### Expected behavior

the `exposecontroller` configmap created by the `jx preview` command has `tls-acme: true`, and the ingress is exposed through https and not http

### Actual behavior

the `exposecontroller` configmap created by the `jx preview` command has `tls-acme: false`, and the ingress is exposed through http and not https

### PR DESCRIPTION
**Pull request by vbehar**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

TLS was broken in `jx preview` because:
- the `omitempty` json tag was missing from the ExposeControllerConfig struct, which resulted in empty values being present in the extraValues.yaml file - thus overriding valid values from the values.yaml file
- the cmdline flags passed through `jx preview` for the ExposeControllerConfig struct were not used to generate the extraValues.yaml file
- ths `tls-acme` flag's default value was `"false"`, which was not an empty value, and thus was overriding the value from the values.yaml file. If we use the empty string as default value, it will still default to false in the exposecontroller, while allowing the values.yaml file from the preview chart to enable TLS

#### Special notes for the reviewer(s)

I've created a new func to build the PreviewValuesConfig, so that I can unit test it - making sure values from the PreviewOptions ends up in the PreviewValuesConfig

#### Which issue this PR fixes

fixes #2196

### CODE REVIEW

**Comment by vbehar** [comment]
I'm also adding missing `omitempty` tags, so that empty values won't override default values from the values.yaml file

File: pkg/jx/cmd/preview.go [hunk 1]
```diff
@@ -432,18 +432,15 @@ func (o *PreviewOptions) Run() error {
 	}
 
 	values := config.PreviewValuesConfig{
-		ExposeController: &config.ExposeController{
-			Config: config.ExposeControllerConfig{
-				Domain: domain,
-			},
-		},
+		ExposeController: o.HelmValuesConfig.ExposeController,
```
Comment (ccojocar) [inline pkg/jx/cmd/preview.go]: `ExposeController` can be `nil` in the `HelmValueConfig`. Please could you add a check for this? It would be great if you could add a small test for this scenario.

**Comment by vbehar** [comment]
@ccojocar hi, sorry about the long time to fix this. I checked for nil and added a unit test, and also rebased on master

**Comment by vbehar** [comment]
@ccojocar @jstrachan Hi, can you please help me understand why the test is failing ? It's a little hard to get information ;-)

I tried to run `make docker-test` locally, and the promote tests fail, but it's because of some missing ctx on my end (`unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`). If I skip the promote tests, everything works.

thanks

**Comment by jstrachan** [comment]
@vbehar looks like the bdd tests issue is related to the BDD tests stuff (`jx step bdd`) and nothing to do with your PR - am investigating...

**Comment by vbehar** [comment]
ok thanks!

**Comment by jstrachan** [comment]
@vbehar so it looks like these changes break the BDD tests as when running the BDD tests with this build we get:
```
 ./build/linux/jx step bdd -b --provider=gke --git-provider=ghe --git-provider-url=https://github.beescloud.com --git-username **** --git-api-token **** --default-****-password **** --no-delete-app --no-delete-repo --tests install --tests test-create-spring
Warning failed to load version: No Major.Minor.Patch elements found
Creating team bdd-ghe-jx-pr-2129-17
Namespace bdd-ghe-jx-pr-2129-17 created
 Updated the team settings in namespace bdd-ghe-jx-pr-2129-17
Storing the kubernetes provider gke in the TeamSettings
Updated the team settings in namespace bdd-ghe-jx-pr-2129-17
Enabling helm template mode in the TeamSettings
Updated the team settings in namespace bdd-ghe-jx-pr-2129-17
Git configured for user: JenkinsXBot and email jenkins-x@googlegroups.com
Using helm2
Skipping tiller
Updated the team settings in namespace bdd-ghe-jx-pr-2129-17
helm installed and configured
Updated the team settings in namespace bdd-ghe-jx-pr-2129-17
existing ingress controller found, no need to install a new one
Waiting for external loadbalancer to be created and update the nginx-ingress-controller service in kube-system namespace
Note: this loadbalancer will fail to be provisioned if you have insufficient quotas, this can happen easily on a GKE free account. To view quotas run: gcloud compute project-info describe
External loadbalancer created
Waiting to find the external host name of the ingress controller Service in namespace kube-system with name jxing-nginx-ingress-controller
No domain flag provided so using default 104.155.31.11.nip.io to generate Ingress rules
nginx ingress controller installed and configured
Saving Git token configuration for server https://github.beescloud.com and user name ****.
Cloning the Jenkins X cloud environments repo to /builder/home/.jx/cloud-environments
Cloning the Jenkins X cloud environments repo to /builder/home/.jx/cloud-environments
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Compressing objects: 100% (8/8), done.
Total 1219 (delta 2), reused 4 (delta 1), pack-reused 1210
Creating Secret jx-install-config in namespace bdd-ghe-jx-pr-2129-17
Generated helm values /builder/home/.jx/extraValues.yaml
Installing Jenkins X platform helm chart from: /builder/home/.jx/cloud-environments/env-gke
Using local value overrides file /home/jenkins/go/src/github.com/jenkins-x/jx/myvalues.yaml
Installing jx into namespace bdd-ghe-jx-pr-2129-17
error: Failed to install team bdd-ghe-jx-pr-2129-17: failed to parse TLS exposecontroller boolean strconv.ParseBool: parsing "": invalid syntax
```

so it looks like we'll need to fix the BDD tests + the jenkins X installer to handle blank values for `ExposeControllerConfig`

**Comment by jstrachan** [comment]
@vbehar I fixed the parsing if blank strings so the rebase worked in the BDD tests

**Comment by vbehar** [comment]
great, thanks @jstrachan !
