### PR TITLE
fix: Gitlab (12?) namespace should use path in GitRepository

### LINKED ISSUE #7181: Gitlab (12?) namespace should use path in GitRepository
There appears to be a typo and `GitRepository` should be using `path` instead of `Name`. Creating PRs with [Gitlab user kind namespaces](https://docs.gitlab.com/ee/api/namespaces.html) `404` fails for me otherwise:

```
error: failed to create Pull Request on the development environment git repository `https://***git`: unable to create pull request: failed to create PR for base master and head branch bump-resource-version-75be7a50-9467-11ea-8f26-a44cc83868d9 from temp dir /tmp/create-pr135132813: finding existing PRs using filter updatebot on repo Steffan, Andreas/***: listing open pull requests on Steffan, Andreas/*: GET https://***/api/v4/users/Steffan, Andreas/projects: 404 {message: 404 User Not Found}
```
In my case, `Name` resolves to my full name `Steffan, Andreas`.

### PR DESCRIPTION
**Pull request by deas**
There appears to be a typo and `GitRepository` should be using `path` instead of `Name`. Creating PRs with [Gitlab user kind namespaces](https://docs.gitlab.com/ee/api/namespaces.html) `404` fails for me otherwise:

```
error: failed to create Pull Request on the development environment git repository `https://***git`: unable to create pull request: failed to create PR for base master and head branch bump-resource-version-75be7a50-9467-11ea-8f26-a44cc83868d9 from temp dir /tmp/create-pr135132813: finding existing PRs using filter updatebot on repo Steffan, Andreas/***: listing open pull requests on Steffan, Andreas/*: GET https://***/api/v4/users/Steffan, Andreas/projects: 404 {message: 404 User Not Found}
```
In my case, `Name` resolves to my full name `Steffan, Andreas`. 

fixes #7181

### CODE REVIEW

File: pkg/gits/gitlab.go [hunk 1]
```diff
@@ -123,7 +123,7 @@ func GetOwnerNamespaceID(g *gitlab.Client, owner string) (int, error) {
 func fromGitlabProject(p *gitlab.Project) *GitRepository {
 	org := ""
 	if p.Namespace != nil {
-		org = p.Namespace.Name
+		org = p.Namespace.Path
```
Comment (hferentschik) [inline pkg/gits/gitlab.go:126]: @abayer - that might be up your alley. WDYT?

**Comment by hferentschik** [comment]
@deas, thanks for the pull request. Much appreciated. Do you mind to create an issue as well and referencing it from this pull request? Makes things easier to track in terms of changelogs etc...

**Comment by deas** [comment]
> @deas, thanks for the pull request. Much appreciated. Do you mind to create an issue as well and referencing it from this pull request? Makes things easier to track in terms of changelogs etc...

You're welcome.

Created the issue and referenced it from the commit.

**Comment by abayer** [comment]
/lgtm

This matches what we’re doing in go-scm, so yeah, seems right to me.
