### PR TITLE
fix: Handling of completion of metapipeline in build controller was flawed

### LINKED ISSUE #5395: controllerbuild sporadically loses watch on pods with metapipeline enabled
Haven't nailed this down exactly, but `controllerbuild` seems to go silent sporadically with metapipeline enabled. We've seen this in the Lighthouse BDD tests and multiple times in the most recent attempt to turn metapipeline on for prod, so I don't think it's a coincidence.

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

This fixes a number of inconsistencies/shoddy logic/odd behavior around how metapipelines are handled in `controller_build`. First, we weren't properly detecting the `PipelineRun` type due to using the wrong prefix, which was dumb on my part. =) That on its own led to us assuming the `PipelineActivity` was complete as soon as the metapipeline finished, which led us down code paths that result in #5395. Additionally, we weren't consistent with our `PipelineRunInfo` names, which may not have been a functional bug, but was definitely a logging bug that made it hard for me to figure out what was going on.

Along the way, I realized that even with those things dealt with, we still ended up processing the metapipeline's pod, albeit after the completion of the generated pipeline, so it didn't actually do anything, but that's still annoying, so I've fixed the logic for deciding whether to call `logJobCompleteState` and try to populate the long-term storage logs URL, etc to be smarter about how to handle metapipeline.

Oh, and we weren't actually using the image we just built in the `jenkins-x-controllerbuild` pod in the Tekton BDD tests, which took me a couple runs to realize, so let's do that.

#### Which issue this PR fixes

fixes #5395

### CODE REVIEW

File: pkg/tekton/pipeline_info.go [hunk 1]
```diff
@@ -151,7 +151,7 @@ func CreatePipelineRunInfo(prName string, podList *corev1.PodList, ps *v1.Pipeli
 		CreatedTime: pr.CreationTimestamp.Time,
 	}
 
-	if strings.HasPrefix(pr.Name, "metapipeline-") {
+	if strings.HasPrefix(pr.Name, MetaPipeline.String() + "-") {
```
Comment (hferentschik) [inline pkg/tekton/pipeline_info.go]: +1, definitely a bug. Any idea how this would manifest itself in the controller at least seemingly not making any progress?

Comment (abayer) [reply pkg/tekton/pipeline_info.go]: Trying to figure that out now. =) https://github.com/jenkins-x/jx/blob/e820d616812cc33dd41859c8fd7e4489f809f017/pkg/cmd/controller/controller_build.go#L1066 is the next line I'm sure should be logged after https://github.com/jenkins-x/jx/blob/e820d616812cc33dd41859c8fd7e4489f809f017/pkg/cmd/controller/controller_build.go#L729, the last line we do see, so something must be going wrong between those.

**Comment by abayer** [comment]
Current thinking is that `tekton.GetRunningBuildLogs` is hanging in some race condition around completion of the metapipeline and starting of the generated pipeline.

File: pkg/tekton/pipeline_info.go (hunk 1 above)
Comment (ccojocar) [reply pkg/tekton/pipeline_info.go]: Shouldn't you add the pipeline type also as a label into the PipelienRun? Encoding it into the name seems a bit fragile to me.

**Comment by hferentschik** [comment]
> Current thinking is that tekton.GetRunningBuildLogs is hanging in some race condition around completion of the metapipeline and starting of the generated pipeline.

My prime candidate as well, since this is the only place where we make use of go routines and where I could see the observed behaviour happening if the log streaming channel does not get closed properly.

**Comment by abayer** [comment]
Note that this is still messy - depending on how my afternoon goes, I may rewrite more of the logic in `updatePipelineActivityForRun` here. Otherwise, I'll open an issue to refactor it down the road.

**Comment by abayer** [comment]
Also, fwiw, I think there's a good chance that the proximate cause of #5395 is some combination of trying to collect build logs for long term storage after the metapipeline finishes but before the generated pipeline has actually spun up its pod completely, specifically when using buckets for the storage, since it has never showed up in tests, but BDD tests are using GitHub pages. Regardless, it's a path we won't cross again now.

**Comment by abayer** [comment]
Putting back on hold until I write unit tests for `ControllerBuildOptions.onPipelinePod`. Which I will do my best to get done today.

**Comment by abayer** [comment]
Ok, some `onPipelinePod` unit tests added.
