### PR TITLE
fix: changed a variable that was needed to do a shallow clone on step…

### LINKED ISSUE #4071: Error when attempting a shallow clone on a job running in `step_create_task`
### Summary 
There is currently an error when trying to execute a new build for an application.
When attempting to do a shallow clone of the repository, it fails with: 

```
"level":"warning","msg":"\nretrying after error:failed to fetch [master] from https://github.com/<org>/<repo>.git in directory /tmp/git871271591: git output: fatal: couldn't find remote ref master\nfatal: the remote end hung up unexpectedly: failed to run 'git fetch origin --depth=1 master' command in directory '/tmp/git871271591', output: 'fatal: couldn't find remote ref master\nfatal: the remote end hung up unexpectedly'\n\n","time":"2019-05-23T18:24:24Z"}
```

### Steps to reproduce the behavior

It's currently a dev only issue as I'm overriding the builder images with the current master code.

### Expected behavior
It should do the shallow clone without problems.

- [X] Next Generation (Tekton + Prow)
- [ ] Classic Jenkins
- [ ] Serverless Jenkins (JenkinsFileRunner + Prow)

### PR DESCRIPTION
**Pull request by dgozalo**
…_create_task

#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
There's a bug in `step_create_task` when attempting a shallow clone, it's setting the remote to the git temp folder so it fails to do a shallow clone later.

#### Which issue this PR fixes

fixes #4071

### CODE REVIEW

File: pkg/jx/cmd/step_create_task.go [hunk 1]
```diff
@@ -1107,7 +1107,7 @@ func (o *StepCreateTaskOptions) cloneGitRepositoryToTempDir(gitURL string, branc
 		if o.Verbose {
 			log.Infof("ran git init in %s", tmpDir)
 		}
-		err = o.Git().AddRemote(tmpDir, "origin", tmpDir)
+		err = o.Git().AddRemote(tmpDir, "origin", gitURL)
```
Comment (hferentschik) [inline pkg/jx/cmd/step_create_task.go]: 👍
