### PR TITLE
Fixes the upgrade app command so it doesn't ask for already answered configuration questions

### LINKED ISSUE #3673: jx upgrade app is asking all questions when used with gitops
### Summary 

When running `jx upgrade app` with a gitops cluster, all questions are asked

### Steps to reproduce the behavior

1. run `jx add app jx-app-datadog --version=0.0.1` and then wait for the pr to merge
2. run `jx upgrade app jx-app-datadog --version=0.0.2` and all questions are asked

### Expected behavior

Just ask the new question (the one for the site thingy)

### PR DESCRIPTION
**Pull request by dgozalo**
#### Submitter checklist

- [X] Change is code complete and matches issue description.
- [X] Change is covered by existing or new tests.

#### Description
Fixes the behavior that happened after upgrading an app that had configuration questions. 
The questions were being asked again because the CLI wasn't able to find the distribution's `values.yaml` file containing all already provided answers and was only finding the main chart's yaml file.

It will now look into the dependencies in the `requirements.yaml` file and attempt to find a valid `values.yaml` in the composed path. It will warn the user if it's unable to find a values.file.

#### Which issue this PR fixes

fixes #3673

### CODE REVIEW

File: pkg/environments/gitops.go [hunk 1]
```diff
@@ -233,6 +237,30 @@ func ModifyChartFiles(dir string, details *PullRequestDetails, modifyFn ModifyCh
...
+func mergeNestedAppsValues(dir string, dependencies []*helm.Dependency, values map[string]interface{}) {
+	for _, dep := range dependencies {
+		if dep.Name != "jenkins-x-platform" {
+			valuesFilePath := filepath.Join(dir, dep.Name)
+			valuesFile, err := helm.FindValuesFileName(valuesFilePath)
+			if err != nil {
+				valuesFilePath = filepath.Join(dir, helm.DefaultEnvironmentChartDir, dep.Name)
+				valuesFile, err = helm.FindValuesFileName(valuesFilePath)
+				if err != nil {
+					log.Warnf("Unable to find the values.yaml file in path: %s", valuesFilePath)
```
Comment (pmuir) [inline pkg/environments/gitops.go]: Normally you want to return the error rather than log it
