### PR TITLE
fix: Switch to building with go 1.13

### LINKED ISSUE #6484: Update the Go version to 1.13.x (1.13.5) in the build and builders
### Summary 
It seems that jx builds now with Go version `1.13.5`. We should update the Go version in the build and all builders.

```
$ake build
CGO_ENABLED=0 GO111MODULE=on go build -ldflags " -X github.com/jenkins-x/jx/pkg/version.Version=2.0.399-dev+d8d557a82 -X github.com/jenkins-x/jx/pkg/version.Revision='d8d557a82' -X github.com/jenkins-x/jx/pkg/version.Branch='master' -X github.com/jenkins-x/jx/pkg/version.BuildDate='20200110-10:48:49' -X github.com/jenkins-x/jx/pkg/version.GoVersion='1.13.5' """ -o build/jx cmd/jx/jx.go

$ build/jx version
NAME               VERSION
jx                 2.0.399-dev+d8d557a82
Kubernetes cluster v1.13.12-gke.8
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.21.0 (Apple Git-122.2)
Operating System   Mac OS X 10.15.2 build 19C57


verifying packages

WARNING: jx version 2.0.721 is available in the version stream. We highly recommend you upgrade to it.

? Would you like to upgrade to the jx version? No

WARNING: could not find a stable package version for git from /Users/cosmin/.jx/jenkins-x-versions
For background see: https://jenkins-x.io/docs/concepts/version-stream/
Please lock this version down via the command: jx step create pr versions -k package -n git
```
### Jx version

The output of `jx version` is:

```
COPY OUTPUT HERE
```

### Jenkins type

- [x ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Switch to building with go 1.13.

This will depend on https://github.com/jenkins-x/jenkins-x-builders/pull/1250 (there's a temp commit in here right now to use a builder image from that PR in the `integration` context).

#### Which issue this PR fixes

fixes #6484

### CODE REVIEW

**Comment by abayer** [comment]
Integration test failure:

```
=== Failed
=== FAIL: pkg/gits TestChangelogMarkdown (0.00s)
    commits_integration_test.go:48:
        	Error Trace:	commits_integration_test.go:48
        	Error:      	Not equal:
        	            	expected: "## Changes\n\n* some commit 1 ([jstrachan](https://github.com/jstrachan))\n* some commit 2 ([rawlingsj](https://github.com/rawlingsj))\n"
        	            	actual  : "## Changes\n"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,4 +2 @@

        	            	-* some commit 1 ([jstrachan](https://github.com/jstrachan))
        	            	-* some commit 2 ([rawlingsj](https://github.com/rawlingsj))
        	            	-
        	Test:       	TestChangelogMarkdown

=== FAIL: pkg/gits TestChangelogMarkdownWithConventionalCommits (0.00s)
    commits_integration_test.go:114:
        	Error Trace:	commits_integration_test.go:114
        	Error:      	Not equal:
        	            	expected: "## Changes\n\n### New Features\n\n* some commit 2 ([rawlingsj](https://github.com/rawlingsj))\n* has actual feature name: some commit 3 ([rawlingsj](https://github.com/rawlingsj))\n\n### Bug Fixes\n\n* some commit 1 ([jstrachan](https://github.com/jstrachan))\n\n### Other Changes\n\nThese commits did not use [Conventional Commits](https://conventionalcommits.org/) formatted messages:\n\n* bad comment 4 ([rawlingsj](https://github.com/rawlingsj))\n"
        	            	actual  : "## Changes\n\n### New Features\n\n* some commit 2 ([rawlingsj](https://github.com/rawlingsj))\n* has actual feature name: some commit 3 ([rawlingsj](https://github.com/rawlingsj))\n"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -7,11 +7 @@

        	            	-### Bug Fixes
        	            	-
        	            	-* some commit 1 ([jstrachan](https://github.com/jstrachan))
        	            	-
        	            	-### Other Changes
        	            	-
        	            	-These commits did not use [Conventional Commits](https://conventionalcommits.org/) formatted messages:
        	            	-
        	            	-* bad comment 4 ([rawlingsj](https://github.com/rawlingsj))
        	            	-
        	Test:       	TestChangelogMarkdownWithConventionalCommits


DONE 64 tests, 4 skipped, 2 failures in 505.203s
make: *** [test-slow-integration] Error 1
```

I noticed some problems when I tried to reproduce this on a docker container regarding `github.com/antham/chyle`'s dependency on `github.com/spf13/cobra`, and since `chyle` is part of the changelog generation logic, I'm wondering if there's a connection there. That said, I can't reproduce this locally or (once I cheated around the dependency problem by adding a `replace github.com/spf13/cobra => github.com/spf13/cobra v0.0.5` to `go.mod` so that I could build in the first place) on the container using the `builder-go-maven` image from https://github.com/jenkins-x/jenkins-x-builders/pull/1250.

**Comment by abayer** [comment]
And here's the `lint` error:

```
RUN make generate-docs
Generating HTML docs for Kubernetes Clients
./build/codegen --generator-version 9642bd3f4de5 docs
time="2020-04-06T19:11:47Z" level=info msg="generating docs to /workspace/go/src/github.com/jenkins-x/jx/docs/apidocs\n" app=codegen
time="2020-04-06T19:11:47Z" level=info msg="installing github.com/kubernetes-incubator/reference-docs/gen-apidocs in version 9642bd3f4de5 via 'go get'" app=codegen
error running go get -u github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5, output go: finding github.com 9642bd3f4de5
go: finding github.com/kubernetes-incubator/reference-docs 9642bd3f4de5
go: finding github.com/kubernetes-incubator 9642bd3f4de5
go: finding github.com/kubernetes-incubator/reference-docs/gen-apidocs 9642bd3f4de5
go: downloading github.com/kubernetes-incubator/reference-docs v0.0.0-20190410022412-9642bd3f4de5
go: extracting github.com/kubernetes-incubator/reference-docs v0.0.0-20190410022412-9642bd3f4de5
go get github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5: github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5: invalid version: reading http://jenkins-x-athens-proxy/github.com/kubernetes-incubator/reference-docs/gen-apidocs/@v/9642bd3f4de5.info: 500 Internal Server Error: failed to run 'go get -u github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5' command in directory '', output: 'go: finding github.com 9642bd3f4de5
go: finding github.com/kubernetes-incubator/reference-docs 9642bd3f4de5
go: finding github.com/kubernetes-incubator 9642bd3f4de5
go: finding github.com/kubernetes-incubator/reference-docs/gen-apidocs 9642bd3f4de5
go: downloading github.com/kubernetes-incubator/reference-docs v0.0.0-20190410022412-9642bd3f4de5
go: extracting github.com/kubernetes-incubator/reference-docs v0.0.0-20190410022412-9642bd3f4de5
go get github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5: github.com/kubernetes-incubator/reference-docs/gen-apidocs@9642bd3f4de5: invalid version: reading http://jenkins-x-athens-proxy/github.com/kubernetes-incubator/reference-docs/gen-apidocs/@v/9642bd3f4de5.info: 500 Internal Server Error'
make: *** [Makefile.codegen:49: generate-docs] Error 1
FAILED make generate-docs
```

I fixed an earlier similar one with `goimports` in https://github.com/jenkins-x/jx/pull/7025/commits/1e3e18816c6aba9b17488326595e41bb6bc097a6, but an attempt to do the same thing here just broke stuff further, because our `gen-apidocs` logic expects the dependency to be fetched with `GO111MODULE=on`. I _think_ we may need to update athens - see https://github.com/gomods/athens/issues/1372.

**Comment by abayer** [comment]
I opened https://github.com/jenkins-x-apps/jx-app-athens/pull/5 to bump our Athens app.

File: hack/generate.sh [hunk 1]
```diff
@@ -6,11 +6,6 @@ RED='\033[0;31m'
 GREEN='\033[0;32m'
 RESET='\033[0m'
 
-if ! [ -x "$(command -v goimports)" ]; then
```
Comment (hferentschik) [inline hack/generate.sh:9]: ooi, what did this do and why is it obsolete?

File: jenkins-x-integration.yml [hunk 2]
```diff
@@ -49,14 +49,14 @@ pipelineConfig:
               - name: build
                 #image: docker.io/golang:1.11.5
                 # needs helm in the image for install_gitops_integration_test.go
-                image: gcr.io/jenkinsxio/builder-go-maven
+                image: gcr.io/jenkinsxio/builder-go-maven:0.0.0-SNAPSHOT-PR-1250-2
```
Comment (hferentschik) [inline jenkins-x-integration.yml:52]: I guess that's to test your builder changes, right? Any issues upgrading the builders?

File: Makefile.codegen [hunk 3]
```diff
@@ -37,11 +37,15 @@ go-generate:
 generate-client: codegen-clientset codegen-config fmt importfmt ## Generate the client
 
 codegen-clientset: build-codegen ## Generate the k8s types and clients
+	# sleep for one second to prevent collision with previous codegen's replacement of go.mod
+	sleep 1
```
Comment (hferentschik) [inline Makefile.codegen:41]: Is that really needed?

File: Dockerfile.builder-go [hunk 4]
```diff
@@ -1,4 +1,4 @@
 # this is used for testing jx inside a cluster in development
-FROM gcr.io/jenkinsxio/builder-go:latest
+FROM gcr.io/jenkinsxio/builder-go:0.0.0-SNAPSHOT-PR-1250-2
```
Comment (hferentschik) [inline Dockerfile.builder-go:2]: what do we put there when we want to merge? Back to 'latest'?

File: cmd/codegen/generator/client_set.go [hunk 5]
```diff
@@ -79,7 +94,37 @@ func GenerateClient(generators []string, groupsWithVersions []string, inputPacka
 				if err != nil {
 					return err
 				}
+				// If we have a semver, copy the semver's pkg directory contents to the normal pkg and delete the semver directory
+				if semVer != "" {
```
Comment (hferentschik) [inline cmd/codegen/generator/client_set.go:98]: so what's going on here?

File: cmd/codegen/util/files.go [hunk 6]
```diff
@@ -12,6 +12,58 @@ import (
 	"github.com/pkg/errors"
 )
 
+// BackupGoModAndGoSum creates backup copies of go.mod and go.sum and returns a function to run at the end of execution
+// to revert the go.mod and go.sum in the repo to the backups.
+func BackupGoModAndGoSum() (func(), error) {
```
Comment (hferentschik) [inline cmd/codegen/util/files.go:17]: that's to avoid that the actual code generation makes changes to the go modules, right? But is the actual code generation in this case still "versioned"?

File: go.mod [hunk 7]
```diff
@@ -23,7 +24,7 @@ require (
 	github.com/antham/chyle v1.6.0
 	github.com/aws/aws-sdk-go v1.24.0
 	github.com/awslabs/goformation v0.0.0-20190320125420-ac0a17860cf1
-	github.com/banzaicloud/bank-vaults v0.0.0-00010101000000-000000000000
+	github.com/banzaicloud/bank-vaults v0.0.0-20190508130850-5673d28c46bd
```
Comment (hferentschik) [inline go.mod:27]: uhhh, I have bad recollections on the Vault version switching around

File: go.mod [hunk 8]
```diff
@@ -151,4 +163,4 @@ replace github.com/Azure/azure-sdk-for-go => github.com/Azure/azure-sdk-for-go v
 
 replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v10.14.0+incompatible
 
-replace github.com/banzaicloud/bank-vaults => github.com/banzaicloud/bank-vaults v0.0.0-20190508130850-5673d28c46bd
```
Comment (hferentschik) [inline go.mod:154]: so we don't need the Vault operator replace anymore? That would be nice.

File: hack/generate.sh (hunk 1 above)
Comment (abayer) [reply hack/generate.sh:9]: We install it elsewhere, so this ended up being redundant.

File: jenkins-x-integration.yml (hunk 2 above)
Comment (abayer) [reply jenkins-x-integration.yml:52]: Yup. This won't build without Go 1.13, so I had to cheat.

File: cmd/codegen/generator/client_set.go (hunk 5 above)
Comment (abayer) [reply cmd/codegen/generator/client_set.go:98]: Basically, I had to hack things a _bunch_ to get our codegen to properly result in `github.com/jenkins-x/jx/v2/pkg/...` etc.

File: cmd/codegen/util/files.go (hunk 6 above)
Comment (abayer) [reply cmd/codegen/util/files.go:17]: Yup.

File: go.mod (hunk 7 above)
Comment (abayer) [reply go.mod:27]: Yeah, this makes that stop. =)

File: go.mod (hunk 8 above)
Comment (abayer) [reply go.mod:154]: Correct!

File: cmd/codegen/util/files.go (hunk 6 above)
Comment (hferentschik) [reply cmd/codegen/util/files.go:17]: This is so that we can use go modules for the generation part (opposed to turning off go-modules). ATM, it would update the go.mod file which we don't want, since versions should only be driven by the runtime dependencies.

Comment (hferentschik) [reply cmd/codegen/util/files.go:17]: I am kind of undecided whether this is a good idea or not, but I don't really see an alternative.

File: cmd/codegen/generator/client_set.go (hunk 5 above)
Comment (hferentschik) [reply cmd/codegen/generator/client_set.go:98]: because client_set generator does not handle this properly?

**Comment by hferentschik** [comment]
What is the process to getting this merged in terms of these custom builder image versions everywhere. Do we need them to merge and then revert to latest once it is in or do we switch back to 'latest' (which might make the or build itself fail)?

File: cmd/codegen/util/files.go (hunk 6 above)
Comment (abayer) [reply cmd/codegen/util/files.go:17]: Same here.

File: cmd/codegen/generator/client_set.go (hunk 5 above)
Comment (abayer) [reply cmd/codegen/generator/client_set.go:98]: Yeah. I tried a lot of permutations/tweaks but couldn't ever get it quite right. Some of the generators did the right thing, some didn't.

**Comment by abayer** [comment]
@hferentschik Step one is to merge the builders PR and get that in the version stream, then to merge this more or less immediately afterwards. I believe everything currently on 1.12 should pass with the 1.13 builder (I did prep tweaks to ensure that in earlier PRs here), but to be safe, I'd like there to be as little gap as possible. Of course, downstream projects will _all_ fail as soon as this merges/releases since the import paths will have changed.

File: Dockerfile.builder-go (hunk 4 above)
Comment (abayer) [reply Dockerfile.builder-go:2]: Yup.

File: Makefile.codegen (hunk 3 above)
Comment (abayer) [reply Makefile.codegen:41]: Sometimes, yes - the go.mod juggling seems to not always be completed by the time the next target starts running.

**Comment by abayer** [comment]
I've removed the bandaid commits to use temporary builders, so this is going to fail until https://github.com/jenkins-x/jenkins-x-builders/pull/1250 has merged and gotten into the version stream.

File: Makefile.codegen (hunk 3 above)
Comment (hferentschik) [reply Makefile.codegen:41]: I find this odd. These are really independent processes and executions of the codegen binary. A new target is not starting before the previous has completed. How would the files not be updated by then?

**Comment by hervelemeur** [comment]
@abayer the CONTRIBUTING.md should be update too:
> Go 1.11 or 1.12, with support for compiling to linux/amd64 (Go version 1.13 is at the moment not supported).
