### PR TITLE
fix(sync): use commit sha instead of tag for ksync image

### LINKED ISSUE #6262: `jx sync` attempts to pull an invalid ksync image
### Summary 

`jx sync` attempts to pull an invalid ksync image

Have been working through @vfarcic's (excellent) DevOps 2.6 toolkit, and noticed an issue running `jx sync`: command was unable to result in successfully initialized pods.

```
$ jx sync --daemon
Downloading https://github.com/vapor-ware/ksync/releases/download/0.4.1/ksync_darwin_amd64 to /Users/robertnowell/.jx/bin/ksync.tmp...
Downloaded /Users/robertnowell/.jx/bin/ksync.tmp
Initialising ksync
==== Local Environment ====
Fetching extra binaries                     ✓

==== Preflight checks ====
Cluster Config                              ✓
Cluster Connection                          ✓
Cluster Version                             ✓
Cluster Permissions                         ✓

==== Cluster Environment ====
Adding ksync to the cluster                 ✓
Waiting for pods to be healthy              ✘
↳       Timed out waiting for the ksync daemonset to be healthy.

To debug, you can:
- Run 'kubectl --namespace=kube-system --context= get pods -lapp=ksync' to look at what's going on.
- Run 'ksync doctor' to do an in-depth check of your system and the cluster.
FATA[0100]                                              
ERROR: Error: Command failed  ksync init --upgrade --image vaporio/ksync:0.4.1
```



```
$ go-demo-6 % kubectl get pods --all-namespaces                                                                                                        
...
kube-system            ksync-8cwf7                                                0/2     ImagePullBackOff   0          12m
kube-system            ksync-fdvck                                                0/2     ImagePullBackOff   0          12m
kube-system            ksync-ppfd8                                                0/2     ImagePullBackOff   0          12m
```

```
$ go-demo-6 % kubectl -n kube-system describe pod ksync-8cwf7                                                                                          
...
Controlled By:  DaemonSet/ksync
Containers:
  ksync:
    Container ID:  
    Image:         vaporio/ksync:0.4.1
...
Events:
  Type     Reason     Age                   From                                              Message
  ----     ------     ----                  ----                                              -------
  Normal   Scheduled  22m                   default-scheduler                                 Successfully assigned kube-system/ksync-8cwf7 to gke-jx-rocks-default-pool-baa7e80e-tmfb
  Normal   BackOff    22m (x5 over 22m)     kubelet, gke-jx-rocks-default-pool-baa7e80e-tmfb  Back-off pulling image "vaporio/ksync:0.4.1"
  Warning  Failed     22m (x5 over 22m)     kubelet, gke-jx-rocks-default-pool-baa7e80e-tmfb  Error: ImagePullBackOff
  Normal   Pulling    22m (x3 over 22m)     kubelet, gke-jx-rocks-default-pool-baa7e80e-tmfb  pulling image "vaporio/ksync:0.4.1"
  Warning  Failed     22m (x3 over 22m)     kubelet, gke-jx-rocks-default-pool-baa7e80e-tmfb  Failed to pull image "vaporio/ksync:0.4.1": rpc error: code = Unknown desc = Error response from daemon: manifest for vaporio/ksync:0.4.1 not found
```

Appears that the image name is not quite right

The attempt to pull image `vaporio/ksync:<version>`seems expected from https://github.com/jenkins-x/jx/blob/master/pkg/cmd/sync/sync.go#L109

ksync images appear to exist at "ksync/ksync/<commit-hash>":
```
$ go-demo-6 % docker pull ksync/ksync:git-a5628b9                                                                                                                                                                                                                                                          (master)go-demo-6
git-a5628b9: Pulling from ksync/ksync
89d9c30c1d48: Pull complete 
4c6a69e598b9: Pull complete 
89673ea5653c: Pull complete 
97b28c888ef9: Pull complete 
Digest: sha256:fcb07b0634571432d76736b695c676365907b4215d2f0edd179a6ef2df2fa486
Status: Downloaded newer image for ksync/ksync:git-a5628b9
docker.io/ksync/ksync:git-a5628b9
$ go-demo-6 % docker pull vaporio/ksync:0.4.1                                                                                                                                                                                                                                                              (master)go-demo-6
Error response from daemon: manifest for vaporio/ksync:0.4.1 not found: manifest unknown: manifest unknown
?1 go-demo-6 % docker pull ksync/ksync:0.4.1                                                                                                                                                                                                                                                               (master)go-demo-6
Error response from daemon: manifest for ksync/ksync:0.4.1 not found: manifest unknown: manifest unknown
```


Seems ksync may have changed their image names recently?




### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.1011
jenkins x platform 2.0.1642
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.3
helm client        Client: v2.16.1+gbbdfe5e
git                2.20.1 (Apple Git-117)
Operating System   Mac OS X 10.14.6 build 18G95
```

### Jenkins type

<!--
Select which installation type are you using. 
-->
- [ ] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ x] Classic Jenkins

### Kubernetes cluster

<!--
What kind of Kubernetes cluster are you using & how did you create it?
-->
GKE, created through `jx create cluster`

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description
* use git commit as tags for ksync docker image
* refactor InstallSync to add tests
* improve error handling

#### Special notes for the reviewer(s)
/cc @hferentschik @abayer 
* If ksync is installed, jx will try to parse the git commit from the output of the command `ksync version`. 
* If ksync is not installed, then jx will get the commit sha for the latest tag/release for ksync.
It will use this commit sha (short sha of the first 7 characters) to pull the right ksync docker image 
#### Which issue this PR fixes
fixes #6262 and #6123

### CODE REVIEW

File: pkg/cmd/opts/install.go [hunk 1]
```diff
@@ -127,7 +127,8 @@ func (o *CommonOptions) DoInstallMissingDependencies(install []string) error {
 		case "kvm2":
 			err = kvm2.InstallKvm2()
 		case "ksync":
-			_, err = ksync.InstallKSync()
+			sy := &ksync.KsynClier{}
```
Comment (hferentschik) [inline pkg/cmd/opts/install.go]: I find this odd, why would you pass an empty KsynClier struct here. What do you want to achieve?

File: pkg/cmd/sync/sync.go [hunk 2]
```diff
@@ -100,13 +100,17 @@ func NewCmdSync(commonOpts *opts.CommonOptions) *cobra.Command {
 func (o *SyncOptions) Run() error {
 
 	// ksync is installed to the jx/bin dir, so we can add it for the user
-	os.Setenv("PATH", util.PathWithBinary())
+	err := os.Setenv("PATH", util.PathWithBinary())
+	if err != nil {
```
Comment (hferentschik) [inline pkg/cmd/sync/sync.go]: +1, good catch

File: pkg/cmd/sync/sync.go [hunk 3]
```diff
@@ -115,9 +119,9 @@ func (o *SyncOptions) Run() error {
 		flag, err := kube.IsDaemonSetExists(client, "ksync", "kube-system")
 		if !flag || err != nil {
 			log.Logger().Infof("Initialising ksync")
-			// Deal with https://github.com/vapor-ware/ksync/issues/218
+			// Deal with https://github.com/ksync/ksync/issues/218
 			err = o.RunCommandInteractive(true, "ksync", "init", "--upgrade", "--image",
```
Comment (hferentschik) [inline pkg/cmd/sync/sync.go]: Should that not go somehow through the Ksyncer interface?

File: pkg/ksync/cli.go [hunk 4]
```diff
@@ -11,39 +11,51 @@ import (
 	"github.com/jenkins-x/jx/pkg/util"
 )
 
-// InstallKSync install ksync
-func InstallKSync() (string, error) {
+type KSyncer interface {
```
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/ksync/cli.go]: What is the aim of KSyncer? By the name, I would expect that it encapsulate ksync commands, similar to _Kustomizer_ or _Helmer_, but that does not necessarily be the case here.

File: pkg/ksync/cli.go [hunk 5]
```diff
@@ -11,39 +11,58 @@ import (
 	"github.com/jenkins-x/jx/pkg/util"
 )
 
-// InstallKSync install ksync
-func InstallKSync() (string, error) {
+// KSyncer contains the methods used for ksync
+type KSyncer interface {
+	GetJXBinLocation() (string, error)
```
Comment (hferentschik) [inline pkg/ksync/cli.go]: I don't think this should go into this interface. We have already _JXBinaryLocation_ in the util package.

File: pkg/ksync/cli.go [hunk 6]
```diff
@@ -11,39 +11,58 @@ import (
...
+	IsInstalled(string) (string, bool, error)
```
Comment (hferentschik) [inline pkg/ksync/cli.go]: I think _IsInstalled_ should just return _bool_ and an error. Everything else is confusing imo.

File: pkg/ksync/cli.go [hunk 7]
```diff
@@ -11,39 +11,58 @@ import (
...
+	RunCommand(name string, args []string) (string, error)
```
Comment (hferentschik) [inline pkg/ksync/cli.go]: Is the intention do execute _ksync_ commands here? Or any type of command. If the former, I'd expect that 'ksync' (aka the main executable) is implicit in a _KSyncer_ interface. If the aim is to execute any arbitrary command then why does it have to be in the interface?

File: pkg/ksync/cli.go [hunk 8]
```diff
@@ -11,39 +11,58 @@ import (
...
 	if err != nil {
 		return "", err
 	}
-	binary := "ksync"
+	return binDir, nil
+}
+
+// IsInstalled checks if the binary is installed
+func (kcli *KsynClier) IsInstalled(binary string) (string, bool, error) {
 	fileName, flag, err := packages.ShouldInstallBinary(binary)
```
Comment (hferentschik) [inline pkg/ksync/cli.go]: Depending on what you try to achieve `ShouldInstallBinary` is not going to work for you. For example if your aim is to install ksync into JX_HOME/bin, then  `ShouldInstallBinary` is not a good choice. See also issue #6912

File: pkg/ksync/cli.go [hunk 9]
```diff
@@ -11,39 +11,51 @@ import (
...
+	// Explicitly ignore any errors from ksync version, as we just need the output!
+	res, err := ksyncCmd.RunWithoutRetry()
+	if err != nil {
+		return "", err
 	}
-	latestVersion, err := util.GetLatestVersionFromGitHub("vapor-ware", "ksync")
+	return res, nil
+}
+
+func (kcli *KsynClier) GetTag(binDir, fileName, owner, repo string) (string, error) {
```
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/ksync/cli.go]: That seems to be doing much more than getting a tag. This downloads and installs the binary as well right? For Kutomize we have written an integration test which proves that the download and install works. I would love to see this here as well.

File: pkg/ksync/export_test.go [hunk 10]
```diff
@@ -0,0 +1,3 @@
+package ksync
```
Comment (hferentschik) [inline pkg/ksync/export_test.go]: What is this file about? It is marked as a test, but no tests are defined in here. Also if it were a test file it needs to be classified as either _unit_ or _integration_ test. This causes the linting task to fail atm.

File: pkg/packages/install.go [hunk 11]
```diff
@@ -179,25 +179,25 @@ func ShouldInstallBinary(name string) (fileName string, download bool, err error
 	pgmPath, err := exec.LookPath(fileName)
```
Comment (hferentschik) [inline pkg/packages/install.go]: This whole check should probably be removed.
Also let's remove the named returns altogether. 
This should probably also be synced with PR #6917 from @nehagup

File: pkg/util/downloads.go [hunk 12]
```diff
@@ -234,7 +234,7 @@ func preamble() (*github.Client, *github.RepositoryRelease, *github.Response, er
 			ts := oauth2.StaticTokenSource(
 				&oauth2.Token{AccessToken: token},
 			)
-			tc = oauth2.NewClient(oauth2.NoContext, ts)
+			tc = oauth2.NewClient(context.TODO(), ts)
```
Comment (hferentschik) [inline pkg/util/downloads.go]: Why this change?

File: pkg/ksync/cli.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go]: The idea was to break the monolith InstallKSync function and decouple calls to external packages, and make it easier to test (It's quite difficult to write tests in the current codebase), but I think it would make more sense to encapsulate ksync commands in that interface. I will refactor it.

File: pkg/util/downloads.go (hunk 12 above)
Comment (ankitm123) [reply pkg/util/downloads.go]: NoContext is deprecated: https://godoc.org/golang.org/x/oauth2#pkg-variables

File: pkg/packages/install.go (hunk 11 above)
Comment (ankitm123) [reply pkg/packages/install.go]: Let me take a look at that PR.

File: pkg/ksync/export_test.go (hunk 10 above)
Comment (ankitm123) [reply pkg/ksync/export_test.go]: The idea was to test functions which are unexported, and this is the standard technique to test it. It is also common in the go standard library. Source: https://medium.com/@robiplus/golang-trick-export-for-test-aa16cbd7b8cd

File: pkg/cmd/sync/sync.go (hunk 2 above)
Comment (ankitm123) [reply pkg/cmd/sync/sync.go]: I have an issue abt better error handling, and enabling errcheck as part of the lint step when we open a PR against jx master: https://github.com/jenkins-x/jx/issues/6851. I have a branch, where I am adding more error checks, it's a bigger work in progress atm.

File: pkg/ksync/cli.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (hferentschik) [reply pkg/ksync/cli.go]: > The idea was to break the monolith InstallKSync function and decouple calls to external packages, and make it easier to test 

I am very much for breaking things up. As you say it is all very intervened. I think, however, in the case if the _KSyncInstall_ function you already get a long way with extracting some functions. _KSyncer_ really sends the wrong message, since by name I would expect it to do something differently, especially given the rest of the codebase

> It's quite difficult to write tests in the current codebase

Ohhh yes. I feel the pain. The install command itself should be quite easy though. Look as well at _kustomize_integration_test.go_. Really I think for testing the install command, we do want to download the actual binary. Only this way we can be sure it works. Mocking this is no guarantee that for example, the URL is correct. Let's try to keep the necessary change minimal here. 

> but I think it would make more sense to encapsulate ksync commands in that interface. I will refactor it.

that might be suitable for another issue/pr.

File: pkg/cmd/sync/sync.go (hunk 2 above)
Comment (hferentschik) [reply pkg/cmd/sync/sync.go]: that would be nice

File: pkg/auth/.tmp_gomock_reflect_512816048/prog.go [hunk 13]
```diff
@@ -0,0 +1,46 @@
+
+package main
```
Comment (hferentschik) [inline pkg/auth/.tmp_gomock_reflect_512816048/prog.go]: I guess you did not mean to commit this file

File: pkg/ksync/cli.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go]: I agree abt the integration tests, I will fix this PR this weekend, and get back to you :)

File: pkg/ksync/cli.go (hunk 8 above)
Comment (ankitm123) [reply pkg/ksync/cli.go:44]: I think I can remove `ShouldInstallBinary` after issue #6912 is resolved.

File: pkg/packages/install.go (hunk 11 above)
Comment (ankitm123) [reply pkg/packages/install.go:179]: Again, I think I need to wait till that PR is merged, what do u say?

Comment (ankitm123) [reply pkg/packages/install.go:179]: I could do this:
```
func ShouldInstallBinary(name string) (fileName string, download bool, err error) {
	fileName = BinaryWithExtension(name)
	download = false

	binDir, err := util.JXBinLocation()
	if err != nil {
		return fileName, download, err
	}

	// lets see if its been installed
	exists, err := util.FileExists(filepath.Join(binDir, fileName))
	if err != nil {
		return fileName, download, err
	}
	if exists {
		return fileName, download, err
	}
	download = true
	return fileName, download, err
}
```
It works in my case (the ksync integration test passes), I dont see the point in installing ksync in global PATH, or even check if it exists there. JXBIN should be the single source of truth. However, this function is used at lot of places, and my refactoring might break more things, and goes beyond the scope of this PR. I could also just extract this to a separate function for only ksync, but a generic function would make more sense imo.

File: pkg/auth/.tmp_gomock_reflect_512816048/prog.go (hunk 13 above)
Comment (ankitm123) [reply pkg/auth/.tmp_gomock_reflect_512816048/prog.go]: Right, removed.

File: pkg/ksync/cli.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go]: Split it into getTag and install function.

File: pkg/ksync/cli.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go]: The integration tests now check if the binary is installed in jx bin, and the ksync pods are in the kubernetes cluster (this is the area which was the main focus of this PR, the wrong tag for the image resulted in unhealthy pods)

File: pkg/cmd/opts/install.go (hunk 1 above)
Comment (ankitm123) [reply pkg/cmd/opts/install.go]: Refactored this code, pretty similar to the existing codebase now.

File: pkg/cmd/sync/sync.go (hunk 3 above)
Comment (ankitm123) [reply pkg/cmd/sync/sync.go]: Yup, and it does now :)

File: pkg/ksync/cli.go (hunk 7 above)
Comment (ankitm123) [reply pkg/ksync/cli.go]: Refactored the interface, it only has ksync commands (version, init and clean) atm. I did not add the other commands to the interface because I feel they are beyond the scope of this PR, I think it makes sense to make an issue which addresses cleaning up and refactoring the ksync codebase, and make the changes as part of that PR. what do u think?

File: pkg/packages/install.go (hunk 11 above)
Comment (hferentschik) [reply pkg/packages/install.go:179]: The `ShouldInstallbinary` part is getting taken care of by @daveconde and his work for multi- cluster support - https://github.com/jenkins-x/jx/pull/7045

File: pkg/cmd/sync/sync_integration_test.go [hunk 14]
```diff
@@ -0,0 +1,86 @@
...
+	// Run ksync in it's own goroutine and pass the error message into a channel
+	go func(cmd *cobra.Command) {
+		err := cmd.Execute()
+		executeCh <- err
+	}(cmd)
+
+	// Check for ksync daemonset in another go routine and pass the error to a channel
+	go func(opts *opts.CommonOptions) {
+		// Wait for at least one pod to be ready
+		time.Sleep(sleepbeforecheck * time.Second)
```
Comment (hferentschik) [inline pkg/cmd/sync/sync_integration_test.go:66]: I don't think this is going to fly. For the pipeline build, 30 seconds is probably a lot and we already have issues with a very slow test suite. On the other hand, I cannot get this test pass locally, because the sleep ends on my machine and internet connection before the download and install of ksync is complete. 

I think we need a more active readiness check. Either by explicitly watching the rollout of the daemon set deployment or by calling `kube.IsDaemonSetExists` in some sort of time-limited loop (maybe with exponential backoff). For the latter, we have several examples in the code.

File: pkg/cmd/sync/sync_integration_test.go [hunk 15]
```diff
@@ -0,0 +1,86 @@
...
+			checkCh <- errors.New("zero pods ready")
+		}
+		checkCh <- nil
+	}(commonOpts)
+
+	select {
+	case err := <-executeCh:
+		assert.NoError(t, err, "unable to execute ksync commands")
+	case err := <-checkCh:
+		assert.NoError(t, err, "ksync pods not ready")
```
Comment (hferentschik) [inline pkg/cmd/sync/sync_integration_test.go:84]: Maybe also here add a time based select, so in case something goes wrong the test will eventually time out.

File: pkg/ksync/cli.go [hunk 16]
```diff
@@ -11,51 +11,159 @@ import (
...
 	}
-	clientURL := fmt.Sprintf("https://github.com/vapor-ware/ksync/releases/download/%s/ksync_%s_%s", latestVersion, runtime.GOOS, runtime.GOARCH)
+	latestVersion := *latestTag.Name
+	// This will return the shortsha, the first 7 characters associated with the git commit
+	latestSha := (*latestTag.Commit.SHA)[:7]
+	return latestSha, latestVersion, nil
+}
+
+// install downloads and installs the ksync package
+func install(latestVersion, binDir, fileName string) error {
```
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go:65]: I had a test for this, but then thought it was redundant because TestKsyncCMD was testing it indirectly. I can always add it back. Testing the install for all the OS would be nice :).

File: pkg/cmd/sync/sync_integration_test.go (hunk 14 above)
Comment (hferentschik) [reply pkg/cmd/sync/sync_integration_test.go:66]: @ankitm123 what's about we skip this test for now and just add a test for the actual install of the binary. This would fix the imminent problem that the image is wrong. Once we have a better solution for writing this test we can then add it as additional test. WDYT?

Comment (ankitm123) [reply pkg/cmd/sync/sync_integration_test.go:66]: We can do that for the time being, but the issue was not with the binary (local ksync binary) being downloaded, the issue was with the tag for the ksync docker image. The binary was always getting installed and downloaded properly, but `jx sync` was using the same tag (0.4.4) for downloading docker images (kysnc images use the git hash, that is where the problem was). Adding the binary test will at least increase the test coverage for now, I will make a separate issue, and address the tests in a subsequent PR, what do u say?

Comment (hferentschik) [reply pkg/cmd/sync/sync_integration_test.go:66]: Sounds good. Thanks for the clarification.

File: pkg/ksync/cli.go [hunk 17]
```diff
@@ -11,51 +11,159 @@ import (
...
+		Name: fmt.Sprintf("%s/ksync", path),
+	}
+	cli := &CLI{
+		Runner: runner,
+	}
+	return cli, nil
+}
+
+// GetJXBinLocation returns the jx bin location
+func getJXBinLocation() (string, error) {
```
[the remark this answers is not in the document]
Comment (ankitm123) [reply pkg/ksync/cli.go]: Removed.

File: pkg/cmd/sync/sync_integration_test.go (hunk 14 above)
Comment (ankitm123) [reply pkg/cmd/sync/sync_integration_test.go:66]: I made the changed requested, and added a simple check to see if ksync is installed or not. Once this PR is merged, I will work on adding the integration tests back with the changes requsted.

File: pkg/ksync/ksync_integration_test.go [hunk 18]
```diff
@@ -0,0 +1,33 @@
...
+		if err != nil {
+			log.Logger().Warnf("unable to remove temporary directory %s: %s", testJXHome, err)
+		}
+		log.Logger().Info("Deleted temporary jx home directory")
+	}()
+
+	// Test installing ksync locally
+	_, err = ksync.InstallKSync()
+	assert.NoError(t, err, "error installing ksync")
+	assert.FileExists(t, filepath.Join(testJXHome, "bin", "ksync"))
```
Comment (hferentschik) [inline pkg/ksync/ksync_integration_test.go:32]: +1 nice one

**Comment by ankitm123** [comment]
@hferentschik any ideas why some tests failed?

**Comment by hferentschik** [comment]
> any ideas why some tests failed?

something completely unrelated. Maybe a temporary issue with GitHub. Not sure:

```
Creating Git repository *************-test/environment-pr-6919-106-tf-boot-production
error: failed to create git repository for gitURL https://github.com/******************/environment-pr-6919-106-tf-boot-production.git: push forked environment git repository: Have you set up a git credential helper? See https://help.github.com/articles/caching-your-github-password-in-git/
: git output: remote: Repository not found.
fatal: repository 'https://******************:****************************************@github.com/******************/environment-pr-6919-106-tf-boot-production.git/' not found: failed to run 'git push origin master' command in directory '/tmp/**-env-repo-729551518/******************/environment-pr-6919-106-tf-boot-production', output: 'remote: Repository not found.
fatal: repository 'https://*************-test:****************************************@github.com/*************-test/environment-pr-6919-106-tf-boot-production.git/' not found'
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c ** step verify env' command in directory '.', output: ''
```

Triggered a re-run on this context.

**Comment by ankitm123** [comment]
failed again, seems like a flaky test hmmm...
