### PR TITLE
fix: filter environments from delete application

### LINKED ISSUE #5668: jx delete application can delete environments!
### Summary 
Issuing `jx delete application` shows a default list of applications to delete that includes live environments as selectable items. This makes it far too easy to accidentally delete an environment when trying to remove an application.

### Jx version

The output of `jx version` is:

```
2.0.775
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by mauromorales**
This PR removes any environments from the list of applications that can be deleted.

Before

```
$ jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [ ]  mauromorales/environment-mm-ghi-5668-dev
  [ ]  mauromorales/environment-mm-ghi-5668-production
  [ ]  mauromorales/environment-mm-ghi-5668-staging
  [ ]  mauromorales/jx-qs-test-delete-apps
```

After

```
$ jx delete application
? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter]
> [ ]  mauromorales/jx-qs-test-delete-apps
```

fixes #5668

### CODE REVIEW

**Comment by hferentschik** [comment]
@mauromorales, would you mind pasting a before and after example of the output? Either on the pull request or on the issue.

File: pkg/cmd/deletecmd/delete_application.go [hunk 1]
```diff
@@ -139,6 +139,23 @@ func (o *DeleteApplicationOptions) Run() error {
 	return nil
 }
 
+func removeEnvironments(jobs []string, environments map[string]*v1.Environment) (applications []string) {
```
Comment (hferentschik) [inline pkg/cmd/deletecmd/delete_application.go]: I am not a friend of naked return values. If anything they should only be used in short functions (which this one arguably is). The problem is that functions can change and easily cross the threshold where naked returns become more of a liability than anything else. Also for consistency reasons, I'd prefer to stay clean of them. That's my 0.02$

File: pkg/cmd/deletecmd/delete_application.go [hunk 2]
```diff
@@ -139,6 +139,23 @@ func (o *DeleteApplicationOptions) Run() error {
...
+	var keep bool
+	for _, job := range jobs {
+		keep = true
+		for _, environment := range environments {
+			if strings.Contains(environment.Spec.Source.URL, job) {
+				keep = false
```
Comment (hferentschik) [inline pkg/cmd/deletecmd/delete_application.go]: Why the detour via the `keep`? If you invert the if statement you can do everything in one line, right?

**Comment by hferentschik** [comment]
> ```
> $ jx delete application
> ? Pick Applications to remove from Prow:  [Use arrows to move, space to select, type to filter] 
> [ ]  mauromorales/environment-mm-ghi-5668-dev
> [ ]  mauromorales/environment-mm-ghi-5668-production
> [ ]  mauromorales/environment-mm-ghi-5668-staging
> [ ]  mauromorales/jx-qs-test-delete-apps
> ```

I guess what gets me here is why the env repos would be "apps". Is there no better way to get apps instead of going via `prowOptions.GetReleaseJobs()`?

File: pkg/cmd/deletecmd/delete_application.go (hunk 2 above)
Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik I don't think this would work because if it's inverted we'd add records every time we don't match the environment, and that would be the case for every existing environment, so we'd end up with a bunch of duplicates

File: pkg/cmd/deletecmd/delete_application.go (hunk 1 above)
Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: I've switched the function to explicitly returns the list of applications

File: pkg/cmd/deletecmd/delete_application.go [hunk 3]
```diff
@@ -160,11 +179,12 @@ func (o *DeleteApplicationOptions) deleteProwApplication(repoService jenkinsv1.S
 		NS:           ns,
 		IgnoreBranch: true,
 	}
-	names, err := prowOptions.GetReleaseJobs()
+	jobs, err := prowOptions.GetReleaseJobs()
```
Comment (hferentschik) [inline pkg/cmd/deletecmd/delete_application.go]: So maybe 'GetReleaseJobs' is really the best we have in the case of _applications_. Feels wrong though. IMO there should be a clear separation between applications/projects and environments. At some stage, we need to try unravelling this instead of monkey patching. 

If we go for filtering, we might want to consider whether it makes sense to push the filtering into `GetReleaseJobs` instead of just applying only in _delete_application_. This sounds like something which could be useful at other places as well. Just thinking out loud atm. @ccojocar WDYT?

File: pkg/cmd/deletecmd/delete_application.go (hunk 2 above)
Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: ahh, I see what you are saying.

Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: One could split the two for loops, just iterating either the jobs or the envs and then making the "contains" check in a helper function. But that's just nitpick.

File: pkg/cmd/deletecmd/delete_application.go (hunk 3 above)
Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: Another disadvantage here is that this is tying us t Prow which is probably not really future proof (thinking Lighthouse here).

I am wondering whether there is some sort of label we could base a selection on which differs between a project/application created via jx [import|create] and say the env pipelines.

Or whether it is possible to first retrieve application namespaces (staging|production|...) and then find applications in this namespace. In this model the dev environment would not count as application namespace.

Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: Also, how does this compare with `jx get application`? Does that have the same problem and if so, do we need to align between them?

Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik good point. We seem to be getting a deployments list on `jx get application` which does return only the applications and not the environments.

https://github.com/jenkins-x/jx/blob/a2908f49f3b03b1374fc3e04ab57a93b1bee963c/pkg/cmd/get/get_applications.go#L281

What I wasn't able to figure out is how to get the repository owner out of the deployment. Do you know if there's a way?

Also, as you mention if we were to follow this approach then we'd only need to request the applications from a given environment to solve #5671

File: pkg/cmd/deletecmd/delete_application.go (hunk 2 above)
Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik I've extracted it into a function now ... but I guess this will depend on what we decide about using a different mechanism to get the applications

File: pkg/cmd/deletecmd/delete_application.go [hunk 4]
```diff
@@ -139,6 +139,28 @@ func (o *DeleteApplicationOptions) Run() error {
 	return nil
 }
 
+func matchesWithAnyEnvironmentURL(s string, environments map[string]*v1.Environment) bool {
```
Comment (hferentschik) [inline pkg/cmd/deletecmd/delete_application.go]: This looks good to me now in terms of using the "filtering" approach. Still trying to figure out whether there is no better way, aka aligning with `get application`.  Funny enough `GetDeployments` in `get application` takes a completely different approach to what we do here. `GetDeployments` goes via Kubernetes deployments while here we look at the Prow config. IMO this should definitely be aligned. Also, the code in `get applications` is explicitly skipping the dev environment which makes sense as well. So I am wondering whether we could not share somehow the code around `GetApplicationsOptions#getAppData`. Does this make sense?

File: pkg/cmd/deletecmd/delete_application.go (hunk 3 above)
Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: See https://github.com/jenkins-x/jx/pull/6069/files#r345255299

Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: > What I wasn't able to figure out is how to get the repository owner out of the deployment. Do you know if there's a way?

Not sure I follow. What do you mean?

Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik right now the generated output with the delete command is:

```
[ ]  mauromorales/jx-qs-test-delete-apps
```

however from `GetDeployments` I only seem to be able to get the name of the application`jx-qs-test-delete-apps` and I'm not aware how to relate it to the repo url/owner

File: pkg/cmd/deletecmd/delete_application.go (hunk 4 above)
Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik yup I know what you mean, I'd be ok using the approach mentioned in the other comment but we should have it clear how much backwards compatibility this should have. If it isn't necessary to show the owner for example then we could also just do the switch.

Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: In the light of https://codetree.com/projects/StX1/board/10487910?type=epic and the recent discussion around applications, I think applications should be retrieved via iterating SourceRepository CRDs. Initially, we can do this without any modifications to the CRD itself, we can just apply the same filtering for env repos as we use here. Another benefit of using the CRDs is that you have the repo information. 

I leave it up to you. I guess we could merge this now and address everything else as part of the "refactor application commands" or we take a first initial step and use SourceRepository CRDs. WDYT?

Comment (mauromorales) [reply pkg/cmd/deletecmd/delete_application.go]: @hferentschik because of all the changes and back and forth that might happen from the refactoring I'd prefer to just merge/close this PR and address in https://github.com/jenkins-x/jx/issues/6101

Comment (hferentschik) [reply pkg/cmd/deletecmd/delete_application.go]: We took the refactoring of the application commands into the new sprint, if you want to continue there. The first step would be to let `get` and `delete` application use the same data source (SourceRepository).
