### PR TITLE
fix: Cloning for environments shouldn't leave strange state in JX_HOME

### LINKED ISSUE #6350: Delete app fails with cherry-pick error
### Summary 
Attempting to delete an App using `jx delete app` fails under some circumstances due to a cherry pick error.

### Steps to reproduce the behavior
```
➜ jx delete app jx-app-fossa
Attempting to cherry pick commits that were on master but not yet pushed
error: couldn't pull the environment repository from dev: Unable to cherry-pick a155412b72bd8ca8123a8e3b0993a5bd49ca577d: git output: error: commit a155412b72bd8ca8123a8e3b0993a5bd49ca577d is a merge but no -m option was given.
fatal: cherry-pick failed: failed to run 'git cherry-pick a155412b72bd8ca8123a8e3b0993a5bd49ca577d' command in directory '/Users/terry/.jx/environments', output: 'error: commit a155412b72bd8ca8123a8e3b0993a5bd49ca577d is a merge but no -m option was given.
fatal: cherry-pick failed'
```

### Jx version

The output of `jx version` is:

```
jx                 2.0.1011
Kubernetes cluster v1.13.11-gke.14
kubectl            v1.16.2
helm client        Client: v2.14.0+g05811b8
git                2.21.0
Operating System   Mac OS X 10.14.6 build 18G1012
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + Prow)
- [ ] Classic Jenkins

### PR DESCRIPTION
**Pull request by abayer**
#### Submitter checklist

- [x] Change is code complete and matches issue description.
- [x] Change is covered by existing or new tests.

#### Description

Until this, `jx delete app`, `jx add app`, and `jx get apps` all did weird things with/under `~/.jx/environments`. All of them used `ForkAndPullRepo` to clone under there - `jx get apps` directly into `~/.jx/environments`, and `jx add app` and `jx delete app` into `~/.jx/environments/dev`. Literally none of this made sense. =)

This reworks not just the app commands, but all commands that create PRs (i.e., gitops) against the dev/prod/staging environments to use temporary directories for the fork/clone/push, with the option, just used in tests, of specifying an existing directory to use instead, while `jx get apps` just clones to a temporary directory as well.

Switching all this to temporary directories also really helps users who manage/work with multiple JX clusters from a single laptop/desktop/host, since namespacing `~/.jx/environments` by cluster is basically impossible so far as I can tell.

Also adds `--auto-merge` to `jx delete app` because I was here.

#### Which issue this PR fixes

fixes #6350

### CODE REVIEW

**Comment by abayer** [comment]
I'm not shocked at the failures - I just wanted to push up what worked for actual apps usage before I had to run to an appointment. Will fix later today

File: pkg/apps/gitops.go [hunk 1]
```diff
@@ -166,9 +176,18 @@ func (o *GitOpsOptions) DeleteApp(app string, alias string, autoMerge bool) erro
 
 // GetApps retrieves all the apps information for the given appNames from the repository and / or the CRD API
 func (o *GitOpsOptions) GetApps(appNames map[string]bool, expandFn func([]string) (*v1.AppList, error)) (*v1.AppList, error) {
-	dir, _, _, _, err := gits.ForkAndPullRepo(o.DevEnv.Spec.Source.URL, o.EnvironmentsDir, o.DevEnv.Spec.Source.Ref, "master", o.GitProvider, o.Gitter, "")
+	dir, err := ioutil.TempDir("", "create-pr")
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: on a side note, I think we should start using a base dir within JX_HOME, e.g. JX_HOME/tmp for all out temporary directory creations. This probably makes it easier to debug and it is also easier to see when things don't get cleaned up.

Comment (hferentschik) [reply pkg/apps/gitops.go]: and why would 'get app' create a tmp directory with 'create-pr' in it?

Comment (hferentschik) [reply pkg/apps/gitops.go]: So for each 'get apps' we clone the repo? That does not seem terribly effective? I guess the idea of using ~/.jx/environment was to have some sort of a cache. 

Admittedly something which works it better than something which is "more performant" but not working ;-)

File: pkg/apps/gitops.go [hunk 2]
```diff
@@ -166,9 +176,18 @@ func (o *GitOpsOptions) DeleteApp(app string, alias string, autoMerge bool) erro
 
 // GetApps retrieves all the apps information for the given appNames from the repository and / or the CRD API
 func (o *GitOpsOptions) GetApps(appNames map[string]bool, expandFn func([]string) (*v1.AppList, error)) (*v1.AppList, error) {
-	dir, _, _, _, err := gits.ForkAndPullRepo(o.DevEnv.Spec.Source.URL, o.EnvironmentsDir, o.DevEnv.Spec.Source.Ref, "master", o.GitProvider, o.Gitter, "")
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: As much as I also dislike the use of `ForAndPullRepo` here, if for no other reason than the fact that it is a terrible name, I believe this would actually work, if there were not the #5772 bug.

Comment (hferentschik) [reply pkg/apps/gitops.go]: Another issue with ~/.jx/environment is that in the case of app it is not keys against context. So if you have multiple clusters and you switch between them you also get an error, this time a legit merge error. This is due to the fact that this app code came first. Later code which uses JX_HOME to cache checkout is keying against the cluster. I believe there is an issue for this as well.

File: pkg/apps/gitops.go (hunk 1 above)
Comment (abayer) [reply pkg/apps/gitops.go]: `jx get app` and `jx get delete app` create PRs, so...

And yeah, I decided to ditch the sorta cache in `~/.jx/environments` because (a) it was horribly broken as written, and (b) there currently is no viable way to namespace the clone inside `~/.jx/environments` by cluster, so if you've got multiple clusters, you'd still end up having potential problems.

File: pkg/apps/gitops.go (hunk 2 above)
Comment (abayer) [reply pkg/apps/gitops.go]: But _why_ use `ForkAndPullRepo` here? It's the forking that drove me off - there's absolutely no reason to _fork_ the dev env as part of running `jx get apps`.

File: pkg/apps/gitops.go (hunk 1 above)
Comment (abayer) [reply pkg/apps/gitops.go]: wait, my brain fried - this shouldn't be `create-pr-`. duh. =)

File: pkg/apps/gitops.go (hunk 2 above)
Comment (hferentschik) [reply pkg/apps/gitops.go]: Exactly, the name is terrible. It implies completely different semantics to what is actually happening, depending on the passed parameters. It is not always forking. The docs also says "ForkAndPullRepo pulls the specified gitUrl into dir using gitter, creating a remote fork if needed using the git provider". But that makes the function not less confusing. It is one of these cases where a single methods tries to do everything. 

I agree it completely confuses the reader of the code at this point in the code. I also think there are several things wrong with ForkAndPullRepo, so the less we use it the better. 

Doing a fresh throw-away checkout for each of these app operations will fix it, but with a pretty high cost. It feels like it there should be a better way. But let's go for something which works.

**Comment by abayer** [comment]
Fixed most of the test failures - `controller_workflow_integration_test` is failing but I literally have no idea how this change makes it fail and I've had a looooong day so I'll look into it tomorrow.

File: pkg/apps/gitops.go (hunk 2 above)
Comment (abayer) [reply pkg/apps/gitops.go]: We already effectively are doing throw away checkouts for `jx add app`, `jx delete app`, `jx upgrade app`, and their friends (namely `jx step scheduler [apply|migrate]`. I just threw in a throwaway checkout for `jx get apps` too. =)

File: pkg/cmd/add/add_app_test.go [hunk 3]
```diff
@@ -80,6 +80,11 @@ func TestAddAppForGitOps(t *testing.T) {
 			DevEnv:     testOptions.DevEnv,
 			HelmUpdate: true, // Flag default when run on CLI
 		}
+		envDir, err := o.CommonOptions.EnvironmentsDir()
```
Comment (hferentschik) [inline pkg/cmd/add/add_app_test.go]: is this test retrying!?

File: pkg/apps/gitops.go [hunk 4]
```diff
@@ -42,6 +42,16 @@ func (o *GitOpsOptions) AddApp(app string, dir string, version string, repositor
 		GitProvider: o.GitProvider,
 	}
 
+	prDir := o.EnvironmentsDir
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: I find it very confusing that parts of the required input for this function come via function parameters and others by accessing the `GitOpsOptions` instance. For example, `autoMerge` is passed as a parameter,  `o.EnvironmentsDir` not.

File: pkg/apps/gitops.go [hunk 5]
```diff
@@ -42,6 +42,16 @@ func (o *GitOpsOptions) AddApp(app string, dir string, version string, repositor
...
+	if prDir == "" {
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: This confuses me. What's happening here. So first you set the `prDir` to the `EnvironmentsDir` which I believe is `~/.jx/environments`, right? If it does not exist you create a tmp directory which eventually gets deleted. I get that part, but what if `~/.jx/environments` already exists?

Comment (hferentschik) [reply pkg/apps/gitops.go]: hmm, on second thought, I might be looking at something here which is work in progress, since `prDir` is not even used.

File: pkg/cmd/add/add_app_test.go (hunk 3 above)
Comment (abayer) [reply pkg/cmd/add/add_app_test.go]: Because the tests want to look at the contents of the resulting PR to make sure it did the right thing, and because of how `FakeProvider` works, that means we've gotta keep around the repo we create the PR in. Hence the `CloneDir` option I've added to all the various commands but not exposed via the CLI - a way to say "actually, don't use a temporary directory, use this one".

File: pkg/apps/gitops.go (hunk 4 above)
Comment (abayer) [reply pkg/apps/gitops.go]: I've tidied it up a bit, but it's still kinda janky.

File: pkg/apps/gitops.go (hunk 5 above)
Comment (abayer) [reply pkg/apps/gitops.go]: Fixed that.

**Comment by abayer** [comment]
This will pass again once https://github.com/jenkins-x/bdd-jx/pull/104 merges.

File: pkg/apps/gitops.go [hunk 6]
```diff
@@ -166,9 +167,38 @@ func (o *GitOpsOptions) DeleteApp(app string, alias string, autoMerge bool) erro
...
+		return nil, errors.Wrapf(err, "parsing dev env repo URL %s", o.DevEnv.Spec.Source.URL)
+	}
+
+	providerInfo, err := o.GitProvider.GetRepository(gitInfo.Organisation, gitInfo.Name)
+	if err != nil {
+		return nil, errors.Wrapf(err, "determining git provider information for %s", o.DevEnv.Spec.Source.URL)
+	}
+	cloneUrl := providerInfo.CloneURL
+	userDetails := o.GitProvider.UserAuth()
+	originFetchURL, err := o.Gitter.CreateAuthenticatedURL(cloneUrl, &userDetails)
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: :-( - this is bad. We should not use this approach. Sad to see that this proliferates now outside ForkAndPullRepo

File: pkg/apps/install.go [hunk 7]
```diff
@@ -175,6 +175,12 @@ func (o *InstallOptions) DeleteApp(app string, alias string, releaseName string,
 		Items: make([]string, 0),
 	}
 
+	// Make sure that we use a temporary directory for GetApps even if we're not using a temporary directory for DeleteApps
```
Comment (hferentschik) [inline pkg/apps/install.go]: What does that mean? Thought we are going to use tmp directories for all of it now?

File: pkg/cmd/add/add_app_test.go (hunk 3 above)
Comment (hferentschik) [reply pkg/cmd/add/add_app_test.go]: So we need to add this just for testing purposes? Seems wrong, especially since it confuses the reader of the production code. I already stumbled across your comment.

Is there no other way to test this?

File: pkg/apps/gitops.go (hunk 6 above)
Comment (abayer) [reply pkg/apps/gitops.go]: I don't disagree, but I couldn't figure out how to ensure that `ForkAndPullRepo` _doesn't_ fork (it seems to fork if the current user is different from the owner of the repo) and I needed an authenticated clone URL, so...

File: pkg/cmd/deletecmd/delete_app.go [hunk 8]
```diff
@@ -45,6 +45,10 @@ type DeleteAppOptions struct {
 	Namespace   string
 	Purge       bool
 	Alias       string
+	AutoMerge   bool
+
+	// Used for testing
+	CloneDir string
```
Comment (hferentschik) [inline pkg/cmd/deletecmd/delete_app.go]: :-(

File: pkg/apps/install.go (hunk 7 above)
Comment (abayer) [reply pkg/apps/install.go]: That's an out-of-date comment - I'll remove.

Comment (abayer) [reply pkg/apps/install.go]: ...and out of date code. Fixing. =)

File: pkg/cmd/add/add_app_test.go (hunk 3 above)
Comment (abayer) [reply pkg/cmd/add/add_app_test.go]: Not so far as I can tell - opening a PR with `FakeProvider` just adds a record on the target repository's struct saying "there's a PR from this other repo", so once the other repo's directory gets deleted, the actual content of the PR is gone. So we either need to do the `CloneDir` stuff or we need to remove checking the content of the PR from the tests, which seems like a bad idea.

File: pkg/apps/gitops.go (hunk 6 above)
Comment (hferentschik) [reply pkg/apps/gitops.go]: Sure

Comment (abayer) [reply pkg/apps/gitops.go]: Though I'd be fine with adding an argument to `ForkAndPullRepo` to explicitly block forking and just using it here.

File: pkg/apps/gitops.go [hunk 9]
```diff
@@ -166,9 +167,37 @@ func (o *GitOpsOptions) DeleteApp(app string, alias string, autoMerge bool) erro
 
 // GetApps retrieves all the apps information for the given appNames from the repository and / or the CRD API
 func (o *GitOpsOptions) GetApps(appNames map[string]bool, expandFn func([]string) (*v1.AppList, error)) (*v1.AppList, error) {
-	dir, _, _, _, err := gits.ForkAndPullRepo(o.DevEnv.Spec.Source.URL, o.EnvironmentsDir, o.DevEnv.Spec.Source.Ref, "master", o.GitProvider, o.Gitter, "")
+	// AddApp, DeleteApp, and UpgradeApps delegate selecting/creating the directory to clone in to environments/gitops.go's
+	// Create function, but here we need to create the directory explicitly. since we aren't calling Create, because we're
```
Comment (hferentschik) [inline pkg/apps/gitops.go]: 👍

File: pkg/cmd/add/add_app_test.go (hunk 3 above)
Comment (hferentschik) [reply pkg/cmd/add/add_app_test.go]: Another approach would be to work against known locations. As I mentioned before, I think we should create all these temporary directories in a common base, aka JX_HOME/tmp. This way we have a place to look/scan for the created directory. 

This combined with creating the tmp directory quite high up in the call hierachy (somewhere close to _Run_), would probably get us closter to where we want to be.

For now that is probably too much to ask for ;-)

Comment (hferentschik) [reply pkg/cmd/add/add_app_test.go]: > So we either need to do the CloneDir stuff or we need to remove checking the content of the PR from the tests, which seems like a bad idea.

Maybe the tests could be split as well. Personally, I would be very reluctant to have this flag just because I need it for testing. For me it is a code smell.
