### PR TITLE
fix(windows): Disabled tests that don't work on windows

### LINKED ISSUE #2077: Can't develop on Windows
### Summary 
The unit tests won't run on Windows, making it hard/impossible to develop

### Steps to reproduce the behavior
Run unit tests on Windows, lots of them fail

### Jx version

The output of `jx version` is:

irrelevant
### Kubernetes cluster

What kind of Kubernetes cluster are you using & how did you create it?
None. 

### Operating system / Environment
Windows

### Expected behavior
all tests should pass

### Actual behavior
tests don't pass

Running `import_integration_test.go` gives:
```
=== RUN   TestImportProject
--- FAIL: TestImportProject (0.00s)
panic: unsupported [recovered]
	panic: unsupported

goroutine 66 [running]:
testing.tRunner.func1(0xc00090ac00)
	C:/Go/src/testing/testing.go:792 +0x38e
panic(0x1e61860, 0xc000270c90)
	C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/jenkins-x/jx/pkg/tests.NewTerminal(0xc00090ac00, 0xc0000bc078, 0x0, 0x0)
	C:/Users/Steve/code/jx/pkg/tests/helpers.go:101 +0x28b
github.com/jenkins-x/jx/pkg/jx/cmd_test.TestImportProject(0xc00090ac00)
	C:/Users/Steve/code/jx/pkg/jx/cmd/common_import_test.go:48 +0x12e
testing.tRunner(0xc00090ac00, 0x22c22b0)
	C:/Go/src/testing/testing.go:827 +0xc6
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:878 +0x35a

Process finished with exit code 1
```
and fails [Here](https://github.com/jenkins-x/jx/blob/239371b85c5903c6dc187386344b0d0bd6176800/pkg/tests/helpers.go#L99).
It seems that `vt10x.NewVT10XConsole` doesn't work (at least on my machine) on windows - see https://github.com/Netflix/go-expect/issues/5

### PR DESCRIPTION
**Pull request by agentgonzo**
(They still run on other platforms)

Fixes #2077 

@jtnord

### CODE REVIEW

File: pkg/jx/cmd/common_install.go [hunk 1]
```diff
@@ -1356,15 +1356,17 @@ func (o *CommonOptions) installMissingDependencies(providerSpecificDeps []string
...
-			Default: deps,
-		}
-		survey.AskOne(prompt, &install, nil, surveyOpts)
+		//prompt := &survey.MultiSelect{
+		//	Message: "Missing required dependencies, deselect to avoid auto installing:",
+		//	Options: deps,
+		//	Default: deps,
+		//}
+		//survey.AskOne(prompt, &install, nil, surveyOpts)
+		_ = survey.AskOne
```
Comment (jtnord) [inline pkg/jx/cmd/common_install.go]: This looks unrelated?

File: pkg/cloud/amazon/common_test.go [hunk 2]
```diff
@@ -53,6 +55,7 @@ func TestResolvingDefaultRegion(t *testing.T) {
 }
 
 func TestResolvingRegionFromAwsRegionEnv(t *testing.T) {
+	tests.SkipForWindows(t, "Pre-existing test. Reason not investigated")
```
Comment (jtnord) [inline pkg/cloud/amazon/common_test.go]: Should there be an issue to investigate the reason here

File: pkg/jx/cmd/common_install.go (hunk 1 above)
Comment (agentgonzo) [reply pkg/jx/cmd/common_install.go]: yeah, committed in error.

File: pkg/cloud/amazon/common_test.go (hunk 2 above)
Comment (agentgonzo) [reply pkg/cloud/amazon/common_test.go]: Probably

Comment (agentgonzo) [reply pkg/cloud/amazon/common_test.go]: grr... it's because my local environment has a `~/.aws` configuration defined, and that affects the tests.

**Comment by agentgonzo** [comment]
@jtnord @ccojocar - I went through the tests and fixed all of them except the ones that use `go-expect` (that doesn't work on windows). The list of skipped tests is now _much_ smaller

File: pkg/cloud/amazon/common_test.go [hunk 3]
```diff
@@ -2,34 +2,43 @@ package amazon_test
...
+	"runtime"
 	"testing"
 )
 
 func switchHome() (string, error) {
-	oldHome := os.Getenv("HOME")
-	newHome := "/tmp/" + uuid.New()
-	os.Setenv("HOME", newHome)
+	oldHome := amazon.UserHomeDir()
+	newHome, err := ioutil.TempDir("", "common_test")
```
Comment (jtnord) [inline pkg/cloud/amazon/common_test.go]: BTW - this doesn't look like it gets cleaned up ever....

File: pkg/config/admin_secrets_test.go [hunk 4]
```diff
@@ -14,15 +15,17 @@ func TestAdminSecrets(t *testing.T) {
 
 	testFile, err := ioutil.ReadFile("admin_secrets_test.yaml")
 	assert.NoError(t, err)
+	secretsFromFile := config.AdminSecretsConfig{}
+	err = yaml.Unmarshal(testFile, &secretsFromFile)
```
Comment (jtnord) [inline pkg/config/admin_secrets_test.go]: do you not want to assert that err is nil?

File: pkg/config/admin_secrets_test.go [hunk 5]
```diff
@@ -14,15 +15,17 @@ func TestAdminSecrets(t *testing.T) {
...
 	service := config.AdminSecretsService{}
 	service.Flags.DefaultAdminPassword = "mysecret"
 	err = service.NewAdminSecretsConfig()
 	assert.NoError(t, err)
 
-	s, err := service.Secrets.String()
-	tests.Debugf("%s", s)
+	secretsFromService := service.Secrets
+	tests.Debugf("%s", secretsFromService)
 	assert.NoError(t, err)
```
Comment (jtnord) [inline pkg/config/admin_secrets_test.go]: err won't have changed as you are no longer updating it as you removed the line

File: pkg/config/admin_secrets_test.go [hunk 6]
```diff
@@ -14,15 +15,17 @@ func TestAdminSecrets(t *testing.T) {
...
 
-	assert.Equal(t, string(testFile), s, "expected admin secret values do not match")
+	assert.Equal(t, secretsFromFile, secretsFromService, "expected admin secret values do not match")
```
Comment (jtnord) [inline pkg/config/admin_secrets_test.go]: assuming `secretsFromFile` has an `Equals`y type thing?

File: pkg/config/helm_values_test.go [hunk 7]
```diff
@@ -14,6 +15,8 @@ func TestEnvironmentExposecontrollerHelmValues(t *testing.T) {
 
 	testFile, err := ioutil.ReadFile("helm_values_test.yaml")
 	assert.NoError(t, err)
+	helmValuesFromFile := config.HelmValuesConfig{}
+	err = yaml.Unmarshal(testFile, &helmValuesFromFile)
```
Comment (jtnord) [inline pkg/config/helm_values_test.go]: `assert.NoError(t, err)`?

File: pkg/jx/cmd/common_install_test.go [hunk 8]
```diff
@@ -14,8 +16,13 @@ func TestInstallEksctl(t *testing.T) {
 	defer os.Setenv("PATH", oldPath)
 
 	defer os.Unsetenv("JX_HOME")
-	err = os.Setenv("JX_HOME", "/tmp/"+uuid.New())
+	tempDir, err := ioutil.TempDir("", "common_install_test")
```
Comment (jtnord) [inline pkg/jx/cmd/common_install_test.go]: `assert.NoError(t, err)`  or `assert.Nil(t, err)`?

File: pkg/jx/cmd/common_install_test.go [hunk 9]
```diff
@@ -14,8 +16,13 @@ func TestInstallEksctl(t *testing.T) {
...
+	err = os.Setenv("JX_HOME", tempDir)
 	assert.Nil(t, err)
 	err = (&CommonOptions{}).installEksCtl(false)
-	assert.FileExists(t, os.Getenv("JX_HOME")+"/bin/eksctl")
```
Comment (jtnord) [inline pkg/jx/cmd/common_install_test.go]: `assert.NoError(t, err)`?

File: pkg/util/commands_test.go [hunk 10]
```diff
@@ -108,25 +103,20 @@ func TestRunFailWithTimeout(t *testing.T) {
 	assert.Equal(t, "", res)
 	assert.Equal(t, true, cmd.DidError())
 	assert.Equal(t, true, cmd.DidFail())
-
-	os.Remove(exPath + "/" + tmpFileName)
-
 }
 
 func TestRunThreadSafety(t *testing.T) {
+	tests.SkipForWindows(t, "Pre-existing test. Windows doesn't have a decent sleep builtin to run no-interactively")
```
Comment (jtnord) [inline pkg/util/commands_test.go]:
```
C:\Users\jnord>timeout /?

TIMEOUT [/T] timeout [/NOBREAK]

Description:
    This utility accepts a timeout parameter to wait for the specified
    time period (in seconds) or until any key is pressed. It also
    accepts a parameter to ignore the key press.

Parameter List:
    /T        timeout       Specifies the number of seconds to wait.
                            Valid range is -1 to 99999 seconds.

    /NOBREAK                Ignore key presses and wait specified time.

    /?                      Displays this help message.

NOTE: A timeout value of -1 means to wait indefinitely for a key press.

Examples:
    TIMEOUT /?
    TIMEOUT /T 10
    TIMEOUT /T 300 /NOBREAK
    TIMEOUT /T -1
```

File: pkg/cloud/amazon/common_test.go (hunk 3 above)
Comment (agentgonzo) [reply pkg/cloud/amazon/common_test.go]: No, it doesn't. But it's only in the temp directory and the files are only small, so not a biggie.

File: pkg/config/admin_secrets_test.go (hunk 4 above)
Comment (agentgonzo) [reply pkg/config/admin_secrets_test.go]: well if something went wrong then `secretsFromFile` won't be correct so the assertion will fail, but there's no hard in checking that it's not Nil.

File: pkg/config/admin_secrets_test.go (hunk 5 above)
Comment (agentgonzo) [reply pkg/config/admin_secrets_test.go]: true.

File: pkg/config/admin_secrets_test.go (hunk 6 above)
Comment (agentgonzo) [reply pkg/config/admin_secrets_test.go]: I changed one character in the text file and the test failed, so that was good enough for me.

File: pkg/config/helm_values_test.go (hunk 7 above)
Comment (agentgonzo) [reply pkg/config/helm_values_test.go]: again, if the unmarshall fails then the assertion will also fail, but no hard in putting it in.

File: pkg/jx/cmd/common_install_test.go (hunk 8 above)
Comment (agentgonzo) [reply pkg/jx/cmd/common_install_test.go]: both seem to do the same thing in this case. @jenkins-x/core - what is the best style for this case?

File: pkg/jx/cmd/common_install_test.go (hunk 9 above)
Comment (agentgonzo) [reply pkg/jx/cmd/common_install_test.go]: Probably a good plan.

File: pkg/util/commands_test.go (hunk 10 above)
Comment (agentgonzo) [reply pkg/util/commands_test.go]: Unfortunately, if you try that as part of the test the command fails saying somethnig like "it needs to be run interactively" :-(

File: pkg/jx/cmd/common_install_test.go (hunk 8 above)
Comment (agentgonzo) [reply pkg/jx/cmd/common_install_test.go]: Looks like the difference is in the response message if the assertion fails: https://github.com/stretchr/testify/blob/master/assert/assertions.go#L1143

File: pkg/util/commands_test.go (hunk 10 above)
Comment (agentgonzo) [reply pkg/util/commands_test.go]: `failed to run 'timeout 1' command in directory 'C:\Users\Steve\code\jx\pkg\util\test_data\scripts', output: 'ERROR: Input redirection is not supported, exiting the process immediately.'`

Comment (jtnord) [reply pkg/util/commands_test.go]: apparently the workaround is
`start /wait timeout 5`

**Comment by agentgonzo** [comment]
`start` is not an executable, but a command prompt builtin command.
```
         Error:      Received unexpected error:
                    exec: "start": executable file not found in %PATH%
                    failed to run 'start /wait timeout 5' command in
directory 'C:\Users\Steve\code\jx\jx\pkg\util/test_data/scripts', output: ''
```

File: pkg/util/commands_test.go (hunk 10 above)
Comment (agentgonzo) [reply pkg/util/commands_test.go]: `start` is not an executable, but a command prompt builtin command.
```
         Error:      Received unexpected error:
                    exec: "start": executable file not found in %PATH%
                    failed to run 'start /wait timeout 5' command in
directory 'C:\Users\Steve\code\jx\jx\pkg\util/test_data/scripts', output: ''
```
