### PR TITLE
fix: UI App BDD tests

### LINKED ISSUE #5641: Enable UI App BDD tests

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #5641

### CODE REVIEW

File: jx/bdd/tekton/ci.sh [hunk 1]
```diff
@@ -47,4 +47,5 @@ jx step bdd --versions-repo https://github.com/jenkins-x/jenkins-x-versions.git
   --tests test-upgrade-ingress \
   --tests test-create-spring \
   --tests test-quickstart-golang-http \
```
Comment (abayer) [inline jx/bdd/tekton/ci.sh]: Actually, while we're here, might as well remove `test-quickstart-golang-http` from `tekton`, since it's covered in `boot-vault`.

**Comment by abayer** [comment]
`boot-vault` hung with the flaky `Couldn''t retrieve Task` thing that Prow-triggered builds automatically are retried for, so I just reran it.

**Comment by hferentschik** [comment]
w00t - this one took me a while to get in ;-)
