### PR TITLE
fix(test): waiting for HTTP to be open prior to making requests

### LINKED ISSUE #5167: pipelinecontroller tests are flaky
### Summary 

They intermittently fail connecting the http server. This happens more when under load. I have reproduced it in a devpod.

https://github.com/jenkins-x/jx/blob/master/pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go#L73

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #5167

### CODE REVIEW

**Comment by hferentschik** [comment]
/hold 

let's see whether tests are passing and trigger them a few times

File: pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go [hunk 1]
```diff
@@ -240,3 +253,29 @@ func getFreePort() (int, error) {
 	}()
 	return l.Addr().(*net.TCPAddr).Port, nil
 }
+
+func waitForOpenPort(host string, port int, timeOut time.Duration) error {
```
Comment (ccojocar) [inline pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go]: Is there any reason to not use `httptest` instead of opening directly the ports?

https://golang.org/pkg/net/http/httptest/

**Comment by abayer** [comment]
Passed, rekicking.

File: pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go (hunk 1 above)
Comment (hferentschik) [reply pkg/cmd/controller/pipeline/pipelinerunner_controller_test.go]: hmm, maybe just ignorance. How would that look like in this case? 

What's happening is that we select a "random" free port and pass it to the controller. The controller then starts its HTTP server waiting for requests. We then make a few HTTP requests to test various things.

The issue I am trying to fix is that the way the test was written, the test request would in some cases be made w/o the HTTP server being ready (at least that's what I believe atm). SO for this reason, I added this _waitForOpenPort_ method which will wait until the HTTP server is listening or the timeout occurs.

**Comment by abayer** [comment]
Test failure wasn't real - a node crashed. Rerunning.

**Comment by hferentschik** [comment]
> Test failure wasn't real - a node crashed. Rerunning.

lol
